### ISSUE TITLE
Suggest Program Options/Flags

### ISSUE THREAD

**Issue by noctuid** [zsh-users/zsh-autosuggestions#111]
Fish will suggest program options even if you've never used them before. I'm not sure if this would be easily possible, but it would be really cool. I don't know if there's been an issue for this already, but I couldn't find one when searching.

This may not be as useful for someone using something like auto-fu, but I think it would still be nice.

**Comment by PythonNut** [comment]
This might be doable with [`zsh-capture-completion`](https://github.com/Valodim/zsh-capture-completion).

**Comment by Hunsu** [comment]
> This might be doable with zsh-capture-completion. 

Can you add more details please as I don't know how to use it?

Is there any way to customize zsh-autosuggestions for certain commands? For example don't suggest: `git checkout -b branch`if `branch`already exist.

**Comment by PythonNut** [comment]
@Hunsu ah sorry. Let me clarify: this may be doable in `zsh-autosuggestions` by writing a lot of new code. It's not possible currently. 

Right now, I use [`auto-fu`](https://github.com/hchbaw/auto-fu.zsh) together with `zsh-autosuggestions`. They actually complement each other rather well, although `auto-fu` is quite painful to setup.

**Comment by ericfreese** [comment]
Please try out [`features/completion-suggestions`](https://github.com/zsh-users/zsh-autosuggestions/tree/features/completion-suggestions) branch. See the PR #330 for more info.

**Comment by noctuid** [comment]
I just tried it. It seems to work quite well for some commands (e.g. `git`). On the other hand, I get no suggestions for others like `borg` even though tab completion gives me results.

**Comment by ericfreese** [comment]
I just installed `borg` (had never heard of it before) and I don't get any tab completion results. I'm trying `borg <tab>` and I just get a list of files. I would have expected sub-commands like `init` and `create`.

Do you have custom completion scripts for it?

**Comment by noctuid** [comment]
I do not, but it's possible that my distro (Arch) ships borg with [these](https://github.com/mrkmg/borgbackup-zsh-completion). I'd have to check.

**Comment by noctuid** [comment]
Also, if I type `hg --co` it gives a correct suggestion, but it's preceded by junk characters and then my current input again (e.g. `hg --co^M^M^[[0m^[[23m^[[24m^[[Jhg --co--config`). This happens for anything with `hg`.
`

**Comment by noctuid** [comment]
I've also had my computer completely freeze twice while typing `man ...`. I can't replicate this consistently, and it may be an unrelated issue, but I haven't had this problem before today.

**Comment by noctuid** [comment]
The `hg` issues is definitely fixed, and the freezing issue is fixed as far as I can tell.

**Comment by noctuid** [comment]
The branch does not change that behavior.

**Comment by mlms13** [comment]
Ah, do completion-based suggestions only get used if no history-based suggestions exist? I'll open a separate issue for `cd` in that case.

**Comment by noctuid** [comment]
If you change the strategy order, it seems to mostly do what you want `ZSH_AUTOSUGGEST_STRATEGY=(completion history)` (though you'll still get invalid suggestions, e.g. if the current directory is empty).

**Comment by ericfreese** [comment]
This is implemented on `develop` as `completion` strategy.
