### ISSUE TITLE
Transfer this repo to a separate organization for better maintenance?

### ISSUE THREAD

**Issue by ericfreese** [zsh-users/zsh-autosuggestions#113]
This is really a question for @tarruda and @faceleg.

What do you think about transferring this repo to my employer's github organization (https://github.com/mojotech)? It would result in more eyes on the development of the project and better maintenance than I can provide alone. I believe @faceleg's [concerns of keeping this the canonical zsh autosuggest plugin](https://github.com/tarruda/zsh-autosuggestions/issues/86#issuecomment-173358158) would be solved by a redirect from this url to mojotech/zsh-autosuggestions.

More info on transferring Github repos: https://help.github.com/articles/transferring-a-repository/

**Comment by faceleg** [comment]
I'm for it, but IMHO it is @tarruda's call

**Comment by ronjouch** [comment]
What about transferring instead to https://github.com/zsh-users , which already hosts and gives visibility to a lot of successful plugins?

**Comment by tarruda** [comment]
It makes more sense to transfer this repo to zsh-users(which is a zsh-focused org), as suggested by @ronjouch.

**Comment by ericfreese** [comment]
Yeah, you're probably right. Should I reach out to zsh-users, or would you like to handle this @tarruda?

**Comment by ericfreese** [comment]
Pinging @nicoulaj. Thinking about bringing this plugin under zsh-users. Thoughts?

**Comment by nicoulaj** [comment]
Of course this project is welcome in zsh-users.

@tarruda, you can transfer the project, and since you are already an owner of the organization, you just need to edit these two teams:
 - https://github.com/orgs/zsh-users/teams/zsh-autosuggestions-admins
 - https://github.com/orgs/zsh-users/teams/zsh-autosuggestions-committers

**Comment by ericfreese** [comment]
Pinging @tarruda... I'm happy to be an admin and keep maintaining this project. Will handle the cleanup after the repo's been transferred. I think we can just pull the trigger on this whenever.

**Comment by tarruda** [comment]
Sorry for the delay, I ended up missing @nicoulaj's message. The repository is transfered :)

**Comment by nicoulaj** [comment]
Nice, teams should be properly setup now.
