### ISSUE TITLE
Will not autosuggest after certain characters

### ISSUE THREAD

**Issue by arianf** [zsh-users/zsh-autosuggestions#130]
I've noticed that after the match regex was changed, that autosuggests don't work once a `~` is typed. I believe this is because it was removed from the regex below.

```bash
"${1//(#m)[\\()\[\]|*?]/\\$MATCH}" #new 
"${1//(#m)[\][()|\\*?#<>~^]/\\$MATCH}" #old
```

Example:

<img width="313" alt="screen shot 2016-02-29 at 5 21 15 pm" src="https://cloud.githubusercontent.com/assets/7397857/13414632/04debfc4-df09-11e5-9f74-abc9181f9068.png">

<img width="363" alt="screen shot 2016-02-29 at 5 21 24 pm" src="https://cloud.githubusercontent.com/assets/7397857/13414635/08a885cc-df09-11e5-92be-e07e60c9980b.png">

**Comment by ericfreese** [comment]
I'm not able to recreate this on my machine. I've tried zsh 5.2 and 5.0.8, loading the plugin by itself, and loading the plugin with a default oh my zsh configuration.

Does the problem go away when not loading the rest of your .zshrc?

```shell
% zsh -f
%% source /path/to/zsh-autosuggestions/zsh-autosuggestions.zsh
%% rawr this is a test ~ hello world
%% rawr this is a test ~
```

If the problem goes away, would you be willing to spend some time trimming down your .zshrc to find what configuration is causing this issue?
