### ISSUE TITLE
bindkey with Ctrl+Space doesn't work anymore

### ISSUE THREAD

**Issue by timofurrer** [zsh-users/zsh-autosuggestions#132]
I just reinstalled `zsh-autosuggestions` from the new repository and since then my key binding for `autosuggest-accept` doesn't work anymore.

I overwrite my settings in the file `$ZSH_CUSTOM/autosuggestion-settings.zsh` with the following statement:

`bindkey '^ ' autosuggest-accept`

The file is definitely sourced.
I use the newest version, which is *v0.2.17* at the moment.
Other keys like `/` work like a charm. 

Does anyone have the some issue?

**Comment by ericfreese** [comment]
What is the output of `bindkey '^ '` and `echo $widgets[autosuggest-accept]`?

Does the binding work if you source `zsh-autosuggestions` without the rest of your config?

```shell
% zsh -f
%% source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
%% bindkey '^ ' autosuggest-accept
```

**Comment by timofurrer** [comment]
Output of `bindkey '^ '`:

    "^@" autosuggest-accept

Output of `echo $widgets[autosuggest-accept]`:

    user:_zsh_autosuggest_widget_accept

It doesn't work either when use `zsh -f` and source and bind manually.

My other plugins:

    plugins=(git git-extras python common-aliases command-not-found zsh-syntax-highlighting zsh-autosuggestions)

Disabling the other plugins doesn't help.

I just took a default `.zshrc` and added my stuff and uploaded it to this gist: https://gist.github.com/timofurrer/9b59786b16c1c985c54f

**Comment by ericfreese** [comment]
What do you get if you press in your terminal: <kbd>ctrl</kbd>+<kbd>v</kbd> and then <kbd>ctrl</kbd>+<kbd>space</kbd>?

What terminal and OS are you running?

Can you successfully bind '^ ' to any other widgets?

I don't think those test failures are related, but I've fixed them in another branch. I'll go ahead and pull those over and make a new 0.2.x release.

**Comment by timofurrer** [comment]
Nothing happens when I press this combination either.

It's an ubuntu 14.04 with konsole.

It doesn't work to bind '^ ' to any other widgets ...

**Comment by ericfreese** [comment]
> It doesn't work to bind '^ ' to any other widgets ...

This leads me to believe that this isn't actually a problem with this plugin, but instead has something to do with your environment. So I'm going to go ahead and close this issue.

Can you try binding a different key combination to `autosuggest-accept` and verify that it does work?

As for why ctrl+space isn't working for you, that gets outside of my knowledge, but this might put you on the right track: https://www.google.com/search?q=bindkey+ctrl+space+ubuntu+konsole

**Comment by akovski** [comment]
I run into similar problem and it turns out that some input method(e.g. ibus) is taking over the ctrl-space shortcut by default.

**Comment by unknownbreaker** [comment]
What if you tried moving your auto-suggestion keybinding to the very bottom of your zshrc file?

**Comment by kinowarrior** [comment]
Quick update to say I found this issue helpful it diagnosing own problem. Running on MacOS I had Ctrl Space mapped in system settings. Unticking the binding freed it up for usage with autocompletions. You could also just change the keybinding set here if you really need that functionality.

Screenshot below (System Preferences -> Keyboard -> Shortcuts (tab):

![Keyboard](https://user-images.githubusercontent.com/49199497/57522555-c96c9500-735d-11e9-8e67-f930158110b1.gif)

**Comment by EdmundsEcho** [comment]
Thank you.  The system shortcuts tab was the issue for me. The post saved me a lot of time.  \- E

**Comment by dilin-MS** [comment]
I am on Win 10 with WSL.
I can use `bindkey ',' autosuggest-accept` to reset the key, but I can't make `bindkey '^ ' autosuggest-accept`.
Later I figured out the reason: `ctrl+space` has been occupied by the system input method.
Setting `bindkey '^j' autosuggest-accept` works for me.
Hope this can help you, too.

**Comment by singhArmani** [comment]
Thank you, @kinowarrior, I was trying to look for the fix. This did the trick.
