### ISSUE TITLE
Does not play well with safe-paste plugin from OMZ

### ISSUE THREAD

**Issue by aaronjensen** [zsh-users/zsh-autosuggestions#145]
If I attempt to use this with safe-paste https://github.com/robbyrussell/oh-my-zsh/pull/1698 then the auto completion stays at the end of what I paste.

![safe-paste](https://cloud.githubusercontent.com/assets/8588/14497136/a68e24dc-014a-11e6-9dcd-2fa664beb71e.gif)

Split from #141

**Comment by ericfreese** [comment]
Sorry for the late response on this one. Just wanted to make clear that this will likely be low priority for me, since I don't use OMZ.

Pull requests are welcome though if someone wants to get this working!

**Comment by aaronjensen** [comment]
@ericfreese no problem, thanks for responding. I'm not using this plugin now (partly because of this bug). https://github.com/zsh-users/zsh-autosuggestions/issues/141 is more important to me any way :smile:

**Comment by HaleTom** [comment]
I've raised a PR for `safe-paste` to use the built-in Bracketed Paste Mode of zsh >= 5.1 [here](https://github.com/robbyrussell/oh-my-zsh/pull/7887).
