### ISSUE TITLE
Support full menu completion like auto-fu

### ISSUE THREAD

**Issue by PythonNut** [zsh-users/zsh-autosuggestions#15]
[`auto-fu`](https://github.com/hchbaw/auto-fu.zsh) is a set of scripts that lists all of the completions menu-style. I love the `zsh-autosuggestions` async method and the whole idea of history based completion. Is it possible to menu-complete asynchronously in the spirit of `auto-fu`? I have several conditions to make sure `auto-fu` isn't too slow:

  * Number of matches N
  * Number of displayed lines N
  * Percent lines of whole terminal

It's really cool being able too see all of the completions available (including contextual information too) and be able to choose from them. History based suggestions are also cool, but only when they're correct. Having both would be awesome.

If this isn't possible, is there a way I can have `zsh-autosuggestions` supply only history suggestions and have `auto-fu` do the rest?

Thanks for the awesome code!
PythonNut

**Comment by jirutka** [comment]
+1

**Comment by 257** [comment]
https://github.com/fish-shell/fish-shell/issues/1465

i just don't understand why no shell has implemented this yet. it feels wired that i have to post pictures from a gui application to explain it to command-line developers. this should have come from a shell to firefox not the other way around...

**Comment by PythonNut** [comment]
Something like this?

![auto-fu](https://cloud.githubusercontent.com/assets/5009546/7763299/ad358d9c-fff3-11e4-8bc6-f3b36d42dbef.PNG)

**Comment by 257** [comment]
something like that but put the first candidate/suggestion in front of the cursor, preferably in a different colour and make the first backspace remove only the suggestion. consecutive backspace(s) shall remove what user has typed.
so in the screenshot above, say 'acs' is the winning candidate and put in front of the 'em' which what's already typed by user. now first backspace will remove 'acs' altogether and second backspace removes 'm' (from 'em') and so on. 
this is very much akin to how webkit-based browser (safari, chrome) auto-complete their address bar (will post screenshots later).

see here too: [https://github.com/hchbaw/auto-fu.zsh/issues/36]

**Comment by rcywongaa-work** [comment]
FWIW: [marlonrichert/zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete) seems to integrate nicely without issue
