### ISSUE TITLE
Evals need escaping

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-autosuggestions#152]
https://github.com/zsh-users/zsh-autosuggestions/blob/87facd9b85630f288433aa0a20a963cffc612ee5/zsh-autosuggestions.zsh#L134 needs to escape `$widget` as `${(q)widget}` because the value `$widget` might be shell-unsafe.  (E.g., the plugin "opp.zsh" creates widgets with literal `(` in their names, according to a bug report (issue 278) I received over at z-sy-h, which would cause the eval to report a syntax error.)

**Comment by ericfreese** [comment]
Working on adding the `q` flags. Seems to fix the errors associated with `opp.zsh`.

I'm curious... What was the reason behind the change from

`${${widgets[$cur_widget]#*:}/:/ }`

to

`${${(s.:.)widgets[$cur_widget]}[2,3]}`

in https://github.com/zsh-users/zsh-syntax-highlighting/commit/11d378332e875f5c215f62de82f68deeba912d76 and https://github.com/zsh-users/zsh-syntax-highlighting/commit/cb02451a4e08d7c0157595db52769ed994aea3b5?

**Comment by danielshahaf** [comment]
Forward compatibility in case more colon-separated fields are added at the end in the future.

But you should review the combined diff 4849ef3..cb02451; most of the interim commits were stupid mistakes and their corrections.
