### ISSUE TITLE
bindkey ctrl-return?

### ISSUE THREAD

**Issue by dragonxlwang** [zsh-users/zsh-autosuggestions#154]
I would like to have ctrl-return mapped to ``autosuggest-execute``

I have tried bindkey with ``^enter'' , ``^^M`` etc but none of them works.

Is there a way to do so?

Thanks,

**Comment by ericfreese** [comment]
I'm personally not sure if this is possible with zsh.

You might have some luck emailing the `zsh-users` email list: http://zsh.sourceforge.net/Arc/mlist.html

I'm going to go ahead and close this issue since it doesn't relate specifically to the plugin.

Good luck!

**Comment by modk** [comment]
In case anyone is having the same problem, just use `cat` without arguments to find out which escape sequence your terminal is emitting for ctrl-enter:
``
cat

^[[28;5;9~
``

Then bind it like this `bindkey -s '^[[28;5;9~' '^E\n'` in your `~/.zshrc`.

**Comment by cvuorinen** [comment]
This did the trick for me:

```
bindkey '^\n' autosuggest-execute
```
