### ISSUE TITLE
forward-char on iterm mac not working

### ISSUE THREAD

**Issue by rogoit** [zsh-users/zsh-autosuggestions#159]
Hi,

i only can do the full suggestion to end of the line with the arrow key on mac iterm.

I use this settings from eric
`# Remove forward-char widgets from ACCEPT
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=("${(@)ZSH_AUTOSUGGEST_ACCEPT_WIDGETS:#forward-char}")

# Add forward-char widgets to PARTIAL_ACCEPT
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(forward-char)`

But it is still not working. I use this version
`commit 87facd9b85630f288433aa0a20a963cffc612ee5
2016-03-14 21:50 Eric Freese                     o Fix #133                                          │Refs: [master], {origin/master}, {origin/HEAD}, <v0.3.1>`

Thx for help
Roland

**Comment by ericfreese** [comment]
If I understand you correctly, the partial accept functionality isn't working for you?

Some questions for you:
- Where did you put the above configuration (what you referred to as "this settings from eric")?
- What is the output of `echo $ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS`?
- What is the output of the following:
    - Type `bindkey "`
    - Press <kbd>ctrl</kbd>+<kbd>v</kbd> and then <kbd>→</kbd> (your right arrow key)
    - Type the finishing quote `"`
    - When completed this something like `bindkey "^[[C"`

P.S. Next time, use the triple backtick for multi-line code blocks: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by ericfreese** [comment]
Going to go ahead and close this because of inactivity. Just reply here if you're still having trouble and I will re-open.

**Comment by rogoit** [comment]
bindkey '^f' vi-forward-blank-word

and then control + f
