### ISSUE TITLE
Fetch Suggestions Asynchronously

### ISSUE THREAD

**Issue by ericfreese** [zsh-users/zsh-autosuggestions#170]
Will solve a number of performance problems.

Was implemented by @PythonNut using `zsh-async` in PR #134, but I think we should be able to implement it without adding the dependency.

Seems to me the only real way to make this asynchronous is to have another process that's responsible for fetching the suggestion. `zsh-async` uses `zpty`s, which might be the best solution. I've also looked a bit into `coproc` (see gist [here](https://gist.github.com/ericfreese/20db47bc62b9df3e28732ea03c1bc811)), but mostly decided they're not the best way forward.

Next will be looking into `zpty`.

**Comment by PythonNut** [comment]
:+1: looking forward to a better solution.

**Comment by ericfreese** [comment]
Merged into `develop`.
