### ISSUE TITLE
Suggestions Font Color In Guake Terminal Like The Default Terminal Font Color

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [zsh-users/zsh-autosuggestions#171]
Hi,

I use [Guake terminal](http://guake-project.org) with the default Ubuntu terminal, in the Ubuntu terminal, the suggestions color looks cool(darker than the default terminal font color).
![selection_103](https://cloud.githubusercontent.com/assets/5562839/15984076/628828b4-2fc6-11e6-862b-9afa46f1db18.png)

But in Guake terminal the suggestions font color like the default font color.

![selection_104](https://cloud.githubusercontent.com/assets/5562839/15984087/d6f88766-2fc6-11e6-9263-d6b1bf462f7d.png)

All the best,
Mohammed

**Comment by ericfreese** [comment]
Hi Mohammed,

I'd guess this has something to do with your color scheme in Guake. Can you try setting the suggestion color to something else (like green, which appears to be working) to see if suggestion coloring is working for you at all? If that works, then you may try adjusting your color scheme, changing the light gray color to be a bit darker.

**Comment by MohammedAl-Mahdawi** [comment]
Hi Eric,

Thank you so much for your reply.

You are right, it is working fine now!

Here is what I did:

1. run `echo $ZSH_CUSTOM` and the result was `/home/mohammed/.oh-my-zsh/custom`

2. run `cd /home/mohammed/.oh-my-zsh/custom`

3. run `touch my_patches.zsh`

4. run `vim my_patches.zsh` and put in the file `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=black,bold'` save the file.

5. Change my Guake terminal color scheme to `Tango`

6. Opening new tab.

Now everything is fine.

All the best,
Mohammed

**Comment by unlocomqx** [comment]
Thank you @MohammedAl-Mahdawi 
Here's a one liner for convenience
`echo "ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=black,bold'" >> $ZSH_CUSTOM/my_patches.zsh`
