### ISSUE TITLE
Very white color as default

### ISSUE THREAD

**Issue by dwaindibbly** [zsh-users/zsh-autosuggestions#172]
There is a very white color ( same as terminal foreground ) for default and I do not know how to change it to dark grey ( i know how to change it ( sort of ) ), using solarized dark colors

**Comment by ericfreese** [comment]
> I do not know how to change it

See the section on configuration in the readme: https://github.com/zsh-users/zsh-autosuggestions

**Comment by ericfreese** [comment]
> i know how to change it ( sort of )

You're going to need to get a bit more specific. Can you describe the specific problem you're having?

**Comment by dwaindibbly** [comment]
what number of color is grey.

**Comment by ericfreese** [comment]
> what number of color is grey

Gray is 8 (the default). Your color scheme likely defines the gray color (color 8) as a white color.

Here's a handy table of colors for 256-color terminals (colors will be slightly different under your color scheme):

<img src="http://misc.flogisoft.com/_media/bash/colors_format/256-colors.sh.png">

More info: http://misc.flogisoft.com/bash/tip_colors_and_formatting

**Comment by hlascelles** [comment]
You can also run `spectrum_ls` in your zsh at any time to see the colour swatch of your terminal.
