### ISSUE TITLE
Auto-suggestion appearing in normal color as text, rather than the more discrete gray.

### ISSUE THREAD

**Issue by TheMadCoder1** [zsh-users/zsh-autosuggestions#174]
How should I fix this? The default color is just the normal white text for the auto-suggestion, and I really want the more muted gray as in the demo. For now, I am using fg=4, as that is the best I can find that isn't the nice gray.

**Comment by TheMadCoder1** [comment]
By the way, I am running Linux Mint 17.2 Cinnamon, and my Terminal Emulators are Guake and Gnome-Terminal with a slightly modified Solarized Dark color scheme. Though color scheme does not affect the issue.

**Comment by ericfreese** [comment]
Take a look at #171 and #172. This is very likely a color scheme issue.
