### ISSUE TITLE
sh: zle: command not found

### ISSUE THREAD

**Issue by zhangwei900808** [zsh-users/zsh-autosuggestions#175]
sh-3.2# source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
sh: zle: command not found
sh: /var/root/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 126: syntax error near unexpected token `('
sh: /var/root/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 126: `		user:_zsh_autosuggest_(bound|orig)_*);;'
sh-3.2#

**Comment by zhangwei900808** [comment]
how can I solove this problem?

**Comment by george-b** [comment]
You have to be running zsh. From the `sh-3.2` in your prompt I'm going to guess you're running  bash.

**Comment by zhangwei900808** [comment]
you are right! Thank you^_^
