### ISSUE TITLE
why I lost my zsh-autosuggestions when I clone oh-my-zsh from github

### ISSUE THREAD

**Issue by zhangwei900808** [zsh-users/zsh-autosuggestions#176]
you can see it!!!
![qq20160710-2 2x](https://cloud.githubusercontent.com/assets/4385154/16711008/e98b3ad6-4678-11e6-8375-4343bd7ef036.png)

**Comment by zhangwei900808** [comment]
now I open new terminal session but no autosuggestions.
I just set oh-my-zsh and you can look up , how can I solve this problem?

**Comment by woobamboo** [comment]
Me too! Can u solve this problem now?How?

**Comment by ericfreese** [comment]
I'm having trouble understanding what exactly the problem is. Can you try to describe the problem you're having a bit more clearly?
