### ISSUE TITLE
Suggestions are invisible

### ISSUE THREAD

**Issue by s0r00t** [zsh-users/zsh-autosuggestions#181]
Using latest zsh 5.2 + OMZ on x64 Arch. z-asug is loaded as a plugin.

The suggestions are not showing up : I can see the suggested character under my cursor, but nothing after it.

Setting different colors did not change anything.

**Comment by ericfreese** [comment]
Take a look at #171, #172, and #174. This is very likely a color scheme issue.

**Comment by s0r00t** [comment]
Setting 'fg=1' (which is red here) or any other color does not change anything, while the colors displays when using a test script.

**Comment by ericfreese** [comment]
Do you see the same problem when running z-asug by itself?

```
% zsh -f
%% source your/path/to/zsh-autosuggestions.zsh
```

**Comment by s0r00t** [comment]
Yes.

**Comment by ericfreese** [comment]
Can you confirm the same problem occurs in another terminal emulator?

**Comment by s0r00t** [comment]
I just tested sourcing the file in a `zsh -f` and exporting ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE with a different color, and the completions showed up.

The problem seems to come from .zshrc and the variable re-definition.

**Comment by ericfreese** [comment]
Ok, cool. Yeah, make sure you're setting the variable after the plugin is sourced.

**Comment by ericfreese** [comment]
This page on OMZ might be helpful: https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-internals

**Comment by s0r00t** [comment]
Alright, the var had to be set after sourcing OMZ.sh.

Thanks for the help ;) You might want to add something in the README about the position of the variable setting in .zshrc, when using OMZ (normally putting it anywhere in the file works), also add something to avoid more tickets about invisibles suggestions :p

**Comment by s0r00t** [comment]
I did, but for simplicity's sake, I'm putting everything in my .zshrc.
