### ISSUE TITLE
Doesn't seem to work in oh-my-zsh at all

### ISSUE THREAD

**Issue by turkeyphant** [zsh-users/zsh-autosuggestions#182]
Just pulled and added to ~/.zshrc, not seeing any autosuggestions at all. Tried removing all other plugins, still no dice?

**Comment by ericfreese** [comment]
Have you followed closely [the instructions from the readme](https://github.com/zsh-users/zsh-autosuggestions#oh-my-zsh)?

**Comment by turkeyphant** [comment]
Yes.

**Comment by ericfreese** [comment]
Can you get it working by manually sourcing it?

`source path/to/zsh-autosuggestions.zsh`

**Comment by turkeyphant** [comment]
Tried that too.

**Comment by fallenpixel** [comment]
Crazy idea, I found your issue, thinking I had the same problem using antigen. However in my case it least it was just the themeing of my ZSH causing the text of the suggestion to appear in the same color as the background. If you execute `echo 'hello'`  followed by `ech` and the right arrow key, does the completion work? If it does, run `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'` in your shell. The completion should display properly. You can try changing the number as well to see what fits in best with your shell. Then this can be added to `~/.zshrc` to make the change permanent.

**Comment by turkeyphant** [comment]
Amazing! Thank you!

**Comment by fallenpixel** [comment]
Glad that did it. Enjoy your autosuggestions.

**Comment by jedahan** [comment]
Is there a way for autosuggestions to detect if the background color is the same and auto-switch to fg=6 as a workaround?

**Comment by turkeyphant** [comment]
A single line in the readme warning of this should suffice. Or having the default an obnoxious colour with instruction to customise after install.

**Comment by solomonxie** [comment]
@fallenpixel thanks that `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'` works perfectly for my iTerm2. somehow it doesn't need that to be worked on Terminal.app

**Comment by superarts** [comment]
> @fallenpixel thank you so much for posting your finding! It drives me crazy for the past couple hours.
> 
> Follow your lead, I find out that the issue is coming particular from iTerm2, (while the Mac Terminal is unaffected as @solomonxie point out). Also, in my case, setting `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` to anything higher than 7 would not work. That leads me to discover that somehow my color profile is set to Terminal `xterm` instead of `xterm-256color`. The setting is at Profiles -> [Profile Name] -> Terminal -> Report terminal type.
> 
> So, at default `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=8` cause `xterm` to unable to render the color, thus render it as default frontground text. You can either change it to lower value, or change terminal type to `xterm-256color` to render more color.

This fixed my problem, thank you!

**Comment by chipacode** [comment]
> Crazy idea, I found your issue, thinking I had the same problem using antigen. However in my case it least it was just the themeing of my ZSH causing the text of the suggestion to appear in the same color as the background. If you execute `echo 'hello'` followed by `ech` and the right arrow key, does the completion work? If it does, run `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'` in your shell. The completion should display properly. You can try changing the number as well to see what fits in best with your shell. Then this can be added to `~/.zshrc` to make the change permanent.

""" ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6' """ !!!

All time wasted, a simple color problem ಠ_ಠ

**Comment by jayagami** [comment]
I did not check all answers, in case nobody noticed.
You should put it before soruce omz  , like:

```zsh
plugins=(git)
plugins=(zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
```

**Comment by anaetrezve** [comment]
> I did not check all answers, in case nobody noticed.
> You should put it before soruce omz , like:
> 
> ```shell
> plugins=(git)
> plugins=(zsh-autosuggestions)
> ```

This worked for me.

**Comment by BlackKhm** [comment]
> @fallenpixel thank you so much for posting your finding! It drives me crazy for the past couple hours.
> 
> Follow your lead, I find out that the issue is coming particular from iTerm2, (while the Mac Terminal is unaffected as @solomonxie point out). Also, in my case, setting `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` to anything higher than 7 would not work. That leads me to discover that somehow my color profile is set to Terminal `xterm` instead of `xterm-256color`. The setting is at Profiles -> [Profile Name] -> Terminal -> Report terminal type.
> 
> So, at default `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=8` cause `xterm` to unable to render the color, thus render it as default frontground text. You can either change it to lower value, or change terminal type to `xterm-256color` to render more color.



> Crazy idea, I found your issue, thinking I had the same problem using antigen. However in my case it least it was just the themeing of my ZSH causing the text of the suggestion to appear in the same color as the background. If you execute `echo 'hello'` followed by `ech` and the right arrow key, does the completion work? If it does, run `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'` in your shell. The completion should display properly. You can try changing the number as well to see what fits in best with your shell. Then this can be added to `~/.zshrc` to make the change permanent.

I don't know why it does not work for me, me using ubuntu version 22.04
