### ISSUE TITLE
$POSTDISPLAY not available anymore

### ISSUE THREAD

**Issue by OmeGak** [zsh-users/zsh-autosuggestions#184]
I have a widget for debugging `zle` widgets that shows all buffers. I used to be able to get the suggestion segment in `$POSTDISPLAY` but after upgrading I see the variable is always unset. I found e87bc74654268c51541bae3ca526a2b3a702dc13 changed the behavior. Is there any other way I can access to it?

``` bash
debug() {
    zle -M "$POSTDISPLAY"
}
zle -N debug
bindkey '^O' debug
```

**Comment by ericfreese** [comment]
Probably the best solution for this problem would be to add to the config a list of widget names that should be ignored. Then you could add your `debug` widget to that list.

For now, you should be able to add your `debug` widget to the list of partial accept widgets (`ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS`). It's a little wonky, but as long as it doesn't move the cursor, you shouldn't get any extra effects.

```
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(debug)
```

**Comment by ericfreese** [comment]
Give the [`features/ignore_widget_list`](https://github.com/zsh-users/zsh-autosuggestions/tree/features/ignore_widget_list) branch a shot, and add your `debug` widget to `ZSH_AUTOSUGGEST_IGNORE_WIDGETS` array.

**Comment by OmeGak** [comment]
Thanks a lot! Adding it to `ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS` seems to work fine. 

I also checked out `develop` and the behavior of  adding the widget to `ZSH_AUTOSUGGEST_IGNORE_WIDGETS` doesn't really work as expected. While `$POSTDISPLAY` is available in my widget, executing it causes the `$POSTDISPLAY` segment to lose its grayed-out highlight. It's just aesthetic as moving the cursor grays it out again.

**Comment by pirj** [comment]
Doesn't seem to be a problem anymore on [v0.4.0](https://github.com/zsh-users/zsh-autosuggestions/tree/v0.4.0). @OmeGak do you mind closing it?
