### ISSUE TITLE
shunit2 - no such remote ref

### ISSUE THREAD

**Issue by dw72** [zsh-users/zsh-autosuggestions#185]
I have problem when updating using zgen:

`-- zgen: Updating '/home/max/.zgen/zsh-users/zsh-autosuggestions-master' ...
Already up-to-date.
error: no such remote ref 46973db9df87bd5fdadea74cb472a99f212a0d3a
Fetched in submodule path 'vendor/shunit2', but it did not contain 46973db9df87bd5fdadea74cb472a99f212a0d3a. Direct fetching of that commit failed.
`

**Comment by ericfreese** [comment]
Not sure what's going on there. Might be easiest to just uninstall/reinstall? Sorry I can't be more helpful. I'm not very familiar with zgen.

**Comment by dw72** [comment]
I changed zgen to zplug and problem disappeard...  Conclusion? probably problem was with zgen, not your plugin.
