### ISSUE TITLE
Slow character-like pasting with zsh-autosuggestions on

### ISSUE THREAD

**Issue by yevhen-m** [zsh-users/zsh-autosuggestions#186]
Hey.
When I paste any text after the prompt, it is pasted character by character. When the plugin is off, everything works smoothly, text is all pasted immediately. How can I fix this?

```
zsh 5.0.2
autosuggestions revision 62cdba4
```

**Comment by balta2ar** [comment]
@yevhen-m This is a duplicate of #136. Related: #164, #170, #180, #169. Stay tuned.
