### ISSUE TITLE
maximum nested function level reached

### ISSUE THREAD

**Issue by metalmac** [zsh-users/zsh-autosuggestions#187]
Hello Guys,

Have you ever ran into this issue?
Just after I installed this plugin into oh-my-zsh, and source the .zshrc file, it poped out 

_zsh_autosuggest_bound_forward-char:2: maximum nested function level reached
![zhs_plugin_issue 2016-08-17_105752](https://cloud.githubusercontent.com/assets/1448776/17723062/7eedbc9e-6469-11e6-8fe2-119985182a81.jpg)

**Comment by metalmac** [comment]
In addtion, this situation occcured right after I source the .zshrc accidentally.

**Comment by metalmac** [comment]
In addtion, this situation occcured right after I accidentally source the .zshrc twice.

**Comment by ericfreese** [comment]
I believe this is a duplicate of #126. There are currently problems with sourcing the plugin multiple times.

**Comment by metalmac** [comment]
Thanks I will check #126 ,but it seems that it doesn't have a solution to it though.

**Comment by ericfreese** [comment]
Correct. Solution for now is to only source it once.

**Comment by albertjone** [comment]
source it once, means you may start a new session and use workon or other commands and you will find it work.

**Comment by TAI-REx** [comment]
Im start a new sessions and it doesnt work. any ideas folk?
