### ISSUE TITLE
Suggestion added to the end of pasted text

### ISSUE THREAD

**Issue by yevhen-m** [zsh-users/zsh-autosuggestions#190]
When I paste into gnome terminal `<C-S-v>` and I there is a suggestion from the plugin after I start a command,  I get this suggestion inserted after my pasted text.
For example, if I type `echo spam` and the next time I type `echo` and insert anything, `spam` is added to the end of the command.

```
autosuggestion  62cdba4
gnome-terminal 3.6.2
ubuntu 14.04
```

**Comment by ericfreese** [comment]
I'm not sure I understand the problem you're having. Can you provide a screen capture? Or a more clear explanation of the problem?

**Comment by yevhen-m** [comment]
![screenshot 2016-10-06 10 56 08](https://cloud.githubusercontent.com/assets/10185058/19144660/87b9fd62-8bb3-11e6-9265-e2f047d6769a.png)
So, I have a suggestion from autosuggestions plugin. When I paste text from clipboard, this suggestion is added to the end of it. This added text (`spam`) is not passed to `echo` command, it just sits on the line and confuses me.

**Comment by yevhen-m** [comment]
I suppose it has been fixed, no longer experience this issue.

**Comment by aserrallerios** [comment]
I can reproduce it using the oh-my-zsh plugin `safe-paste`.

**Comment by ericfreese** [comment]
@aserrallerios That may be related to #145
