### ISSUE TITLE
Suggestion: reverse-i-search functionality

### ISSUE THREAD

**Issue by jmredfern** [zsh-users/zsh-autosuggestions#192]
I wonder if you have considered adding reverse-i-search functionality to this plugin, which I think would enhance this nice plugin even more. A keypress which will also cycle through all matching lines in the bash history.

Best regards,
Jim

**Comment by protist** [comment]
If you want i-search to match previous commands that have the same *beginning* as the typed string, then you can just use the built-in zsh functions. I've bound it to `PgUp` and `PgDown` here.
```
bindkey "^[[5~" history-beginning-search-backward
bindkey "^[[6~" history-beginning-search-forward
```

**Comment by ericfreese** [comment]
I'm going to go ahead and close this since there hasn't been much activity and there is a pretty good workaround using `history-beginning-search{forward,backward}`
