### ISSUE TITLE
Display same color

### ISSUE THREAD

**Issue by abhigenie92** [zsh-users/zsh-autosuggestions#194]
The autocomplete doesn't have a different color than something that was typed into the shell. I tried installing as a plugin as well as manually, still no difference.

**Comment by z0rc** [comment]
See #174, #172, #171. Probably it's an issue with your color scheme.

**Comment by abhigenie92** [comment]
![image](https://cloud.githubusercontent.com/assets/12474640/18997999/711de446-8754-11e6-86da-0efae2d9cb17.png)
The color in the suggestion is same the default text color. I tried the suggestion but it doesn't it.

**Comment by ericfreese** [comment]
Have you tried setting the `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` variable? See the section on configuration in the readme: https://github.com/zsh-users/zsh-autosuggestions#configuration
