### ISSUE TITLE
Accept part of a suggestion

### ISSUE THREAD

**Issue by malimM** [zsh-users/zsh-autosuggestions#199]
My apologies if the title doesn't make sense.

What I mean is if I type ```sudo t```, then a suggestion should be to complete upto ```sudo tlp``` and not the entire previously typed command of ```sudo tlp start``` because now I want to type ```sudo tlp bat```.

**Comment by ericfreese** [comment]
I believe there is actually already support for what you're trying to do. Check out [the section of the readme on configuring widgets](https://github.com/zsh-users/zsh-autosuggestions#widget-mapping) and the [`ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS`](https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/config.zsh#L43) configuration variable. By default, the `forward-word` widgets will accept the first word in the suggestion.

**Comment by malimM** [comment]
@ericfreese Yes! This is perfect, thank you.
