### ISSUE TITLE
Cursor will disappear if there is matched command in neovim terminal

### ISSUE THREAD

**Issue by hiberabyss** [zsh-users/zsh-autosuggestions#200]
When enable `zsh-autosuggestions`, if there is a matched command in neovim terminal, then the cursor will disappear.

How to reproduce:
1. Execute `nvim -u NONE`
2. Execute `:terminal zsh` in neovim
   ![image](https://cloud.githubusercontent.com/assets/2898670/19524654/0e019fcc-9651-11e6-8808-7182a9900baf.png)
3. Type `wd` in the terminal, the cursor disappeared.
   ![image](https://cloud.githubusercontent.com/assets/2898670/19524687/2736c972-9651-11e6-8e88-7f31e8767c7d.png)

Versions:
zsh-autosuggestions: fedc22e9
Neovim: v0.1.6-250-g2d96140
zsh: 5.2

Thanks!

**Comment by doubleloop** [comment]
This may not be `nvim` specific.. Today I opened gnome-terminal and also observed cursor disappearing, even with a clean zshrc:
```
% cat ~/.zshrc
source ~/.oh-my-zsh-custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
% cd ~/.oh-my-zsh-custom/plugins/zsh-autosuggestions
% git rev-parse @                                   
c7d4a85031c101ef9bce0018096622087894dd09
% gnome-terminal --version
GNOME Terminal 3.26.2 Using VTE version 0.50.2 +GNUTLS
% zsh --version
zsh 5.4.2 (x86_64-debian-linux-gnu)
```
Normaly I use tilix and did not observe any problem there
```
% tilix --version
Versions
	Tilix version: 1.7.2-0.0.1
	VTE version: 0.50
	GTK Version: 3.22.26
```

**Comment by pasimko** [comment]
Same issue.
```gnome-terminal --version
# GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS
zsh 5.5.1 (x86_64-unknown-linux-gnu)```

**Comment by ericfreese** [comment]
Going to close this because of lack of activity. Feels more like a terminal emulator bug (or at least an upstream zsh bug) than a problem with this plugin. We can re-open if we get clearer repro steps.

**Comment by Wei-Mao** [comment]
I also encountered the same problem

**Comment by liberninja** [comment]
Just had the same issue, but only with my xfce terminal. Works fine in Kitty and urxvt. I wonder if there's a way to disable autosuggestion just for a specific terminal.

**Comment by mohssineAboutaj** [comment]
in **gnome-terminal** i found that issue coming from [zsh autosuggestion](https://github.com/zsh-users/zsh-autosuggestions)
the solution is to modify color values as they said [here](https://github.com/zsh-users/zsh-autosuggestions#suggestion-highlight-style)
here is my config
``ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=cyan,bg=transparent,bold,block"``
