### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by Kenmmm** [zsh-users/zsh-autosuggestions#204]
Thank you for the tool,but, Can you add this small feature? [incr.zsh](http://mimosa-pudica.net/zsh-incremental.html)

**Comment by PythonNut** [comment]
[`auto-fu.zsh`](https://github.com/hchbaw/auto-fu.zsh) is essentially the successor to `incr.zsh`. And you can use both it and `zsh-autosuggestions` at the same time. [My config](https://github.com/PythonNut/zsh-config) does so, although my config is a rather interesting beast that I'm not sure people should be reading.

**Comment by PythonNut** [comment]
@Alessandro-Barbieri you might want to leave an issue on my config, so I won't forget to get to it.

**Comment by Alessandro-Barbieri** [comment]
ok this works for me (I had to change colour because with solarized dark theme was invisible)
```
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=grey'
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(
    "expand-or-complete"
    "pcomplete"
    "copy-earlier-word"
)
bindkey '^ ' autosuggest-accept
```
