### ISSUE TITLE
zsh-autosuggestion breaks zle-isearch-update widget

### ISSUE THREAD

**Issue by docwhat** [zsh-users/zsh-autosuggestions#207]
It seems that zsh-autosuggestion is breaking the `zle-isearch-update` widget, which is loaded for use by `zsh-syntax-highlighting`.  I troubleshot this problem in zsh-users/zsh-syntax-highlighting#387 if you want to see the history.

Basically, if the `zle-isearch-update` widget is rebound and `history-incremental-pattern-search-backwards` is bound to `^R` then search fails after a (small) random number of items in the history.

I created a minimal test case for you: https://gist.github.com/docwhat/0cd192c066a5f9da69244f1631c5d481

Clone it, run `./setup.sh` and then `./fake-home.sh` and try to search backwards for `hi ` via `^R`.

A work around for this is to [add `zle-isearch-update` to the widget ignore list](https://github.com/docwhat/dotfiles/blob/master/zsh/startup/0plugins.zsh#L63-L68).

I also submitted PR #206 which would also fix this, via a sledge hammer.

**Comment by ericfreese** [comment]
Thank you for this. I will investigate soon.
