### ISSUE TITLE
Password asked after typing anything in prompt

### ISSUE THREAD

**Issue by extink** [zsh-users/zsh-autosuggestions#208]
When using this plugin (latest version: fedc22e9bbd046867860e772d7d6787f5dae9d4c) and starting up a prompt and typing something will ask for the sudo password making it unusable.

Tested it with (all latest versions):
- antibody
- antigen
- zplug

Tested it with and without other plugins.

**Comment by ericfreese** [comment]
This sounds very strange. Can you reproduce running `zsh -f` and sourcing the plugin file manually?
