### ISSUE TITLE
Accept upto first blank space

### ISSUE THREAD

**Issue by mustaqimM** [zsh-users/zsh-autosuggestions#210]
I remember having it set before but now I am unable to get it to work. I wish to to press ```->``` to accept the first word, like this: ```bindkey '^f' vi-forward-blank-word``` but when I try to set it to the right arrow, it doesn't work. The output from ```cat -v``` for ```->``` is ```^[[C```

**Comment by ericfreese** [comment]
Let me just make sure I'm understanding clearly what you're trying to do:

If the cursor is at the end of the buffer, you'd like the right arrow key (<kbd>→</kbd>) to accept the first word of the suggestion (up to the first space). Otherwise, if your cursor is not at the end of the buffer, you'd like the right arrow key to move the cursor forward one character.

Is that correct?

**Comment by mustaqimM** [comment]
I mean like this: https://i.imgur.com/3ttPfTs.png
If I typed `sudo`, this cursor is now situated after `o`. Now if I press `→` it should accept only up to the end of `hddtemp`

**Comment by ericfreese** [comment]
What would you expect the right arrow to do if your cursor was between the `u` and the `d`? Say if you typed in "sudo" and then hit the left arrow twice. Would you expect the right arrow key to always go forward to the end of the word?

**Comment by mustaqimM** [comment]
No then it would just move the cursor, ```sudo``` would still be typed ofcourse. The cursor would move preferably(after moving left twice and right once) to the space after ```sudo```. Is that what you mean?

**Comment by g3-3k** [comment]
hi! same aim for me, no idea how to do, any suggestion?

**Comment by ericfreese** [comment]
This doesn't seem to work right, but you could play around with something like this:

```shell
forward-char-or-word() {                              
  if (( $CURSOR == $#BUFFER )); then
    zle forward-word
  else
    zle forward-char
  fi
}

zle -N forward-char-or-word

bindkey '^[[C' forward-char-or-word
```
