### ISSUE TITLE
What is the license of zsh-autosuggestions ?

### ISSUE THREAD

**Issue by shirishag75** [zsh-users/zsh-autosuggestions#212]
# I looked at the zsh-autosuggestions and spefifically at LICENSE 

https://github.com/zsh-users/zsh-autosuggestions/blob/master/LICENSE

I didn't find any clarity as to under which license does zsh-autosuggestions exist ?

For inspiration you could look at zsh's own copyright file which goes overboard a bit but gives credit to all the authors and various licenses under which the software could be used. 

Can this be fixed with zsh-autosuggestions. 

This is necessary as i wanted to file an RFP - Request for package in Debian 

```
Subject: RFP: zsh-autosuggestions -- Fish-like fast/unobtrusive autosuggestions for zsh.
Package: wnpp 
Severity: wishlist 

 Package name    : zsh-autosuggestions
  Version         : 0.3.3 
  Upstream Author : Name <somebody@example.org>
* URL             : http://www.example.org/
* License         : (GPL, LGPL, BSD, MIT/X, etc.)
  Programming Lang: (C, C++, C#, Perl, Python, etc.)
  Description     : Fish-like fast/unobtrusive autosuggestions for zsh.
```

can this be fixed ?

**Comment by ericfreese** [comment]
The license was around before I got involved with the project, but it looks like it is an MIT license.

See text of MIT license here: https://opensource.org/licenses/MIT
