### ISSUE TITLE
Doesn't work with VIM

### ISSUE THREAD

**Issue by Loxzibit** [zsh-users/zsh-autosuggestions#216]
Getting this error (see below) when i try to tab-complete with vim. Don't get the issues with Nano.

__Error Message:__
`_arguments:451: _vim_files: function definition file not found`

__ZSH Version__
`zsh 5.2 (x86_64-apple-darwin16.0)`

__Antigen__
`Antigen v1.4.0`

__VIM__
`version 7.4.898`

__Zshrc Config__
```
source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle composer
antigen bundle docker
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle djui/alias-tips

antigen theme agnoster

antigen apply
```

**Comment by ericfreese** [comment]
Are you sure this has to do with this plugin? What happens if you comment out `antigen bundle zsh-users/zsh-autosuggestions` in your config? Do you still see the error message?

**Comment by ericfreese** [comment]
Going to go ahead and close this. Feel free to re-open if you confirm it is an issue with this plugin.
