### ISSUE TITLE
Tab in history is broken

### ISSUE THREAD

**Issue by Eyenseo** [zsh-users/zsh-autosuggestions#220]
Hello folks,
if there is a tab in the history the suggestion is currently showing a `\t` - below you can see what I mean.

<a href="https://asciinema.org/a/a1270r00ypkpjzpgdbw862jox" target="_blank"><img src="https://asciinema.org/a/a1270r00ypkpjzpgdbw862jox.png" width="150"/></a>

I bisected the commits and found that 63816c5d introduces the behaviour.

**Comment by ericfreese** [comment]
Thanks for the report @Eyenseo. It looks like this is related to #209. Please try the develop branch and let me know if the problem persists.
