### ISSUE TITLE
rpm/debian packages

### ISSUE THREAD

**Issue by nicoulaj** [zsh-users/zsh-autosuggestions#222]
Hi,

I have started creating packages for zsh-users projects on OpenSUSE build service: https://build.opensuse.org/project/subprojects/shells:zsh-users

It is an easy way to build, maintain and distribute packages for many distributions at once (Debian and derivatives/RHEL and derivatives/Fedora/SUSE...). The packaging quality is very low (just puts files in /usr/share), but I guess it can still be useful to users, and we can improve it later if experienced packagers step in.

The package for this project is [here](https://build.opensuse.org/package/show/shells:zsh-users:zsh-autosuggestions/zsh-autosuggestions), and users can download it from [here](https://software.opensuse.org/download.html?project=shells%3Azsh-users%3Azsh-autosuggestions&package=zsh-autosuggestions).

Maybe you could add a mention in your README like [I did in zsh-completions](https://github.com/zsh-users/zsh-completions#using-packages) ?

**Comment by ericfreese** [comment]
👍 Thanks! I'll get to this when I can. If you have time to submit a PR it'd be greatly appreciated.
