### ISSUE TITLE
Introduce command to automatically update this plugin

### ISSUE THREAD

**Issue by ecbrodie** [zsh-users/zsh-autosuggestions#224]
Since this plugin needs to be manually installed via `git clone` into my OMZ custom plugins directory, I am not sure if it is being automatically updated when I load my shell.

If it is not being automatically updated, then I think it would be a good idea that a command is introduced to trigger an update of the plugin. I guess I could just `cd` into the directory and run `git pull`, but that seems more manual and tedious than it should be. Having this run automatically would be great so that I don't need to remember to update this plugin occasionally. However, if not possible to be automatic, then just introducing an alias or function to update would be nice. Then I could just add it to my `.zshrc` file. Thank you.

**Comment by jedahan** [comment]
I would prefer for plugins to not start managing themselves separately than using something like git, antigen, zgen, zplug, or zpm. I'm sure an alias/function can be added as a one liner to your own zshrc separately than the plugin.

**Comment by ericfreese** [comment]
I agree with @jedahan. I generally don't think there's much benefit to having plugins managing themselves.

You could add an alias to `git -C path/to/zsh-autosuggestions pull`. Then that alias could even be added to your `.zshrc` if you want to update every time it's sourced.
