### ISSUE TITLE
Don't show multiline commands twice

### ISSUE THREAD

**Issue by benwaffle** [zsh-users/zsh-autosuggestions#225]
If you run 
```
ls \
-l
```

Then hit up, it shows 
![screenshot from 2017-03-15 20-49-34](https://cloud.githubusercontent.com/assets/1713819/23976857/ed2480c4-09c0-11e7-8b92-8dbd972ba863.png)

**Comment by desyncr** [comment]
I'm facing this issue as well. Hope it's a configuration problem.

**Comment by ericfreese** [comment]
Can you guys try this on the `develop` branch? A lot has changed and this may be fixed.

**Comment by desyncr** [comment]
In a quick look it seems it works properly on `develop`!
