### ISSUE TITLE
zsh-autosuggestions breaks `up-line-or-beginning-search` and `down-line-or-beginning-search`

### ISSUE THREAD

**Issue by OmeGak** [zsh-users/zsh-autosuggestions#227]
I use `up-line-or-beginning-search` and `down-line-or-beginning-search` to navigate history up from the position of the cursor. It used to work just fine but after I upgraded some time ago it stopped working. When I press `<UP>`, I can only go a couple of entries back in the history. When I press `<DOWN>` afterwards, I only get a beep.

I found this configuration, in combination with `match_prev_cmd` strategy, very powerful, as it gave me a way to preview the most recent history result from where I had typed, press `<UP>` and then keep going back in history. If I changed my mind, pressing `<DOWN>` would leave me exactly where I was at the beginning, with the suggestion still there.

I have tested in the `develop` branch and the issue remains.

**Comment by kylealwyn** [comment]
same issue.

**Comment by Xazzzi** [comment]
Same here on `develop`. Any fix available?

**Comment by OmeGak** [comment]
I just updated and it seems to be working fine again.

**Comment by Xazzzi** [comment]
Confirmed, works like a charm! =)

**Comment by cig0** [comment]
Hi all,

Can anybody confirm if shell history is broken again?

**Zsh**
```
~ % zsh --version
zsh --version
zsh 5.4.2 (x86_64-apple-darwin17.0.0)
```
**zsh-autosuggestions** (just cloned), enabled via _oh-my-zsh_:
```
~ % head -n3 /Users/cig0/.oh-my-zsh/custom/plugins/zsh-autosuggestions/CHANGELOG.md
# Changelog

## v0.4.0
```
**~/.zshrc**
```
plugins=(
    ...
    zsh-autosuggestions
    ...
)

# Plugins configuration
...
ZSH_AUTOSUGGEST_USE_ASYNC="true"  ## zsh-autosuggest
```

Thanks!
