### ISSUE TITLE
Highlighting style not working in tmux.

### ISSUE THREAD

**Issue by mtbehisseste** [zsh-users/zsh-autosuggestions#229]
Everything is ok when using zsh. The highlighting style of autosuggestions(I changed it to fg=240) works. But when I use tmux, the color of the suggestions did not change to what I expected(fg=240). The color is exactly the origin command line color. Other functions like right arrow key to complete or command line suggestions work well. There's only problem about highlighting styles in tmux. Any suggestion?

**Comment by philippotto** [comment]
I'm experiencing the same issue. I've enabled `set -g default-terminal screen-256color` in `.tmux.conf`, but this doesn't help. When tmux is closed, everthing works fine.

**Comment by Cdok** [comment]
Also experiencing this issue 
### tmux suggestion color
![screen shot 2017-04-21 at 10 45 00 am](https://cloud.githubusercontent.com/assets/16109837/25289705/a1bc0cd4-267f-11e7-8a49-60b193e08e6d.png)

### outside of tmux session
![screen shot 2017-04-21 at 10 45 10 am](https://cloud.githubusercontent.com/assets/16109837/25289711/a4d69a9c-267f-11e7-93ee-0d1e2a0081b8.png)


Note that issue is also occurring on the `git` zsh plugin inside of tmux

**Comment by mojidong** [comment]
tmux default  TERM  is screen： 
```zsh
$ env | grep TERM
TERM=screen
```

You can solve it like this:
```zsh
echo  "export TERM=xterm-256color" >> ~/.zshrc
exec zsh
```

**Comment by pirj** [comment]
![screen shot 2017-05-13 at 02 15 33](https://cloud.githubusercontent.com/assets/6916/26019934/1b8c845e-3782-11e7-801b-1552a31e0ecc.png)
I do not experience this. Check [my dotfiles](https://github.com/pirj/dotfiles/) for the reference.

**Comment by mojidong** [comment]
If you use MacOS iTerm2, you may need to modify the terminal type.

MacOS iTerm2: 
```
Preferences -> Profile -> Terminal -> Report Terminal Type :  xterm-256color
```

**Comment by ericfreese** [comment]
Sounds like this is solved. Thanks everyone 👍

**Comment by ericfreese** [comment]
Just came across another relevant link. See the tmux FAQ: https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal

**Comment by ZhouShengsheng** [comment]
Setting the default term to `xterm-256color` in your `.tmux.conf` does the trick:
```
# Set default term to xterm
set -g default-terminal xterm-256color
```

**Comment by crysis-ps** [comment]
> ```shell
> cho  "export TERM=xterm-256color" >> ~/.zshrc
> exec zsh
> ```

Thanks.
I made the <if> block in .zshrc to make this only for tmux:
`if [ ! "$TMUX" = "" ]; then
	export TERM=xterm-256color
fi`

**Comment by afirth** [comment]
> Would this workaround perhaps break other things?

yes, neovim for example

**Comment by afirth** [comment]
my workaround (gnome terminal) is

term prefs -> profiles -> show bold text in bright colors

and

`.zshrc`
```
zle_highlight=(default:bold)
```
no doubt you can do the first part in gconf if you like

this causes text in the terminal to be bold (and bright) and suggestions to be "normal"

**Comment by igloo1505** [comment]
> If you use MacOS iTerm2, you may need to modify the terminal type.
> 
> MacOS iTerm2:
> 
> ```
> Preferences -> Profile -> Terminal -> Report Terminal Type :  xterm-256color
> ```

I know this is old, but in 2023 this still worked for me!

**Comment by DeepaPrasanna** [comment]
> if [ ! "$TMUX" = "" ]; then export TERM=xterm-256color; fi

I have added this in .zshrc . this seems to not work for me. I have ubuntu 22.04
