### ISSUE TITLE
Suggestions can show multiple lines.

### ISSUE THREAD

**Issue by wilon** [zsh-users/zsh-autosuggestions#232]
Hi, I want to show  multiple lines just like a editor. So modify `zsh-autosuggestions.zsh` like this: 

```diff
 _zsh_autosuggest_strategy_default() {
-    fc -lnrm "$1*" 1 2>/dev/null | head -n 1
+    fc -lnrm "$1*" 1 2>/dev/null | head -n 6
 }
```

![http://wx4.sinaimg.cn/mw690/6c90904bly1feqmwru436g209w05gn49.gif](http://wx4.sinaimg.cn/mw690/6c90904bly1feqmwru436g209w05gn49.gif)

But there's some bugs on keyboard ➡️

Coud it support this?

**Comment by ericfreese** [comment]
> Coud it support this?

I don't think it will be supporting multiple suggestions any time soon. The goal of this project is to emulate in zsh the Fish autosuggestions feature, which I don't think has support for multiple suggestions.
