### ISSUE TITLE
extendedglob causes artifacting

### ISSUE THREAD

**Issue by protist** [zsh-users/zsh-autosuggestions#236]
In `~/.zshrc`:
```
setopt extendedglob
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
```
Create some history on the command line.
```
$ grep 'foo' bar
```
Now type the following.
```
$ grep '
```
So far, zsh-autosuggestions has been revealing the previous history item, as expected. Now type in a caret instead.
```
$ grep '^
```
The autosuggestion disappears, as expected. However, if I press `a`, the full suggestion reappears.
```
$ grep '^agrep 'foo' bar
```
Here the cursor is on the on the `g` of the second `grep`. If I type more, the autosuggestion just keeps moving across.
```
$ grep '^aaaaaagrep 'foo' bar
```
Again the cursor is on the `g`. Starting again, if I type `f` instead of `a`, then there are no autosuggestions.
```
$ grep '^f
```
although further keypresses will bring it up again. Also, I can replicate this from a fresh prompt with just a caret and another letter (with the exception of `g` in this example).
```
$ ^agrep 'foo' bar
```

I tested with the latest zsh-autosuggestions commit (fedc22e9bbd046867860e772d7d6787f5dae9d4c) Removing `setopt extendedglob` from `~/.zshrc` fixes this problem.

Also, this appears to interfere with autosuggesting legitimate history entries with carets in them.

**Comment by ericfreese** [comment]
I believe this is fixed on the `develop` branch. Take a look there and let me know if you're still seeing issues.

**Comment by protist** [comment]
I just tested, and this has been fixed in `develop`. Thank you.
