### ISSUE TITLE
zsh at 100% CPU

### ISSUE THREAD

**Issue by lucas-clemente** [zsh-users/zsh-autosuggestions#24]
After setting up autosuggestions every zsh shell process is taking up 100% CPU after using suggestions once. From my zshrc:

```
source ~/.zsh-autosuggestions/autosuggestions.zsh
export AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=248'
bindkey '^F' forward-word
zle-line-init() {
  zle autosuggest-start
}
zle -N zle-line-init
```

zsh:

```
$ zsh --version
zsh 5.0.5 (x86_64-apple-darwin13.0.2)
```

Let me know if I can help.

**Comment by Arctomachine** [comment]
Found this topic by searching online, other similar topics link to here.

I have zsh 5.8.1 (x86_64-ubuntu-linux-gnu), with omz and powerlevel10k theme, running on ubuntu (wsl).
I notice that one zsh process takes 100% usage (one full core).
Process command in htop is `/usr/bin/zsh -l -i -c "/tmp/something/something" "print-env" "--print0" "--header" "something"`.
I checked file system with `ls -a` and there is no such folders in /tmp that it has in command.

Is it something relevant or is it different issue?
This topic seems to be ancient, but still version 5 is discussed here, which is what I have installed too.
