### ISSUE TITLE
Ignored widgets make suggestion lose highlight color

### ISSUE THREAD

**Issue by OmeGak** [zsh-users/zsh-autosuggestions#240]
Executing any widget registered in `ZSH_AUTOSUGGEST_IGNORE_WIDGETS` makes the suggestion lose the highlight color. This is a follow up from #184.

Quick way to reproduce the issue:

```shell
ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(backward-char)
```

Just press arrow left once there is a suggestion and it will turn back to the normal color.

**Comment by ericfreese** [comment]
@OmeGak Trying to reproduce this today and I'm not able to. Please re-open if you can still reproduce this on latest `develop` branch.

I'm using
```
% zsh -f
%% source zsh-autosuggestions.zsh; ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(backward-char)
%% source <left arrow>
```

**Comment by OmeGak** [comment]
Still happening for me. I'll find the time to provide a minimum viable example that reproduces the issue.
