### ISSUE TITLE
ZSH_AUTOSUGGEST_USE_ASYNC breaks shell history

### ISSUE THREAD

**Issue by austinarbor** [zsh-users/zsh-autosuggestions#241]
When adding the option `ZSH_AUTOSUGGEST_USE_ASYNC=true` to my `~/.zshrc` file, this breaks command history.  Pressing up button on keyboard will retrieve at most the 2 most recent commands.  When I remove this option from my `~/.zshrc` file, command history functionality returns to normal

**Comment by ericfreese** [comment]
Oh dang. I bet this is related to #227. One of my last commits before `v0.4.0` was to disable async by default so I bet that's what "fixed" it.

**Comment by cig0** [comment]
Hi all,

Can anybody confirm if shell history is broken again?

**Zsh**
```
~ % zsh --version
zsh --version
zsh 5.4.2 (x86_64-apple-darwin17.0.0)
```
**zsh-autosuggestions** (just cloned), enabled via _oh-my-zsh_:
```
~ % head -n3 /Users/cig0/.oh-my-zsh/custom/plugins/zsh-autosuggestions/CHANGELOG.md
# Changelog

## v0.4.0
```
**~/.zshrc**
```
plugins=(
    ...
    zsh-autosuggestions
    ...
)

# Plugins configuration
...
ZSH_AUTOSUGGEST_USE_ASYNC="true"  ## zsh-autosuggest
```

Thanks!

**Comment by partounian** [comment]
Yes it is still broken.

Also, @cig0 you need to set ZSH_AUTOSUGGEST_USE_ASYNC before the plugins array.

**Comment by partounian** [comment]
Also we should probably check if `ZSH_AUTOSUGGEST_USE_ASYNC` is set to `1` or `true`, rather than checking if defined.

**Comment by aarbor989** [comment]
@partounian does it need to be before the plugins array?  I don't see that mentioned in the docs

**Comment by partounian** [comment]
@aarbor989 I was wrong, it executes before each prompt (precmd).


https://github.com/zsh-users/zsh-autosuggestions/blob/master/zsh-autosuggestions.zsh#L699

**Comment by BirkhoffLee** [comment]
This is still broken, b4 it gets fixed i suggest writing this issue to README.md to notice ppl

**Comment by ericfreese** [comment]
I've got a hypothesis based on #227 that this is only an issue when using `up-line-or-beginning-search` and `down-line-or-beginning-search`. Is anyone here seeing this issue while using other widgets?

You can check what your up and down keys are bound to by running:

```
$ bindkey $terminfo[kcuu1]
```

and

```
bindkey $terminfo[kcud1]
```

**Comment by ericfreese** [comment]
And for those who may want to dig in, source of that widget is here: https://github.com/zsh-users/zsh/blob/master/Functions/Zle/up-line-or-beginning-search

**Comment by partounian** [comment]
@ericfreese I have confirmed the issue and I am using up-line-or-beginning-search and down-line-or-beginning-search.

**Comment by ericfreese** [comment]
If we confirm that it is only an issue with `*-line-or-beginning-search`, the first step toward fixing it would be to write a failing test. A test for this would live in [spec/integrations](https://github.com/zsh-users/zsh-autosuggestions/tree/master/spec/integrations). Could look at some of the other specs in that directory for inspiration.

**Comment by partounian** [comment]
Not sure if it help but I use oh-my-zsh and have not added the `*-line-or-beginning-search` it is in their file here https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh

**Comment by ericfreese** [comment]
Ok should be fixed on `develop`. In the mean time you can also add `up-line-or-beginning-search` and `down-line-or-beginning-search` to `ZSH_AUTOSUGGEST_CLEAR_WIDGETS`.

**Comment by austinarbor** [comment]
Appears to be working fine for me in `develop`, thanks!

**Comment by partounian** [comment]
Same
