### ISSUE TITLE
Cannot work in Windows with Babun

### ISSUE THREAD

**Issue by Kahnnn** [zsh-users/zsh-autosuggestions#242]
There is no auto suggestions show in the shell

**Comment by ericfreese** [comment]
Not sure how to help you as I don't run windows or babun. Anyone else have any ideas?

**Comment by z0rc** [comment]
Probably another case of terminal colorscheme issue, see #262 and #272.

**Comment by ericfreese** [comment]
Thanks @z0rc. Going to close this. Can re-open if someone runs into it again and @z0rc’s comment doesn’t help.
