### ISSUE TITLE
Incomplete suggestions - shows only first character

### ISSUE THREAD

**Issue by StefanoFioravanzo** [zsh-users/zsh-autosuggestions#243]
zsh-suggestions shows just the first character of the suggestion and not the entire string. For example if a have a subfolder `document` and I type `cd d` it shows just the `o` and not `ocument`.

I tried to change theme but nothing changes.

I am on OS X using ITerm2.

**Comment by ericfreese** [comment]
Well this is weird. Can you reproduce with only `zsh-autosuggestions` sourced?

```shell
% zsh -f
% source zsh-autosuggestions.zsh
```

**Comment by StefanoFioravanzo** [comment]
Yes it as the same behavior, if not worse actually. If I type `c` it proposes `d` (for `cd`) for example. But then, if I have the folder `Documents` and I type `D` it does not propose anything!

**Comment by ericfreese** [comment]
You are aware it only suggests things from your history right? So it won't suggest `cd Documents` unless you've previously executed that command.

**Comment by StefanoFioravanzo** [comment]
Yes of course. But still  it shows just the next character in the suggestion and not the whole string.

**Comment by StefanoFioravanzo** [comment]
@ericfreese ok found the issue. Apparently the plugin was using a color identical to the background for the suggestion. My theme's fault!

**Comment by dakaugu** [comment]
Same happens with Solarized Dark theme on iTerm but i would still like to keep using the theme. Any way to change suggestions hint color?

**Comment by engintekin** [comment]
@dakaugu *Solarized Dark theme* is fixing this issue https://gist.github.com/kevin-smets/8568070#iterm2

**Comment by ssword** [comment]
@engintekin , thanks for the reference. 
To save you from the long reading. The following command can solve the problem:
`echo ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=\'fg=60\' >> $ZSH_CUSTOM/zsh-autosuggestions_custom.zsh`

**Comment by jcrawford** [comment]
Thanks I was having this same issue on my side love that it works now :)

**Comment by fabianmossberg** [comment]
> @ericfreese ok found the issue. Apparently the plugin was using a color identical to the background for the suggestion. My theme's fault!

Damn, I've been trying to figure this out, had the same problem 😂

**Comment by tasuki** [comment]
For me it was setting `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` _before_ loading the plugin. Apparently it needs to be set after loading the plugin otherwise it gets overridden.

**Comment by rayryeng** [comment]
> @engintekin , thanks for the reference. To save you from the long reading. The following command can solve the problem: `echo ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=\'fg=60\' >> $ZSH_CUSTOM/zsh-autosuggestions_custom.zsh`

This was a great workaround. Thanks! Worked for me.
