### ISSUE TITLE
Maintainer will be away May 28 through Aug 9

### ISSUE THREAD

**Issue by ericfreese** [zsh-users/zsh-autosuggestions#244]
Just a heads up for everyone here. I'm going to be away from my computer for a couple months this summer. If pull requests to `develop` are solid, I may merge them but otherwise won't be checking on this repo.

Cheers,
Eric

**Comment by aaronjensen** [comment]
Enjoy your break. If you get a chance before you head out to point me in the right direction on https://github.com/zsh-users/zsh-autosuggestions/issues/238 I'd much appreciate it and could take it from there. Thanks!
