### ISSUE TITLE
Autosuggestion is not invalidated when typing a * or ?

### ISSUE THREAD

**Issue by ivan** [zsh-users/zsh-autosuggestions#248]
I'm having this problem with 0.4.0, but not 0.3.3: when the typed command includes a `*` or `?`, the autosuggestion is not invalidated and starts crawling to the right: https://ludios.org/tmp/zsh-autosuggestions-async-issue.mp4

```
# zsh --version                                               
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

.zshrc settings: https://gist.github.com/ivan/79de5e87210e8cf21e305bb4c30c4360#file-zshrc-L200-L206

(Originally reported at https://github.com/zsh-users/zsh-autosuggestions/pull/180#issuecomment-275911411.)

**Comment by ericfreese** [comment]
Only occurs with `match_prev_cmd` strategy.

**Comment by ericfreese** [comment]
I believe this is fixed on `develop`. Please try it out @ivan
