### ISSUE TITLE
Breaks surround module

### ISSUE THREAD

**Issue by glacambre** [zsh-users/zsh-autosuggestions#254]
When using zsh 5.3.1, the following snippet of code:
```zsh
bindkey -v
autoload -U select-quoted select-bracketed surround
zle -N select-quoted
zle -N select-bracketed
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround

for m in visual viopp; do
    for c in {a,i}{\',\",\`}; do
        bindkey -M $m $c select-quoted
    done
    for c in {a,i}${(s..)^:-'()[]{}<>bB'}; do
        bindkey -M $m $c select-bracketed
    done
done
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround
```
Will let the user turn the following string: ```hello "world" !``` into this one: ```hello 'world' !``` by doing this: ```<ESC>cs"'```. However, sourcing zsh-autosuggestions will break this: instead of staying in vi normal mode, pressing ```cs``` will make zle go back into insert mode.

**Comment by glacambre** [comment]
In case someone encounters the same issue: there's a workaround, adding ```vi-change``` and ```vi-delete``` to ```ZSH_AUTOSUGGEST_IGNORE_WIDGETS``` makes the surround module work but breaks zsh-autosuggestions when using vi-change and vi-delete (suggestions aren't updated anymore).

**Comment by ericfreese** [comment]
From a little playing, I'm able to reproduce this, but it seems to only occur when the delay between pressing <kbd>c</kbd> and pressing <kbd>s</kbd> is more than about a second. If I press <kbd>s</kbd> immediately after <kbd>c</kbd>, it seems to work fine. Confirmed too that without z-asug loaded, the delay doesn't matter and the replacement always works so it seems the plugin is at fault.

**Comment by IngoHeimbach** [comment]
@glacambre Do you have a custom value for `KEYTIMEOUT`? I can use surround with autosuggestions if `KEYTIMEOUT` > 25.

**Comment by glacambre** [comment]
@IngoHeimbach Nice catch, my `KEYTIMEOUT` is very low, increasing it fixes the issue. Thanks !

Looks like the issue stems from me not knowing how `KEYTIMEOUT` and zsh-autosuggestions interact rather than a zsh-autosuggestions bug, hence feel free to close this issue if you want to.

**Comment by jdhao** [comment]
I have also met with this issue when I am using [zsh-vim-mode](https://github.com/softmoth/zsh-vim-mode).  It turns out that I have set up `KEYTIMEOUT` to 1 following [the guideline on internet](https://www.johnhawthorn.com/2012/09/vi-escape-delays/). 

After I use `export KEYTIMEOUT=30` in my `.zshrc`,  I can use the surround text object in vi normal mode.
