### ISSUE TITLE
How to let history ignore the wrong command

### ISSUE THREAD

**Issue by niubaoshu** [zsh-users/zsh-autosuggestions#259]
➜  src sssssssssssssssssssssss

zsh: command not found: sssssssssssssssssssssss

➜  src history|tail -n 1

 1633  sssssssssssssssssssssss
not history ssssssssssssssss

**Comment by mattsoutherden** [comment]
Here is one possible way to do this:

https://superuser.com/a/902508

**Comment by ericfreese** [comment]
Going to go ahead and close this since it's not specific to this plugin. If you're still looking for answers, consider emailing the `zsh-users` email list: http://zsh.sourceforge.net/Arc/mlist.html

**Comment by ghunti** [comment]
Sorry for commenting in such an old issue.
I don't know if in 2017 the behavior is the same as today, but currently, applying what @mattsoutherden proposed `zshaddhistory() { whence ${${(z)1}[1]} >| /dev/null || return 1 }` works very well, if `zsh-autosuggestions` is disabled.
When the `zsh-autosuggestions` plugin is enabled, that sollution doesn't work. Is there anything that can be done to prevent `zsh-autosuggestions` to display auto-complete suggestions for wrong commands like `gut status` ?
