### ISSUE TITLE
Upon installation only displaying next character

### ISSUE THREAD

**Issue by willgdjones** [zsh-users/zsh-autosuggestions#262]
On a fresh install, it only seems to complete the next character:

<img width="110" alt="screen shot 2017-07-28 at 14 43 28" src="https://user-images.githubusercontent.com/1719848/28717699-28ae67b2-73a3-11e7-84a4-833c679f03eb.png">

The suggestion appears in white. I had previously typed `echo something`

**Comment by quanru** [comment]
+1

**Comment by mattsoutherden** [comment]
Possibly your fg8 colour (the default autosuggest colour) is indistinguishable from fg0 (terminal bg). You could try printing all your terminal colours to see if this may be the case

e.g.

```for code in {000..255}; do print -P -- "$code: %F{$code}Test%f"; done```

If that is the case, you can set the suggestion colour by changing `zstyle ':prezto:module:autosuggestions:color'` in `runcoms/zpreztorc`

**Comment by ericfreese** [comment]
I think @mattsoutherden nailed it. Only thing to add is if you're not using prezto, set `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` variable instead of the prezto`zstyle`.

**Comment by willgdjones** [comment]
Yep this fixed it! Thanks @mattsoutherden
