### ISSUE TITLE
Make the project `setopt WARN_NESTED_VAR` friendly

### ISSUE THREAD

**Issue by kutsan** [zsh-users/zsh-autosuggestions#271]
Using `setopt WARN_NESTED_VAR` option gives a bunch of warnings. Nested variables could be easily defined with `typeset -g`.

**Comment by ericfreese** [comment]
Just pushed up branch `fixes/warn_nested_var_opt` (PR #275) that I believe fixes this.

Does that fix the issue for you?

**Comment by kutsan** [comment]
Apparently, errors are still persist.

![](https://i.imgur.com/DxHkCkz.png)

**Comment by ericfreese** [comment]
That's strange. Can you confirm the sha you're using is 8064a6f?

**Comment by kutsan** [comment]
Yes, I can confirm. I am also getting this error like 500 times for a prompt.

```
_zsh_autosuggest_get_bind_count:2: scalar parameter bind_count set in enclosing scope in function _zsh_autosuggest_get_bind_count
```

**Comment by kutsan** [comment]
@ericfreese Just in case you don't know. You should also use `typeset -g` for nested variable assignments. It won't it global if it's already local and defined.

**Comment by ericfreese** [comment]
@kutsan Ok, pushed up another commit 256293c that I think should be better. I'm basically adding `typeset -g` to everywhere that I am assigning to variables that exist from an earlier scope.

**Comment by kutsan** [comment]
Thank you! It's all gone. Besides WARN_CREATE_GLOBAL option, I think using `typeset -g` gives better readability for the code. Since, reader can understand that, variables are from outer scope.

You can close the issue as you wish. Thanks again.

**Comment by ericfreese** [comment]
Merged into `develop`. Will release with 0.4.1
