### ISSUE TITLE
Automatically generated code documentation

### ISSUE THREAD

**Issue by psprint** [zsh-users/zsh-autosuggestions#273]
Hello
I'm writing [Zshelldoc](https://github.com/zdharma/zshelldoc). Using it to generate documentation for [Zplugin](https://github.com/zdharma/zplugin/tree/master/zsdoc) and seeing how it helps to:
 - understand the code (even to myself, but hoping to get contributors)
 - motivate to document the code

I've also generated documentation for your project, it's an example shipped with Zshelldoc:

https://github.com/zdharma/zshelldoc/tree/master/examples

PDFs are generated using Asciidoctor, I now look forward for doing this with Travis-CI.

So, maybe you will be interested in shipping "API" documentation with your project? To gain contributors and have fun :)

**Comment by psprint** [comment]
I'm puzzled about no feedback. Isn't Zshelldoc good enough, or you don't want to draw in new contributors for some reason?

Running Zshelldoc is really fun, using it now in `zplugin-crasis` project, and also in `zplugin` project. What's fun in this is e.g. using Travis CI to generate PDFs from Asciidoc with `asciidoctor`, compare if there are changes, and commit and push to `gh-pages` branch. Result for `zplugin` is here: http://zdharma.org/zplugin/

**Comment by ericfreese** [comment]
Sorry for the slow response- I've been a bit busy lately with other projects. I think this could be interesting though, and I would happily merge a PR.

**Comment by psprint** [comment]
I'll be happy to set up Zshelldoc for `zsh-autosuggestions`, I'm fresh on this so it will be easy. It's a good decision, the project matches very well Zshelldoc features.

But doing some iterations on function comments is needed and probably only you can do that. This is quite fun, I was doing this for Zplugin, devoting some 5 minutes few times a day.

**Comment by ericfreese** [comment]
Thanks 👍  I'll gladly add some documentation comments next time I have some cycles for this.

**Comment by psprint** [comment]
Looking forward for merge, hope you'll find time because the documentation would make Zsh plugins more software and less top-down scripts, I think. Others could follow such popular plugin as autosuggestions, this would be very cool :)

**Comment by ericfreese** [comment]
I apologize for never digging into this. The PR added a bit more complexity than I wanted to have, and since I haven't personally felt the problem to begin with, it felt like adding extra complexity for little gain. I'm going to go ahead and close this ticket, but I'll keep zsd in the back of my mind should I feel the need for it in the future. Thanks.
