### ISSUE TITLE
zsh autosuggestions is not working after closing iterm2

### ISSUE THREAD

**Issue by mehedi-sharif** [zsh-users/zsh-autosuggestions#279]
I have install this plugin in iterm2 and it works fine after adding 
`source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh`
this command in my mac. But after closing the iterm2 and reopen it , the auto suggestion is not working. 
Do I need to add any command to work with in iterm startup. 
Thanks

**Comment by ericfreese** [comment]
You'll need to source the file every time you start a new shell session. This can be easily done by adding it to the `.zshrc` file in your home directory. Check out step 2 of the manual installation section on the readme: https://github.com/zsh-users/zsh-autosuggestions#manual

**Comment by mehedi-sharif** [comment]
I did the manual process . but still no luck 👎

**Comment by ericfreese** [comment]
Are other things from your `.zshrc` being applied?

**Comment by mehedi-sharif** [comment]
I am sorry . Its an issue from my end . There was a line in that file name plugins = (git) . And I repeated with new plugins=(zsh-autosuggestions) line. If you guys mention this in that tutorial that will be helpful for the novice users.
Thanks

**Comment by ericfreese** [comment]
Ah ok glad you got it sorted 👍

**Comment by matan-gk** [comment]
Hi. Having the same issue and could not find the solution.
Installed using homebrew, added the source line to .zshrc as mentioned in the install.md.
The other "source" line I have there is for syntax highlighting, which works fine.
running the source line manually in the terminal session works fine too, but only for that session obviously.

**Comment by trinanda** [comment]
> I am sorry . Its an issue from my end . There was a line in that file name plugins = (git) . And I repeated with new plugins=(zsh-autosuggestions) line. If you guys mention this in that tutorial that will be helpful for the novice users.
> Thanks

After trying few ways to resolve this, I also solved this problem with your wat.
Thanks

**Comment by Santosh4Tech** [comment]
> I am sorry . Its an issue from my end . There was a line in that file name plugins = (git) . And I repeated with new plugins=(zsh-autosuggestions) line. If you guys mention this in that tutorial that will be helpful for the novice users.
> Thanks

I am facing the same issue. Could you please let me know which file you did a modification?
