### ISSUE TITLE
The shell session will crash after source ~/.zshrc on Mac OS

### ISSUE THREAD

**Issue by luguodexxx** [zsh-users/zsh-autosuggestions#280]
In a opened session, if i sourced ~/.zshrc, and then type any command line, the session would crash. Mac OS 10.11.6, zsh 5.0.8

**Comment by ericfreese** [comment]
Can you get some more information around this? It would be helpful for you to remove bits and pieces of your .zshrc file to narrow down exactly what is causing the session to crash.
