### ISSUE TITLE
Show suggestion in error folder Mac Osx

### ISSUE THREAD

**Issue by Remeic** [zsh-users/zsh-autosuggestions#284]
Report this issue, if i move to Desktop/myname all works, i come back to ~ and move to Documents/mywork/project1, when i go to Desktop plugin suggest me Documents/mywork but folder doesn't exist in Desktop, so suggestion is wrong

<img width="591" alt="schermata 2017-10-22 alle 12 55 56" src="https://user-images.githubusercontent.com/7298302/31861170-8dc65894-b728-11e7-8116-51e6c79aa2e3.png">
<img width="584" alt="schermata 2017-10-22 alle 12 56 53" src="https://user-images.githubusercontent.com/7298302/31861171-8deffdfc-b728-11e7-9572-c63d2c3b5ffd.png">

**Comment by ericfreese** [comment]
Yep, the suggestions are currently pretty dumb. They're only based on history, and have no notion of where you are or what exists there. See #196 and #111.
