### ISSUE TITLE
Autosuggest only the commands available to the terminal

### ISSUE THREAD

**Issue by GloverDonovan** [zsh-users/zsh-autosuggestions#285]
Is there any way to autosuggest only the commands available to the terminal (e.g. echo, cp, rm, etc.)? Most of the time I don't need my entire history, but when I do, the arrow keys suffice for me.

Consider: https://fishshell.com/docs/current/tutorial.html#tut_autosuggestions

Ideally you'd be able to use any combination of these features (the one I'm interested in is commands without the entire history).

As a workaround, would it be possible to tell zsh-autosuggestions to use a blank or nonexistent history file? Ignore everything after the first space in autosuggestions? A history file that lists all the commands to autosuggest and nothing more?

Thanks

**Comment by ericfreese** [comment]
You can write your own suggestion strategy. You just have to define a function with the right name and then change the strategy variable in your config. Check out https://github.com/zsh-users/zsh-autosuggestions/tree/master/src/strategies for some inspiration.

**Comment by GloverDonovan** [comment]
Sorry it took so long for me to reply. I changed `default.zsh` a bit and got it to show only the command (i.e. everything before the first space), but now it shows the same command every time I press space. What am I doing wrong?

```
_zsh_autosuggest_strategy_command() {
    local prefix="$1"

    typeset -g suggestion="${"${history[(r)${(b)prefix}*]}"% *}"
}

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

export ZSH_AUTOSUGGEST_STRATEGY="command"
```
