### ISSUE TITLE
Multiple bugs with iTerm2 3.1.3+ on Mac High Sierra 10.13

### ISSUE THREAD

**Issue by aarbor989** [zsh-users/zsh-autosuggestions#286]
I created a [screen recording](https://drive.google.com/open?id=0ByD5rdsGCdAqbkZNWHUxODBsZ0E) to capture some of the bugs I am seeing when running on High Sierra 10.13.  To summarize (in order of occurrence in the video)

1. When pasting text, the left prompt disappears
2. Typing a command and backspacing causes extra letter(s) to be added in , and sometimes prevents users from backspacing to beginning of the line.  In the video, when I start backspacing `curl`, it changes to `ccurl`
3. Sometimes cannot backspace to beginning of line (there is a space that somehow gets added and cannot be removed)
4. Commands with autosuggestions sometimes have extra characters randomly added into the command.  In the video. `curl -X GET` is changed to `curl -X GGET`

These bugs are only occurring in iTerm2.  I tested with both 3.1.3 and 3.1.4 and the issues appeared in both.  In the standard Mac Terminal.app, the bugs are not present.  Additionally, if I disable autosuggestions, the issues disappear in iTerm2.

**Comment by davidosomething** [comment]
you should run
`echo $TERM`
`echo $SHELL`
`$SHELL --version`
`infocmp`

and paste results here for more useful debugging info

**Comment by aarbor989** [comment]
@davidosomething 
```
🔥  ~ ❯ echo $TERM                                                                      ⏎  00:32:27
xterm-256color
🔥  ~ ❯ echo $SHELL                                                                        00:32:32
/bin/zsh
🔥  ~ ❯ $SHELL --version                                                                   00:32:41
zsh 5.3 (x86_64-apple-darwin17.0)
🔥  ~ ❯ infocmp                                                                            00:32:48
#	Reconstructed via infocmp from file: /usr/share/terminfo/78/xterm-256color
xterm-256color|xterm with 256 colors,
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	colors#256, cols#80, it#8, lines#24, pairs#32767,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=^J, indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
	rmir=\E[4l, rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smm=\E[?1034h, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,```

**Comment by davidosomething** [comment]
shot in the dark, but try using a newer zsh?
`brew install zsh` for `zsh 5.4.2` (`sudoedit /etc/shells` and add  `/usr/local/bin/zsh` if you want to `chsh` to it)

**Comment by aarbor989** [comment]
Ah - I had the latest version of zsh _installed_ but looks like it never took hold because I didn't edit `/etc/shells` and add the `/usr/local/bin/zsh` path to it.  Unfortunately that didn't fix the issue - but glad I'm on the latest version now! (thanks)

**Comment by z0rc** [comment]
This looks like compatibility issue with your zsh theme, configuration and/or plugins. Can you reproduce issues with after sourcing zsh-asug with clean env? Like:
```
zsh -f
source path/to/zsh-autosuggestions.zsh
```

**Comment by aarbor989** [comment]
It does work fine using the above, and after testing with the default "robbyrussell" theme in oh-my-zsh, the issue also subsides (although it is interesting it worked just fine before High Sierra and it still works fine in Terminal.app).  In any case, I'll try and debug the theme from my side.  Thanks everyone

**Comment by CoreyKaylor** [comment]
I seem to also be having odd behavior with iTerm2 3.1.5 on High Sierra. 
For me the odd behavior is that I only ever see 1 character suggestion visually. However, accepting by either -> or CTRL+F will expand out to what I would normally see in the suggested text. Changing themes in oh-my-zsh doesn't work for me.

The default Mac Terminal works as expected. 

I also tested this out and the behavior stays the same.
```
zsh -f
source /path/to/zsh-autosuggestions.zsh
```

```
 corey@coreymacbook  ~  echo $TERM
xterm-256color
 corey@coreymacbook  ~  echo $SHELL
/usr/local/bin/zsh
 corey@coreymacbook  ~  $SHELL --version
zsh 5.4.2 (x86_64-apple-darwin17.0.0)
 corey@coreymacbook  ~  infocmp
#	Reconstructed via infocmp from file: /usr/share/terminfo/78/xterm-256color
xterm-256color|xterm with 256 colors,
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	colors#256, cols#80, it#8, lines#24, pairs#32767,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=^J, indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
	rmir=\E[4l, rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smm=\E[?1034h, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by z0rc** [comment]
@CoreyKaylor #288, #272, #262.

**Comment by CoreyKaylor** [comment]
Thanks @z0rc that fixed it.

**Comment by egeste** [comment]
@aarbor989 I noticed that in your theme, you use emojis. I was also using an emoji in my theme, and as soon as I replaced it with a non-emoji utf8 character, everything went back to normal.

I think it's safe to assume at this point that there's a bug in either zsh or oh-my-zsh that's causing utf8 chars in the emoji space to break theming.

**Comment by shilov** [comment]
@egeste I haven't tried stripping out oh-my-zsh, that's worth a shot. Based on a discussion I saw in the official zsh mailing list, I figured it's internal to how zsh handles rendering.

I've reproduced op's original problem and other rendering oddities with a couple of themes, both on Linux and Mac, with zsh v5.3 and 5.4. The latest zsh release (5.4.2) seems to be the most problematic for me: rendering content on top of previous lines when tabbing for autocomplete. For some reason, it only happens when using a two-line prompt. 

fwiw earlier versions of zsh v5 were not prone to these issues.

**Comment by aarbor989** [comment]
@egeste @shilov interesting find with the emojis. Were you both experiencing issues in iTerm and Terminal, or just iTerm?

**Comment by ericfreese** [comment]
Going to close since it seems these issues are unrelated to zsh-autosuggestions.

**Comment by shilov** [comment]
@ericfreese iterm2 + Terminal both have this issue. I removed zsh-autosuggestions and the problem is still there, it's safe to say the culprit is something else.

**Comment by drsharp** [comment]
Just to add to this, I had the exact same problem as the OP (@aarbor989). After updating oh-my-zsh and playing around with themes I realized that my custom theme was to blame. I had set a custom prompt that included a large UTF8 icon for the prompt character, and when I did `ctrl-r` to do a backwards history search, it would move the actual cursor over to the right one space. Then, if I found a command from history and went to move around the line to edit it, I saw the same behavior as in @aarbor989's screen recording.

I change the character to a smaller character and it doesn't seem to be happening anymore.

I should note that the original custom theme I had was from at least two older versions of OSX and I never had any problem. So it was a combination of High Sierra and my custom theme. Go figure.

**Comment by WheresWardy** [comment]
Came here from Google and wanted to add that I had the same issue with macOS High Sierra 10.13.3, iTerm2 and Bash, as well as Terminal.app, and I had a UTF-8 character in my Prompt. So does seem to be an issue specifically related to High Sierra and UTF-8 characters in prompts.

**Comment by lbergelson** [comment]
I'm seeing the same problem with Iterm2 and zsh with a prompt that has a UTF8 character.  It started happening after upgrading to High Sierra from El Capitan.

**Comment by amitosdev** [comment]
Had the same issue. Solved by adding
```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
into my `~/.zshrc` as suggested [here](https://github.com/robbyrussell/oh-my-zsh/issues/1282).

**Comment by johannesluedke** [comment]
I am having the same issue, MacOS X + zsh with emoji in custom theme; https://github.com/zsh-users/zsh-autosuggestions/issues/286#issuecomment-450576664 did not solve it :(

**Comment by H-L** [comment]
Still having the bug from the screen recording on top of this issue, even with the fix proposals.
It mostly appears when using `tab` into a suggestion. 

**e.g.** `git chec` then tab
 => `ggit checkout` but the command will work fine.

**My config:**
* **OS** macOS Mojave 10.14.3
* **Iterm** Build 3.2.8
* **ZSH** 5.7.1 (x86_64-apple-darwin18.2.0)
* Using Oh My ZSH & wild-cherry theme

**Plugins installed**
  git
  gitignore
  nvm
  rbenv
  colored-man-pages
  colorize
  github
  virtualenv
  pip
  python
  osx
  zsh-autosuggestions
  zsh-syntax-highlighting

**Comment by Aurorxa** [comment]
https://aexiar.github.io/linux/notes/01_linux_basic/08_xdx/#_1-2-5-%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98

```shell
# 修改主题
sed -i 's/⚡/%{%G⚡%}/' ~/.oh-my-zsh/themes/agnoster.zsh-theme
```
```
# 重新加载配置文件
source ~/.zshrc
```
