### ISSUE TITLE
Can not show all the suggestions but only the next letter

### ISSUE THREAD

**Issue by yilinfang** [zsh-users/zsh-autosuggestions#288]
In Sierra 10.12.6 iterm2 with the default conf, the suggestion only show the next letter but not the full suggestion

**Comment by z0rc** [comment]
Probably color scheme related. Dupe of #262 and #272.

**Comment by yilinfang** [comment]
@z0rc I have tried  robbyrussell and agnoster, both have the problem.

**Comment by z0rc** [comment]
It's matter of iterm2 colors, not the zsh theme. Also check proposed solutions in linked tickets, please.

**Comment by yilinfang** [comment]
@z0rc Thanks a lot, I have fixed the problem with the solution of #262, so sorry to bother you.
