### ISSUE TITLE
Is it possible to show more than suggestion from history?

### ISSUE THREAD

**Issue by YASoftwareDev** [zsh-users/zsh-autosuggestions#289]
Like in title, sometimes I want to see more than one previous history entry to choose from.
Any suggestions what I need to change to achieve it?

**Comment by ivan** [comment]
See https://github.com/zsh-users/zsh-autosuggestions/issues/232#issuecomment-294860042

Maybe you want ctrl-r -> history-incremental-search-backward?  That is what I use when the autosuggestion isn't what I need.

**Comment by YASoftwareDev** [comment]
I have installed .oh-my-zsh, so "ctrl-r"/"ctrl-s" functionality known from bash is working for me. But it shows only one suggestions.

Working #232 case is exactly what I'm looking for!
But partial solution proposed by OP in #232 is not working anymore. Code was refactored soon after.

Could you provide me some clue what should I change to mimic OP (partial) solution?

**Comment by ivan** [comment]
Alright, just ignore this if you already know: press ctrl-r again after it's showing a match, and it will keep going backwards to another match until you've reached the end.

**Comment by ericfreese** [comment]
Sorry @YASoftwareDev, but as stated in #232, the goal of this project is to emulate in zsh the Fish autosuggestions feature, which I don't think has support for multiple suggestions.
