### ISSUE TITLE
suggestion breaks on fast vi movement

### ISSUE THREAD

**Issue by IngoHeimbach** [zsh-users/zsh-autosuggestions#290]
If the user switches to `vicmd` and invokes a vi movement quickly enough (within the `KEYTIMEOUT` interval) the suggestion preview will disappear. One possible solution is to decrease `KEYTIMEOUT` but that introdoces problems with key bindings that consist of multiple keys (for example `cc`, `iw` or key bindings of the surrounding module). Is this a known problem?

**Comment by IngoHeimbach** [comment]
The problem is caused by an [optimization in widgets.zsh](https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/widgets.zsh#L56-L59). The optimization avoids getting multiple suggestions if still keys are queued for processing. However, there is no guarantee that the last key will invoke the suggestion rendering process; in my case the last key is a vi movement and no suggestion is rendered at all. In my opinion, this optimization should be removed. What do you think?

**Comment by ericfreese** [comment]
That optimization was added as a fix for #219 (see PR #223). Ideally, we could find a way to solve this problem, while still supporting the fix for #219. If there's no way to satisfy both, I think we should add an option to disable this instead of removing it for everyone.

**Comment by ericfreese** [comment]
This was just fixed on `develop` with commit https://github.com/zsh-users/zsh-autosuggestions/commit/42f5a06f7f29007d91e37f85e1dc5a80f1b7c059

Will go out with the next release.
