### ISSUE TITLE
"firewall-cmd " command can't autocomplete options for centos 7

### ISSUE THREAD

**Issue by yaro97** [zsh-users/zsh-autosuggestions#292]
the "Tab" always works for autocompletion
But for CentOS 7, "firewall-cmd " command can't autocomplete options.
when switch to  Bash with typing "bash", the completion do well!!
SOS,! please!!!

**Comment by ericfreese** [comment]
It sounds like you're talking about zsh tab completion. That's not a feature of this plugin. I'm going to go ahead and close.
