### ISSUE TITLE
Full suggested command always shown after pressing enter

### ISSUE THREAD

**Issue by N4zroth** [zsh-users/zsh-autosuggestions#293]
Hi,
I'm using zsh with oh-my-zsh on OSX High Sierra with iTerm 2. I recently installed the plugin and really like it but I have one problem: When I type 'ls' for example, it might suggest 'ls -la' which is fine. But when I now hit enter, 'ls' is executed (which is correct as well), but my terminal looks like it executed 'ls -la' (which it of course didn't). I am so far as narrowing it down to a problem with my theme or any plugin but I'm not sure what exactly is causing it and what I can do to fix it. Any suggestions?
Thanks.

Edit: It is no problem with my theme but any of these plugins:
git autojump brew common-aliases history jsontools mvn osx screen sudo svn tmux wd zsh-syntax-highlighting zsh-dwim docker
Edit #2: Problem is with zsh-syntax-highlighting :(

**Comment by ericfreese** [comment]
Ok, I'm going to go ahead and close this since it seems to be unrelated to this plugin.
