### ISSUE TITLE
Erasing sensitive or mistaken commands from history

### ISSUE THREAD

**Issue by mikob** [zsh-users/zsh-autosuggestions#297]
I'm trying to get zsh-autosuggestions to respect removed history without restarting the shell. 

I've tried deleting the item from `~/.zhistory`, `history -d {offset}`, `fc -R` but still the item I've removed shows up as an autosuggestion. Even though the command doesn't show when I run `history`.  I feel there might be some caching going on somewhere in https://github.com/zsh-users/zsh-autosuggestions/tree/master/src/strategies but can't pinpoint what needs to change.

**Comment by ericfreese** [comment]
Hmm.. there's no caching implemented. We just access the provided `$history` variable. Try running `echo ${history[(r)<prefix>*]}"` where `<prefix>` is the beginning of the history item you're trying to remove. For example, if the command was `ls foo | grep bar`, try `echo ${history[(r)ls foo*]}`. If it doesn't print the command, it's not visible to zsh-autosuggestions.

**Comment by mikob** [comment]
Thanks for the link. Yeah, the command stays in `$history` even after my various removal methods. I can't modify that variable because it's readonly. I wonder if there's some way to force it to reload without reloading the whole shell...

**Comment by ericfreese** [comment]
Going to close since it sounds like your issue is with zsh itself and not this plugin. You cloud try the mailing list if you're still stuck: http://zsh.sourceforge.net/Arc/mlist.html
