### ISSUE TITLE
Beep after pressing the → key.

### ISSUE THREAD

**Issue by politicus** [zsh-users/zsh-autosuggestions#300]
I can hear a beep appearing after I pressed the → key. Annoyging

Close to [this](https://github.com/zsh-users/zsh-autosuggestions/issues/79) issue. 
Tried to change the syntax highlighting plugin. Didn't solve the problem.

**Comment by ericfreese** [comment]
Hi @politicus. Can you reproduce with only this plugin loaded? Try running `zsh -f` to run zsh without sourcing your `.zshrc` file and then manually source `zsh-autosuggestions.zsh` by running `source your/path/to/zsh-autosuggestions.zsh`. Do you still have the beeping?

**Comment by politicus** [comment]
@ericfreese Thanks for your answer. The beep disappeared a few days ago for no apparent reason.
