### ISSUE TITLE
Breaks vi-delete function

### ISSUE THREAD

**Issue by glacambre** [zsh-users/zsh-autosuggestions#302]
Using rxvt-unicode (urxvt) v9.21, zsh 5.3.1 and zsh-autosuggestions v0.3.3:
Start a "clean" shell, go into vi mode, type something, press `<Esc>`, press `d`, press `l`, the last letter you type will be deleted. Now source zsh-autosuggestions, type something, do `<Esc>dl`, the last letter won't be deleted.
Something like this:
```zsh
zsh -f
set -e vi
echo^[dl^C
source zsh-autosuggestions.zsh
echo^[dl
```

**Comment by glacambre** [comment]
I should add that it's `dl` that is specifically broken, every other vi-delete action (`dd`, `dh`...) works as expected.

**Comment by ericfreese** [comment]
I've added a failing spec for this to the `fixes/vi-delete` branch: https://github.com/zsh-users/zsh-autosuggestions/blob/fixes/vi-delete/spec/integrations/vi_mode_spec.rb

**Comment by ericfreese** [comment]
Should be fixed now on `develop`. Will go out with the next release.
