### ISSUE TITLE
Use Up and Down to go Through Suggestions?

### ISSUE THREAD

**Issue by mjklemm** [zsh-users/zsh-autosuggestions#303]
Hi,

I was searching Google to find out if zsh-autosuggestions can use Up and Down to scroll through the commands that it suggest for completion.  Some thing like this:

If this works, please ignore my ignorant question and point me to the right settings.  If it's not yet there, can you please consider this issue a feature request?

Thanks!

Kind regards,
        -michael

**Comment by rumbletumjum** [comment]
You'll want to have something like 

`if [[ "${terminfo[kcuu1]}" != "" ]]; then`
`  autoload -U up-line-or-beginning-search`
`  zle -N up-line-or-beginning-search`
`  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search`
`fi`

`if [[ "${terminfo[kcud1]}" != "" ]]; then`
`   autoload -U down-line-or-beginning-search`
`  zle -N down-line-or-beginning-search`
`  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search`
`fi`



somewhere in your init scripts along with zsh-autosuggestions. Most people get this from oh-my-zsh and don't realize it's not really default ZSH behavior (I sure didn't which is the only way I know what enables it). Someone correct me if I'm wrong, but zsh-autosuggestions basically grabs the first little bit from your history that matches what you've started typing and drops it in the current line being edited. Enabling the above will give you the same sort of history search sans zsh-autosuggestions, but they work better together IMO.

**Comment by ericfreese** [comment]
I think @rumbletumjum's suggestion should solve this issue. I'm going to go ahead and close.

**Comment by gitgt** [comment]
I don't know if this is the same as I want, so I'll explain. I use Zsh in Ubuntu without oh-my-zsh.
When I start typing ´nan´ I see "nano previous-file". But when I wan't "nano file-before-that-one" I cannot just scroll with that ´nan´.
I tried to put this code in ~/.zshrc but I don't see a change.
