### ISSUE TITLE
[wish-list] suggest command name in the $PATH and support predefined suggestions

### ISSUE THREAD

**Issue by skywind3000** [zsh-users/zsh-autosuggestions#306]
Suggestion is the most impressive feature in fish, and zsh-autosuggestions is great too, now I switch 
back to zsh because of this plugin. But it could be really cool if zsh-autosuggestions supports these two features:

**1. suggest command name in the $PATH**

Fish could suggest me a proper command name which isn't in my command history but in the $PATH.
This is really convenience when I first run a new command but forget its name.

**2. Predefined suggestions:**

Terminal users always switch between different remote systems, but when I login to a new system, every suggestions should be collected from scratch, zsh-suggestions is useless on a new machine.

It is unwise to distribute my command history file everywhere, the command history is not designed for this. But if I can edit a predefined suggestion file, input some common use commands, like:

```bash
# ~/.zsh-suggestions.common
tar -zvxf abc.tar.gz
tar -cvzf abc.tar.gz abc/*
git pull 
git push origin master
....
```

I can distribute this file to every remote system I will work on, and zsh-suggestions will help me a lot on the new machines.

**Comment by ericfreese** [comment]
If someone would like to implement these, they'd be relatively implemented as alternative suggestion strategies. Check out https://github.com/zsh-users/zsh-autosuggestions/tree/master/src/strategies for a couple examples.

Another idea that I would love to implement some day would be tying into the completion system as has been suggested in #111. That would accomplish your first suggestion.

**Comment by skywind3000** [comment]
I really want to implement this, but the longest bash script I wrote is no more than 100 lines and  zsh script is definitely beyond my ability.

After posting this, I realized that my first suggestion could be implemented by the second one. Just count every executable in the $PATH at the first time and create a new predefined file.

And "Suggest Program Options/Flags" discussed in https://github.com/zsh-users/zsh-autosuggestions/issues/111 may also be implemented with a auto-generated predefined file .

**Comment by ericfreese** [comment]
> I really want to implement this, but the longest bash script I wrote is no more than 100 lines and zsh script is definitely beyond my ability.

I think it would take less than 100 lines to implement this. Define your own strategy function `_zsh_autosuggest_strategy_my-strategy` and set `ZSH_AUTOSUGGEST_STRATEGY` to `my-strategy`. In your suggestion function, just use `typeset -g suggestion="your suggestion"` to return a suggestion. Zsh script is a lot like Bash, and [most everything is documented](http://zsh.sourceforge.net/Doc/).

**Comment by skywind3000** [comment]
Thanks for your instructions, finally, I successfully made it. Would you please take a look at it ?

https://github.com/skywind3000/zsh-autosuggestions/blob/master/src/strategies/predefined.zsh

It will search the history at first, and than search the predefined files.

Predefined files are declared by:
- `$ZSH_AUTOSUGGEST_PREDEFINED_NAME` : auto-generated file name, default to `~/.zsh_autosuggest`
- `$ZSH_AUTOSUGGEST_PREDEFINED_PATH` : user predefine file names separated by simicolon

Content of auto-generated file `~/.zsh_autosuggest`:
1. all executable names in `$PATH`
2. content of a builtin database: "[predefined.txt](https://github.com/skywind3000/zsh-autosuggestions/blob/master/src/strategies/predefined.zsh)",  which is generated with [tldr pages](https://github.com/tldr-pages/tldr/).

zsh-autosuggests is much more friendly with these predefine files on any new system.

**Comment by skywind3000** [comment]
I found that fish seem like doing similar thing:

When I first login fish on a new system and quit immediately, there was a unfinished job:

    python3 $update_args

```
root@vmn6:/home/skywind # fish
Welcome to fish, the friendly interactive shell
root@vmn6 /u/h/skywind# 
There are still jobs active:

   PID  Command
 91055  python3 $update_args >/dev/null ^/dev/null &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
root@vmn6 /u/h/skywind# 
root@vmn6:/home/skywind # exit
```

**Comment by skywind3000** [comment]
After using and updating it for nearly a month, I believe it is stable enough. So, a new PR for this has been created:

https://github.com/zsh-users/zsh-autosuggestions/pull/315

Due to my poor zsh scripting skill, feel free to close this if you have better implementation.

**Comment by ericfreese** [comment]
@skywind3000 Please try out [`features/completion-suggestions`](https://github.com/zsh-users/zsh-autosuggestions/tree/features/completion-suggestions) branch and let me know if that covers your use cases. See the PR #330 for more info.

**Comment by ericfreese** [comment]
#330 has been merged to `develop`. Hope that will cover your desired use case.
