### ISSUE TITLE
It beeps whenever I expand the grey text with right arrow

### ISSUE THREAD

**Issue by nikitavoloboev** [zsh-users/zsh-autosuggestions#307]
Whenever I try to expand the greyed out suggestion like here:

![2018-01-24 at 19 05](https://user-images.githubusercontent.com/6391776/35348841-94aab1a4-0139-11e8-87be-06b82b961dbc.png)

I press right arrow here and it expands the suggestion like so: 

![2018-01-24 at 19 06](https://user-images.githubusercontent.com/6391776/35348863-a8f267ba-0139-11e8-966d-a1a7ee759de8.png)

But it also makes a beeping (error) sound. I think this is a bug.

Thank you for any help.

**Comment by Zetagonality** [comment]
The fix is in the /develop branch, it hasn't been merged into master yet.

**Comment by nikitavoloboev** [comment]
Is it possible to merge it?

**Comment by nikitavoloboev** [comment]
It started working for me.

**Comment by fferri** [comment]
Not working for me. Still get the beep when completing with forward-char. Tested in `zsh -f`.

```
$ (cd ~/.zsh-autosuggestions ; git rev-parse HEAD --abbrev-ref HEAD )
fa5d9c0ff5fb202545e12c98dae086d91d70ba50
develop
```
