### ISSUE TITLE
4.3.11 requirement

### ISSUE THREAD

**Issue by rumbletumjum** [zsh-users/zsh-autosuggestions#309]
I'm wondering what features of 4.3.11 are required for this plugin. I'm considering putting together a zsh distro for our shared corporate environment and wanted to incorporate zsh-autosuggestions (and zsh-syntax-highlighting) but I only have access to 4.3.10. I'm not a zsh wizard by any means, so I'm assuming there are changes to zle that require 4.3.11.

Any help is greatly appreciated.

**Comment by ericfreese** [comment]
I have never tried running it on 4.3.10 so I don't know if anything would specifically break. We only run CI on versions back to 4.3.11 though, so it would be unsupported. Main reason for choosing 4.3.11 was that it is what's bundled for RHEL6 (see #296 and #298). Also, zsh-syntax-highlighting supports back to 4.3.11. I'd say try it out on 4.3.10 and if it works, go for it! Let us know how it goes :)
