### ISSUE TITLE
Have to provide source from the manual installation to get it working after every terminal restart.

### ISSUE THREAD

**Issue by yankeexe** [zsh-users/zsh-autosuggestions#310]
`source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh`
Have to use the command mentioned in manual installation to get the plugin working. 
tried the method with oh-my-zsh but it didn't work out.

**Comment by ericfreese** [comment]
You'll need to add that line to a .zshrc file in your home directory for the plugin to be sourced before every shell session.
