### ISSUE TITLE
backward-word support

### ISSUE THREAD

**Issue by getaaron** [zsh-users/zsh-autosuggestions#313]
If I accidentally accept a suggestion using the `forward-word` widget I can't undo that acceptance by using the `backward-word` widget. This would be a helpful feature.

**Comment by ericfreese** [comment]
You could try using backward-delete-word instead.

**Comment by ericfreese** [comment]
Going to go ahead and close this. I don't think Fish implements this behavior and this plugin is intended to mirror the behavior of Fish autosuggest.
