### ISSUE TITLE
Muted gray color not working

### ISSUE THREAD

**Issue by tanmay-kulkarni** [zsh-users/zsh-autosuggestions#314]
I get the suggestions properly. But they are shown in normal white color which is exactly the same as the color of the text that I'm typing.

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

is properly set in the zsh-autosuggestions.zsh file.

I'm using Oh-My-Zsh and exactly followed the steps given in the instructions to install the plugin. I even removed it and reinstalled but the same issue persists. Do you know what the problem might be?

**Comment by HaxorGaruda** [comment]
maybe problem is color setting in your terminal..  try to change ...

**Comment by tanmay-kulkarni** [comment]
@HaxorGaruda It doesn't seem that way. I use LXterminal with standard Solarized color scheme. I tweaked the foreground and background colors, set them to default but to no avail. Both the suggested text and typed text get the same color.

**Comment by warren-lei** [comment]
I think it is a problem of terminal, try to export TERM=xterm-256color. I have solved this problem by this way.

**Comment by JackBogart** [comment]
> I think it is a problem of terminal, try to export TERM=xterm-256color. I have solved this problem by this way.

Spent over an hour today trying to fix my issue, this fixed it. Thank you!!!!
