### ISSUE TITLE
can not set  `bindkey "^;" autosuggest-accept`

### ISSUE THREAD

**Issue by eromoe** [zsh-users/zsh-autosuggestions#316]
`ctrl + space` is the default shortcut to switch input method on Windows.
So I'd like use `ctrl + ; ` 

But it is not working 
`bindkey "^;" autosuggest-accept`

**Comment by ericfreese** [comment]
I don't think it's possible to bind anything to `^;` https://stackoverflow.com/a/28984903/154703
