### ISSUE TITLE
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE Not Working Correctly?

### ISSUE THREAD

**Issue by austinarbor** [zsh-users/zsh-autosuggestions#322]
If I set `ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE` to a value < 6, for some reason it breaks the autosuggestion functionality.  Anything >= 6 seems to work fine.  I basically want to be able to disable autosuggestions for all pasting since whenever I paste a command it is always the full command

**Comment by ericfreese** [comment]
What are you using to test that the autosuggestion functionality is broken? Can you give an example?

**Comment by austinarbor** [comment]
It appears to be working on my personal laptop actually, when `ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE` >= 2.  When I set it to 1, autosuggestions do not appear in the prompt when I type a command (prefix to a command)

**Comment by ericfreese** [comment]
I think you may be misunderstanding how BUFFER_MAX_SIZE works. When it is set to X, no suggestions will be shown if the length of the buffer is greater than X. So when you set it to 1, no suggestions are ever shown.

> for whatever reason, the autosuggestions stop appearing when I set the value to <= 5

Do autosuggestions show when you set it to 5, but type less than 3 characters? Again, a more concrete example would be very helpful here.

**Comment by austinarbor** [comment]
Does buffer refer to just the clipboard buffer, or the buffer of the total input entered on the shell prompt?

**Comment by ericfreese** [comment]
It refers to the text entered into the shell prompt.

If you want to disable suggestions after pasting, you could add this line to your config:

`ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=bracketed-paste`.

**Comment by austinarbor** [comment]
Oh ok, then my understanding was incorrect.  I thought I had read somewhere that setting a small-ish value for `ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE` would improve pasting speed into the prompt (maybe here? https://github.com/zsh-users/zsh-autosuggestions/issues/215#issuecomment-274373957 , or https://github.com/zsh-users/zsh-autosuggestions/issues/141) so thats why I probably thought buffer strictly referred to the pasting buffer. 

I don't necessarily care about enabling/disabling suggestions _after_ pasting, I just want to speed up the paste action itself.  What is the latest and greatest method / settings tune for that these days?

**Comment by ericfreese** [comment]
Disable bracketed-paste-magic (BPM) if you don't need it. Otherwise, you can use zsh 5.4 or greater for faster pastes with BPM. Can also try the solution [here](https://github.com/zsh-users/zsh-autosuggestions/issues/238#issuecomment-303402980), disabling autosuggestions while BPM is running. There's an example of that in the specs here: https://github.com/zsh-users/zsh-autosuggestions/blob/master/spec/integrations/bracketed_paste_magic_spec.rb

**Comment by austinarbor** [comment]
I am using zsh 5.5.1 but didn't really notice any speed improvements with pasting. I commented out the lines below in `~/.oh-my-zsh/lib/misc.zsh` and that did speed up pasting speed significantly!

```bash
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic
```

I initially tried the first linked solution by adding those functions to my `.zshrc` file but that didn't seem to have any effect

Thanks for the help

**Comment by austinarbor** [comment]
Just as an aside - are there any negative consequences from disabling BPM?
