### ISSUE TITLE
Broken ability to scroll up through bash history

### ISSUE THREAD

**Issue by kleinjm** [zsh-users/zsh-autosuggestions#323]
I've tried installing the plugin manually, via oh-my-zsh and brew and have experienced this issue no matter how I install it. I'm using oh-my-zsh, iTerm, and tmux and narrowed down this plugin as the issue.

Basically, with the plugin enabled in my zshrc, I lose the ability to scroll up through my command history. It seems that I can hit the up arrow and get my last command and then any similar matching commands. Ie. if my last command was `git add` then I can get that by hitting up arrow. If I hit it again I will get `git commit` or `git merge` commands but only a few and then I can't get up to any more history. So it seems that the first word is being matched and anything else in the reverse history is being skipped.

You can see my entire environment configuration at [my dotfiles](https://github.com/kleinjm/dotfiles). Let me know what other info you need, thanks!

**Comment by ericfreese** [comment]
This sounds like a duplicate of #241. Try `develop` branch and let me know if that solves your problem.

**Comment by kleinjm** [comment]
That did it, thanks! I'll close this one and follow that issue instead
