### ISSUE TITLE
Keybinding not working in IntelliJ embedded terminal

### ISSUE THREAD

**Issue by vickyliuyi** [zsh-users/zsh-autosuggestions#326]
Hi, 

I tried to add the `bindkey '^[[Z' autosuggest-accept  ` to make shift+tab work like the right arrow key to accept the suggestions. I tried type that directly and also added that into my .zshrc files. I'm using zsh with the Mac built-in terminal. It turns out it worked fine if I opened a regular terminal window but not working at all in the IntelliJ embedded terminal window. 
Any idea what might be wrong?

Thanks!

**Comment by ericfreese** [comment]
Can you bind shift + tab to any other widgets in the IntelliJ terminal?

**Comment by ericfreese** [comment]
Going to go ahead and close this as I'd guess the problem is unrelated to this plugin.

**Comment by gloryVine** [comment]
I'm having the same issue three years later. I disabled all other keymaps of shift-tab in PyCharm's settings, and it's still not working.
