### ISSUE TITLE
Please add antigen to docs

### ISSUE THREAD

**Issue by jleaders** [zsh-users/zsh-autosuggestions#331]
Please add an `antigen` installation guide to the documentation.

I presume it would be a one-liner:
`antigen bundle zsh-users/zsh-autosuggestions`

**Comment by ericfreese** [comment]
> I presume it would be a one-liner:
> `antigen bundle zsh-users/zsh-autosuggestions`

That's right.

I'm thinking we should break the installation instructions out to a separate doc since they're getting so long. A PR for this would be very welcome!

**Comment by ericfreese** [comment]
See #349
