### ISSUE TITLE
autosuggestions not work for Guake terminal ~

### ISSUE THREAD

**Issue by roachsinai** [zsh-users/zsh-autosuggestions#336]
I'm on Manjaro, Gnome3, setting Guake autostart.

---

I install this great plugin from the `community` repository by:

`pacman -S zsh-autosuggestions`

And added `source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh` to `.zshrc`.

---

The `autosuggestions` not work when I use Guake, however it **WORKS** on gnome-terminal.

Could you please tell me where is wrong?

**Comment by ericfreese** [comment]
Hmm. Tough to say without more info. My guess is that the color you're using for the suggestion in Guake is the same as the background. Try setting `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` to something like `fg=3` or `fg=4` and see if the suggestions appear.

**Comment by roachsinai** [comment]
Yes, you're right. Thanks a lot.

**Comment by roachsinai** [comment]
Hi @ericfreese , sorry to talk about this issue again. As I install this plugin from AUR, the only to do it is change the `fg` at `/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh`. It works.

I want to konw above is the only way cause I had create a zsh file under $ZSH_CUSTOM directory, and it doesn't work.

**Comment by roachsinai** [comment]
Ok, thanks again, and how about change blow

```
# Widgets that accept the entire suggestion
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
	forward-char
	end-of-line
	vi-forward-char
	vi-end-of-line
	vi-add-eol
)

# Widgets that accept the entire suggestion and execute it
ZSH_AUTOSUGGEST_EXECUTE_WIDGETS=(
)
```

to

```
# Widgets that accept the entire suggestion
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
	end-of-line
	vi-forward-char
	vi-end-of-line
	vi-add-eol
)

# Widgets that accept the entire suggestion and execute it
ZSH_AUTOSUGGEST_EXECUTE_WIDGETS=(
	forward-char
)
```

---

I just want to use `^F` to accept and execute the autosuggest.

**Comment by ericfreese** [comment]
Yes you should be able to put that in your zshrc too

**Comment by roachsinai** [comment]
emm, thanks! great!
