### ISSUE TITLE
Please call `zle` with `--`

### ISSUE THREAD

**Issue by psprint** [zsh-users/zsh-autosuggestions#337]
Hello,
I have widgets named in "-a-widget" convention. Following error occurs:

_zsh_autosuggest_bind_widget:zle:47: bad option: -s

The function is -fast-highlight-check-path-async. I've checked with man and -fa are legitimate options that's why it complains about "-s". You need to add "--", example: `zle -N -- -fast-process`, etc.

**Comment by ericfreese** [comment]
Thanks for reporting. This should be fixed on `develop` and will go out with the next release.
