### ISSUE TITLE
Problems with setopt warn_create_global

### ISSUE THREAD

**Issue by vaeth** [zsh-users/zsh-autosuggestions#341]
With `setopt warn_create_global` (on branch features/completion-suggestions), I receive for the first usage the warnings
```
_zsh_autosuggest_fetch_suggestion:7: scalar parameter strategy created globally in function _zsh_autosuggest_fetch_suggestion
_zsh_autosuggest_capture_completion:6: scalar parameter REPLY created globally in function _zsh_autosuggest_capture_completion
```
I suppose the former is indeed a missing `local strategy`.
Not sure about the latter; perhaps at least the warning can be suppressed somehow?

**Comment by ericfreese** [comment]
Should be fixed now with 43a011026ffd9c7e9dba4cf022922a4877f1d4e7.

Thanks @vaeth!
