### ISSUE TITLE
`completion` strategy leaks zsh processes on Mac OS

### ISSUE THREAD

**Issue by ericfreese** [zsh-users/zsh-autosuggestions#347]
Haven't investigated enough to reproduce in an isolated environment, but after running `completion` strategy for a while on my mac, I built up a lot of extra zsh processes that needed to be killed.

Does not appear to be an issue on linux, but it could also have to do with the ZSH version or something...

**Comment by ericfreese** [comment]
This might be fixed with #350. I cleaned up some funky recursive completion fetching that may have caused this issue. @alok take a look?

**Comment by alok** [comment]
I *think* that fixed it.

**Comment by ericfreese** [comment]
Thanks @alok I'll let this issue hang out for a while until I can confirm on my mac as well.

**Comment by ericfreese** [comment]
Confirmed it seems this issue is fixed now
