### ISSUE TITLE
Completion strategy sometimes shows incorrect suggestion

### ISSUE THREAD

**Issue by ericfreese** [zsh-users/zsh-autosuggestions#354]
Typing `ls "/"` results in a suggestion of `ls "/"ls "/bin"`.

The issue seems to be that pressing tab after a quoted string moves your cursor to the end of the string in the quote and fetches completions there.

Need to figure out a way to prevent `complete-word` in the pty from ever modifying the buffer left of where the cursor is when the completion widget is invoked.

**Comment by joshddunn** [comment]
Not sure if this would be related.

Works fine with proper capitalization
<img width="297" alt="screen shot 2018-12-01 at 7 29 11 pm" src="https://user-images.githubusercontent.com/7513070/49334249-749f4400-f59f-11e8-99bf-70307f6d8b5f.png">

Without proper capitalization, proper suggestion but displays the entire suggestion and what you have already written.
<img width="420" alt="screen shot 2018-12-01 at 7 28 59 pm" src="https://user-images.githubusercontent.com/7513070/49334250-77019e00-f59f-11e8-8e44-1c091780dd39.png">

CASE_SENSITIVE is blank for me
<img width="209" alt="screen shot 2018-12-01 at 7 33 27 pm" src="https://user-images.githubusercontent.com/7513070/49334267-0c9d2d80-f5a0-11e8-8f1c-8dcf896615e6.png">

**Comment by ericfreese** [comment]
There's so many ways this can go wrong, I'm probably just going to add some code to `_zsh_autosuggest_fetch_suggestion()` to drop suggestions that don't match the prefix exactly.
