### ISSUE TITLE
auto complete not working fully for apt-get install

### ISSUE THREAD

**Issue by behrangsa** [zsh-users/zsh-autosuggestions#361]
I want to auto-complete `apt-get install ` into `apt-get install --install-suggests`.

I enter `apt-get install --` and press the <kbd>TAB</kbd> key.

# Here's what I expect:

To be provided with all options starting with `--`, such as:

* `--no-install-recommends`
* `--install-suggests`
* `--download-only`
* ...

# Here's what happens:

Pressing <kbd>TAB</kbd> auto completes to:

`apt-get install ruby-rails-assets-markdown-it--markdown-it-for-inline`

**Comment by ericfreese** [comment]
This seems to be unrelated to this plugin. This plugin does nothing related to tab completion.

You may want to send an email to one of the upstream mailing lists: http://www.zsh.org/mla/

**Comment by rubenanapu** [comment]
# How I solved it

I had auto completion problems trying to autocomplete `wget` with `apt-get install wg[TAB][TAB]` and I managed to solve it by removing the `--no-generate` parameter from the flies below:

```
/usr/share/bash-completion/completions/apt-cache
/usr/share/bash-completion/completions/apt-get
```

It is worth mentioning that these files are available only after you install `bash-completion`.

The `--no-generate` parameter I'm referring to can be seen in the line below, but I removed ALL  `--no-generate`, not only from this line: 
https://github.com/scop/bash-completion/blob/master/completions/apt-get#L28

# How did I come to this point?

I got to this point after running `set -v` previous to `apt-get install wg[TAB][TAB]`, which showed that the command executed was:
```
apt-cache --no-generate pkgnames wg
```
and the output was an error:
```
E: Could not open file  - open (2: No such file or directory)
```
When I executed `apt-cache pkgnames wg` without the `--no-generate` I correctly got the list for autocompletion:
```
root@484f5c8f56ba:/# apt-cache pkgnames wg
wgalician-minimos
wget2
wgaelic
wget
wgerman-medical
wget2-dev
```
Hope this helps.
