### ISSUE TITLE
After changing ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE nothing happens

### ISSUE THREAD

**Issue by Lomey** [zsh-users/zsh-autosuggestions#362]
When I set 
  `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=green'` or   
  `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=2'` or
  `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=1'` or something else
in 
> ./.oh-my-zsh/custom/plugins/zsh-autosuggestions/src/config.zsh

then close and open terminal NOTHING happens.

Maybe it is because of default terminal properties.

Plese help!

Thank you!

**Comment by ericfreese** [comment]
The files under src/ are source files. The values in src/config.zsh are default values. You're not intended to modify those files. To configure the plugin, you should set the value of those variables in your zshrc (or in a custom config file for oh my zsh).

Carefully re-read the section in the readme on configuring the plugin: https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#configuration
