### ISSUE TITLE
wishlist: support a custom lookup table of auto-replace suggestions.

### ISSUE THREAD

**Issue by cogburnd02** [zsh-users/zsh-autosuggestions#370]
Nerd-fonts supports a 'npm' symbol at E71E

http://nerdfonts.com/?set=e71e#cheat-sheet

I can set up an alias so that when this character is entered, the command 'npm' is executed.

it would be very nice if I could type 'npm' and have the shell 'correct' it to the 'npm' character at E71E as I type.

presumably, this would be fairly simple to do by adding a lookup table of texts (like 'npm') to replace and what to replace them with. (in my case, the 'npm' character, but in others' cases, specific common spelling errors could be put in the lookup table too.)

**Comment by ericfreese** [comment]
I think this feature is outside the scope of this plugin. It's intended to provide suggestions based on things you've already typed, without changing what you've typed. Could be an interesting idea for a different plugin though.
