### ISSUE TITLE
_zsh_autosuggest_modify:27: unrecognized modifier `0'

### ISSUE THREAD

**Issue by zhugaozi** [zsh-users/zsh-autosuggestions#372]
when i use zsh_autosuggestion in my oh-my-zsh plugins, it prompt “_zsh_autosuggest_modify:27: unrecognized modifier `0'”. I don't know what happend, help me, please!

**Comment by zhugaozi** [comment]
I repaired it when i upgrade cento OS from version 6.3 to version 6.10. Tank you!

**Comment by ericfreese** [comment]
Looks like a dup of #250
