### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by bastien-wink** [zsh-users/zsh-autosuggestions#374]
Is it normal zsh-autosuggestions doesn't regroup simmilar commands ?

![capture d ecran de 2018-10-08 12-28-12](https://user-images.githubusercontent.com/7903123/46604229-d5595580-caf5-11e8-844b-fee5e1d39ff1.png)

We could implement an option to hide already shown entries, what do you think ?

**Comment by ericfreese** [comment]
From the screenshot, this looks to be something you have set up using `fzf`. This plugin looks nothing like that. That being said the `HIST_IGNORE_DUPS` zsh option may help you. 
https://unix.stackexchange.com/a/310714

Closing since it's not relevant to this plugin.
