### ISSUE TITLE
No autosuggestions when using Ubuntu terminal with "Solarized Dark" theme

### ISSUE THREAD

**Issue by tzfrs** [zsh-users/zsh-autosuggestions#375]
Hi, my stack is

* Ubuntu 18.04
* Default terminal with solarized dark theme
* zsh
* oh-my-zsh
* git, zsh-syntax-highlighting and zsh-autosuggestions plugin

Sadly, with this setup I am not seeing any autosuggestions. It looks like this

![image](https://user-images.githubusercontent.com/3509557/46650123-bdd4a800-cb9b-11e8-8579-b174934515b3.png)

As you can see, you can only see the `cd` but nothing that comes after. When I switch the theme to a different one you instantly see the suggestions

![image](https://user-images.githubusercontent.com/3509557/46650168-d775ef80-cb9b-11e8-812a-7af0a78399e3.png)

The setting was 

`ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8` which should be grey according to this link https://github.com/zsh-users/zsh-autosuggestions/issues/172#issuecomment-226022265

However, it's not visible, it somehow uses the default text color of the terminal. When I change `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` in `~/.oh-my-zsh/custom/plugins/zsh-autosuggestions` to `fg=black,bold` or even to `white` for example, it still is not visible under Solarized Dark and it looks the same under different themes, so it doesn't seem like this setting is actually used under Ubuntu. 

Any idea how I can make these visible?

**Comment by tzfrs** [comment]
Okay, I fixed this. This isn't a problem of `zsh-autosuggestions`. For anyone stumbling upon the same problem, it has to do sth. with the color palette the terminal is using, for example, I used the solarized colour palette.
Now, if I hover over a specific entry it says "Palette entry 8"  for example. If I edit this colour, this will change the syntax-highlithing colour. 

So you don't need to only change the built-in scheme but also adjust your palette below the themes.

**Comment by kaxap** [comment]
For those using iTerm2 with Solarized Dark theme, the suggestion color is in Preferences -> Profiles -> Colors. Change "Bright Black" under ANSI colors:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/2851970/146740971-71cd8629-76f3-49fd-a12c-91ad5daaf1f4.png">

**Comment by muya** [comment]
> For those using iTerm2 with Solarized Dark theme, the suggestion color is in Preferences -> Profiles -> Colors. Change "Bright Black" under ANSI colors:
> 
> <img alt="image" width="296" src="https://user-images.githubusercontent.com/2851970/146740971-71cd8629-76f3-49fd-a12c-91ad5daaf1f4.png">

A setting of "50% Gray" worked well for me on iTerm with Solarized Dark Theme
