### ISSUE TITLE
Directory suggestions disappear with one use of `emulate -L zsh`

### ISSUE THREAD

**Issue by alok** [zsh-users/zsh-autosuggestions#379]
I'm using the `develop` branch.

When I hit tab, directory names as completions used to pop up (I have `autocd` set). Now, they don't.

The issue appears to be the line `emulate -L zsh` in `_zsh_autosuggest_modify` in `zsh-autosuggestions.zsh`. Removing it fixes the issue. No idea why.

**Comment by ericfreese** [comment]
Do you get this behavior using `zsh -f` and sourcing the plugin manually?

**Comment by mnpqraven** [comment]
Hello, i'm also having this issue (version 0.5.0). using `zsh -f` and sourcing the plugin does also replicate the issue, deleting the line `emulate -L zsh` also fixed the issue. My laptop doesn't have this issue even with the line `emulate -L zsh` though which is weird. I don't really know where the difference is that can cause the bug as my pc and laptop use the same dotfiles. If there's anything i should test let me know

**Comment by ericfreese** [comment]
@mnpqraven What version of zsh are you using? And what is the output of `setopt`?

**Comment by mnpqraven** [comment]
both machines are on `zsh 5.6.2 (x86_64-lc-linux-gnu)`
the setopt are also identical
````
alwaystoend
autocd
autopushd
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
````

**Comment by ericfreese** [comment]
I have a minimal `.zshrc` from @Ifnister [here](https://github.com/zsh-users/zsh-autosuggestions/issues/394#issuecomment-444175287) that reproduces the issue:

```
setopt autocd 
autoload -Uz compinit
compinit
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
```

**Comment by mnpqraven** [comment]
i just tested on the working machine, the issues also appears in `zsh -f` with manual plugin sourcing

**Comment by ericfreese** [comment]
Looks like this was introduced with #360. Will have to find a different fix for #334.

**Comment by ericfreese** [comment]
As a workaround for now, you can add `expand-or-complete` (or whatever is bound to tab (`^I)`) to `ZSH_AUTOSUGGEST_IGNORE_WIDGETS` in your `.zshrc` after sourcing the plugin.

```sh
# Check which completion widget you're using
% bindkey '^I'
"^I" expand-or-complete
```

```sh
# Add to your .zshrc
ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(expand-or-complete)
```

Going forward, we can probably just add all of the completion widgets to that array, but there may be a way we can fix the issue without having to disable suggestions for those widgets.

**Comment by ericfreese** [comment]
Ok @alok @mnpqraven, I've got a fix on branch `fixes/autocd-tab-completion` (#402). Try it out and let me know if it works?

**Comment by mnpqraven** [comment]
hi @ericfreese, it seems to be working again now, thank you very much, i'll keep this updated if a run into a bug again

**Comment by alok** [comment]
Works for me.
