### ISSUE TITLE
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE is overwritten at startup

### ISSUE THREAD

**Issue by Gerrit-K** [zsh-users/zsh-autosuggestions#385]
I'm used to separate my dotfiles based on their scope. E.g. I have a file `.colors.zsh` that defines all colors of my theme and makes sure that all components (prompt, LS_COLORS, completion, ...) share the same palette. Some plugins require these variables to be set prior to `zplug load` which is why I source that file early in my `.zshrc`. 

Unfortunately most variables of `zsh-autosuggestions`, including `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE`, are [overwritten at startup](https://github.com/zsh-users/zsh-autosuggestions/blob/master/zsh-autosuggestions.zsh#L45) with their respective default values which makes pre-configuration impossible. This could be fixed by a simple check prior to setting the default value.

**Comment by ericfreese** [comment]
#335 #378

**Comment by Gerrit-K** [comment]
Oh, sorry about the duplicate ... I was probably too focused on this particular Variable when I looked through the existing issues.
