### ISSUE TITLE
Selecting a color from the xterm256 pallet

### ISSUE THREAD

**Issue by ChaosCA** [zsh-users/zsh-autosuggestions#388]
This question has probably been asked, and I tried to search but couldn’t seem to find any with the same question.

Is it possible to set the suggestion color to an exact color in the xterm256 color pallet?
https://jonasjacek.github.io/colors/

The standard usually is ‘color’ + index of the color. However I can’t get this to work. Looking at the documentation for how it should be formatted doesn’t show how you can choose a specific color that doesn’t have a name.

Any help would be appreciated!

**Comment by Donng** [comment]
#262 
This issue may help you.It works for me and I'm using iterm2.

Setting the following in you `.zshrc`:

```
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=33"
```

**Comment by ChaosCA** [comment]
That’s not really related to what I said @Donng

**Comment by ericfreese** [comment]
It sounds like you're trying to use the value in [that table](https://jonasjacek.github.io/colors/) under the "Xterm Name" column (e.g. `DeepSkyBlue4`) but that won't work with this plugin. Instead use the value under "Xterm Number" column (e.g. `25`)

`ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=25"`

**Comment by ChaosCA** [comment]
Thank you!
