### ISSUE TITLE
Tab not showing hidden directories with globdots enabled

### ISSUE THREAD

**Issue by hectorhuertas** [zsh-users/zsh-autosuggestions#398]
Hi!
After updating to v0.5.0, tab completion doesn't show hidden directories. I tested with v0.4.3 and it works as expected.

Minimal .zshrc:
```
setopt globdots
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
```

**Edit: providing more details**
Running:
```
% zsh -f
% source ~/.zshrc
% mkdir test
% mkdir test/visible
% mkdir test/.hidden
% cd test
% cd <press TAB>
```
I get using v0.4.3:
```
% cd (test autosuggested)
.hidden/  visible/
```
I get using v0.5.0:
```
% cd visible/
```
I've tried with these 3 .zshrc, getting the same results for each version:
```
setopt globdots
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
```
```
setopt autocd
setopt globdots
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
```
```
setopt noautocd
setopt globdots
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
```

**Comment by ericfreese** [comment]
Hi @hectorhuertas, are you using `setopt autocd`? Can you post an example of what you have typed into the buffer when tab completion fails? This may be a dup of #379.

**Comment by hectorhuertas** [comment]
@ericfreese I've updated the issue with more details. `autocd` doesn't seem to make a difference. However, adding `ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(expand-or-complete)` to .zshrc as #379 suggests fixes the problem. Feel free to close this one if you think it's duped.

**Comment by ericfreese** [comment]
Merged that PR. Closing this issue. Let me know if you're still seeing the issue on develop branch.

**Comment by hectorhuertas** [comment]
Tried with the develop branch and it works great. Thanks!
