### ISSUE TITLE
_zsh_autosuggest_modify:30: unrecognized modifier `0'

### ISSUE THREAD

**Issue by Lqlsoftware** [zsh-users/zsh-autosuggestions#399]
Same problem to #250 , but changed to 30.
_zsh_autosuggest_modify:30: unrecognized modifier `0'

$ zsh --version
zsh 4.3.10 (x86_64-redhat-linux-gnu)

$ uname -a
Linux instance-0gr1kh01 3.10.0.514.26.2.el7.x86_64 #4 SMP Wed Aug 16 17:09:53 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

Can this bug be fixed? I really need this plugin...
Thx!

**Comment by ericfreese** [comment]
Closing in favor of #250. This plugin currently only supports back to 4.3.11, but could potentially push that back to 4.3.10 if it's not too much trouble.

**Comment by Lqlsoftware** [comment]
Thx man.
I upgrade my zsh to 4.3.11 and fix this bug.
Forgive my ignorance.
