### ISSUE TITLE
Broken prompt when autosuggestion contains non-latin languages

### ISSUE THREAD

**Issue by pcr910303** [zsh-users/zsh-autosuggestions#400]
[![asciicast](https://asciinema.org/a/GvQB8Zo8C4UNYIAy7Kp4zJRp8.svg)](https://asciinema.org/a/GvQB8Zo8C4UNYIAy7Kp4zJRp8)

This asciicast explains well, but basically when autosuggestion contains non-latin characters, the prompt breaks.

**Comment by ericfreese** [comment]
Can you reproduce using `zsh -f` and sourcing the plugin manually?

**Comment by pcr910303** [comment]
Ah, never mind. The file name was broken, there was special characters in the file name.
