### ISSUE TITLE
Tab not showing hidden files with globdots and zsh-autosuggestions enabled

### ISSUE THREAD

**Issue by duhok1** [zsh-users/zsh-autosuggestions#410]
With both `setopt globdots` and **zsh-autosuggestions** enabled, TAB does not show hidden directories/files.

This is my **~/.zshrc.local**:
```
setopt globdots
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
```

**However**, setopt globdots would work by _disabling_ zsh-autosuggestions!

FYI, using [Grml](https://git.grml.org/?p=grml-etc-core.git;a=blob_plain;f=etc/zsh/zshrc;hb=HEAD) zsh config file

**Comment by ericfreese** [comment]
Hi! This is actually fixed on the develop branch. Give that a shot for now. One of these days I'll get around to making a new release.

See #398
