### ISSUE TITLE
rebinding widgets slows down prompt display

### ISSUE THREAD

**Issue by leotaku** [zsh-users/zsh-autosuggestions#411]
This is related to my previous issue at #346, but the functionality surrounding the problem has since been reworked, which is why I chose to close said issue and open a new one.

### My problem:
zsh-autosuggestions is setup in a way that it rebinds all widgets on every precmd call. [here](https://github.com/zsh-users/zsh-autosuggestions/blob/master/zsh-autosuggestions.zsh#L734) 

Unfortunately, for me at least, this seems to cause a noticeable slowdown when displaying a new prompt.

### Possible fix
I don't think widget definitions change all that much during "normal" shell operation. So it could be a good idea for most use-cases to simply remove the hook or at least make it configurable.

**Comment by romkatv** [comment]
FYI: There is a PR that speeds this code up by 20%. Not much, but for the size of the PR it's not terrible. The PR has failed to elicit any reaction from the project owner though.

**Comment by ericfreese** [comment]
Put up PR #418 to add `ZSH_AUTOSUGGEST_MANUAL_REBIND` config option to disable automatic re-binding. Give it a shot and I'll merge it if there's no objections. Made my prompts about twice as fast according to @romkatv's prompt benchmark :+1:
