### ISSUE TITLE
cd history broken

### ISSUE THREAD

**Issue by magnus-gross** [zsh-users/zsh-autosuggestions#412]
This plugin breaks zsh cd history, see https://github.com/robbyrussell/oh-my-zsh/issues/7667#issuecomment-475991991

**Comment by magnus-gross** [comment]
`git bisect` identifies the bad commit as 4540304fa0a59b9054f19ede32088da6669938d1.

BTW, this commit also seemed to introduce some mixed indentation, there are even spaces and tabs mixed in the very same line in this commit, wtf.

**Comment by ericfreese** [comment]
Hi! This is actually fixed on the develop branch. Give that a shot for now. One of these days I'll get around to making a new release.

See #398
