### ISSUE TITLE
Getting warning, despite working correctly

### ISSUE THREAD

**Issue by kylemh** [zsh-users/zsh-autosuggestions#414]
Love your tool! I'm getting the following warning when I open a new shell: 
`Warning: plugin zsh-autosuggestions not found`.

... but it's working perfectly!

**Comment by ericfreese** [comment]
Hm this seems like it is an issue with your plugin manager. Are you using something like Oh My Zsh, Antigen, or Prezto?

**Comment by kylemh** [comment]
Indeed! I was coming here to close my own issue. Despite running MacOS, I should be following the Oh My Zsh installation instructions. Curious to see that it works though!
