### ISSUE TITLE
autosuggestion not working for oh-my-zsh

### ISSUE THREAD

**Issue by yuungH4x0r** [zsh-users/zsh-autosuggestions#416]
So I thought my autosuggestion was working, I had ran this command `source .oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh` and it was working fine, but right after I closed the terminal and opened up again the auto suggestion quit working. Any help?

**Comment by yuungH4x0r** [comment]
Yea so I have that already in my `.zshrc` but still nothing and I restarted the terminal already.

**Comment by ericfreese** [comment]
Ok I'm not sure why that wouldn't be working then. Maybe there is a typo or something? You could always add the manual `source` line to your `.zshrc`.

**Comment by yuungH4x0r** [comment]
That seemed to work. Thanks

**Comment by ashrafhadden** [comment]
Same problem. This only became an issue for me in the past week, maybe less than that. Even `source`ing doesn't fix it. It works totally fine in VSCode's terminal, so it's definitely iTerm specific.

**Comment by Warkst** [comment]
> ### ⚠️ Make sure iTerm's "Background" and "ANSI Normal Black" are set to two _distinctly_ different colors!
> > iTerm > Preferences > Profiles > Colors > ANSI Colors > Bright > Black
> > iTerm > Preferences > Profiles > Colors > Basic Colors > Background
> 
> @yuungH4x0r I had the same problem. Turns out I had the autosuggestion color (ANSI Bright Black) set exactly the same as my iTerm background so they blended together perfectly and I just couldn't see it 😅

Could this perhaps be added to the README somewhere, under troubleshooting?

**Comment by ericfreese** [comment]
> Could this perhaps be added to the README somewhere, under troubleshooting?

Good idea! Please feel free to write something up and send a PR.

**Comment by huwllewellyn** [comment]
I was missing the repo. To fix I ran:
`$ git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions`

**Comment by lawrenceagles** [comment]
running `git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions` solved this for me.

**Comment by xyyolab** [comment]
for me, messed up `zsh-autosuggestions` and `zsh-completions`.
I know it's stupid, but it cost me 5 minutes -_-
hope you don't ;)

**Comment by bayronq** [comment]
thanks.

**Comment by hongshaoyang** [comment]
>  ### ⚠️ Make sure iTerm's "Background" and "ANSI Normal Black" are set to two _distinctly_ different colors!

To add on, under iTerm > Preferences > Profile > Colors, **do not** choose Solarized Dark as a Color Preset as "Background" and "ANSI Bright Black" are the same colour!

**Comment by dipam7** [comment]
I am trying to install zsh-autosuggestions. I followed the manual steps as well as homebrew steps. However, in both cases when I try to do `source ~/.zshrc` I get the following error:

```
-bash:  ! ${+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_ORIGINAL_WIDGET_PREFIX} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_STRATEGY} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_CLEAR_WIDGETS} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_ACCEPT_WIDGETS} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_EXECUTE_WIDGETS} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_IGNORE_WIDGETS} : bad substitution
-bash:  ! ${+ZSH_AUTOSUGGEST_COMPLETIONS_PTY_NAME} : bad substitution
-bash: /Users/dipamvasani/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: syntax error near unexpected token `('
-bash: /Users/dipamvasani/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: `		user:_zsh_autosuggest_(bound|orig)_*)'
```

Can someone tell me what's wrong?

**Comment by veksha** [comment]
for me the solution was simply wrong order of commands in .zshrc

this line:
`plugins=(git z colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)`

was AFTER this line:
`source $ZSH/oh-my-zsh.sh`

I just swapped them and after that all plugins were loaded correctly. (no need for manual sourcing of plugins)

**Comment by ericfreese** [comment]
@dipam7 it looks like you’re using bash. This is a plug-in for zsh so it won’t work in bash. Install and use zsh to use this plugin. It looks like there’s a good write up on installing zsh here https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH

**Comment by igortuag** [comment]
> for me the problem was simply wrong order of commands in .zshrc
> 
> this line:
> `plugins=(git z colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)`
> 
> was AFTER this line:
> `source $ZSH/oh-my-zsh.sh`
> 
> I just swapped them and after that all plugins were loaded correctly. (no need for manual sourcing of plugins)

Thanks, it worked for me

**Comment by HabibulRahman** [comment]
> for me the problem was simply wrong order of commands in .zshrc
> 
> this line:
> `plugins=(git z colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)`
> 
> was AFTER this line:
> `source $ZSH/oh-my-zsh.sh`
> 
> I just swapped them and after that all plugins were loaded correctly. (no need for manual sourcing of plugins)

Thanks, it worked for me as well

**Comment by ngtankhoa** [comment]
@veksha thank you so much! this works for me as well. I think this should be considered the accepted answer.

**Comment by eeerpjw** [comment]
> for me the problem was simply wrong order of commands in .zshrc
> 
> this line:
> `plugins=(git z colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)`
> 
> was AFTER this line:
> `source $ZSH/oh-my-zsh.sh`
> 
> I just swapped them and after that all plugins were loaded correctly. (no need for manual sourcing of plugins)

thanks you so much, it worked for me.

**Comment by rodrigoalmeidagit** [comment]
I am currently using the theme below, which is the same as the initial OMZ standard, with only a few color changes.

====
# @host ➜ currentdir rvm:(rubyversion@gemset) git:(branchname)

# Get the current ruby version in use with RVM:
if [ -e ~/.rvm/bin/rvm-prompt ]; then
    RUBY_PROMPT_="%{$fg_bold[blue]%}rvm:(%{$fg[green]%}\$(~/.rvm/bin/rvm-prompt s i v g)%{$fg_bold[blue]%})%{$reset_color%} "
else
  if which rbenv &> /dev/null; then
    RUBY_PROMPT_="%{$fg_bold[blue]%}rbenv:(%{$fg[green]%}\$(rbenv version | sed -e 's/ (set.*$//')%{$fg_bold[blue]%})%{$reset_color%} "
  fi
fi

# Get the host name (first 4 chars)
HOST_PROMPT_="%{$fg_bold[green]%}@rodrigo-linux ➜ %{$fg_bold[cyan]%}%c "
GIT_PROMPT="%{$fg_bold[blue]%}\$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}"
PROMPT="$HOST_PROMPT_$RUBY_PROMPT_$GIT_PROMPT"

ZSH_THEME_GIT_PROMPT_PREFIX="git:( %{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]% %{$fg[yellow]%} ✗ %{$fg[blue]%)"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]% %{$fg[yellow]%} ✔ %{$fg[blue]%)"
====

It turns out that if I change the theme in the ~ / .zshrc file, to the Dracula theme, the auto suggestion stops working.

Can someone help me?
Thanks

**Comment by titaneric** [comment]
> I am trying to install zsh-autosuggestions. I followed the manual steps as well as homebrew steps. However, in both cases when I try to do `source ~/.zshrc` I get the following error:
> 
> ```
> -bash:  ! ${+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_ORIGINAL_WIDGET_PREFIX} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_STRATEGY} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_CLEAR_WIDGETS} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_ACCEPT_WIDGETS} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_EXECUTE_WIDGETS} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_IGNORE_WIDGETS} : bad substitution
> -bash:  ! ${+ZSH_AUTOSUGGEST_COMPLETIONS_PTY_NAME} : bad substitution
> -bash: /Users/dipamvasani/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: syntax error near unexpected token `('
> -bash: /Users/dipamvasani/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: `		user:_zsh_autosuggest_(bound|orig)_*)'
> ```
> 
> Can someone tell me what's wrong?

Perhaps a little late. You are running `zsh` command in `bash`, you may set your default shell to `zsh` by `sudo chsh -s $(which zsh) $USER`.

**Comment by jonathanmdr** [comment]
Running this command solved it for me:
`$ git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions`

**Comment by mikedixson** [comment]
> running `git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions` solved this for me.

This worked perfectly for me. Without spending too much time on this I guess apt installed to a location that OMZ doesn't pick up from just declaring the plugin by name.

**Comment by harmandeep-singh** [comment]
Folk like me generally did mistake pasting the end of file : follow the suggestion of @veksha

**Comment by acgq** [comment]
> 
> 
> i using bash in git version 2.33.1.windows.1
> 
> anyone get error like this in terminal windows 10 , but "Git bash" is working
> 
> config .zshrc
> 
>     * source $ZSH/oh-my-zsh.sh
> 
>     * plugins=(zsh-syntax-highlighting zsh-autosuggestions)
> 
>     * source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
> 
> 
> typing space or any key press , get this : [?1h←
> 
> ![WindowsTerminal_2021-10--26__222549](https://user-images.githubusercontent.com/26026818/138911520-d093a5d6-2ecf-4b22-9680-c8c07612b7a9.png)

I enconter this problem in windows too, disabling async mode (add  `unset ZSH_AUTOSUGGEST_USE_ASYNC` in .zshrc)  seem to be a workaround

**Comment by patricksousamacedo** [comment]
What worked for me was removing the spaces between the equal sign and the ()

It was like this:

plugins = (git zsh-autosuggestions)

I removed the spaces:

plugins=(git zsh-autosuggestions)

And I put the source line below the plugins line:

plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

**Comment by itzzmesid** [comment]
> I was missing the repo. To fix I ran: `$ git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions`

Worked

**Comment by faustaleonardo** [comment]
> for me the problem was simply wrong order of commands in .zshrc
> 
> this line: `plugins=(git z colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)`
> 
> was AFTER this line: `source $ZSH/oh-my-zsh.sh`
> 
> I just swapped them and after that all plugins were loaded correctly. (no need for manual sourcing of plugins)

A lifesaver. Thank you 👍

**Comment by JackWP1** [comment]
None of the above suggestions worked for me. So I had to `source` directly to the file to get mine working. Maybe this might help someone else.  Or maybe I'm missing a trick and there's a better way of doing this..?

in my **.zshrc** file:
```
plugins=(zsh-autosuggestions)
source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
```

**Comment by davidc360** [comment]
> source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

This worked for me

**Comment by jd-apprentice** [comment]
> I was missing the repo. To fix I ran: `$ git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions`

This solved the issue for me thanks!

**Comment by prawee** [comment]
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

source .zshrc

i solved.

**Comment by jonathanmdr** [comment]
I run `$ git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions` and It's worked for me.

**Comment by entwwwicklung** [comment]
hmm for me the issue was that instead of having plugins listed like this in `~/.zshrc` file
`plugins=
(
git
zsh-autosuggestions
zsh-syntax-highlighting
)`
had to change it to one line
`plugins=(git zsh-autosuggestions zsh-syntax-highlighting)`

probably some spacing issue happened

**Comment by tsids** [comment]
> ### For people that encounters this issue trying to achieve that on **Linux + terminator** :
> 
> You just have to go to **Preferences** > **Profile** > **Colors** . In sub-menu **Palette** . Then, you must select **Custom** instead of **Solarize Dark** as a built-in themes. Finally, change **the bottom left color** to a lighter one.

Thank you, this worked for me.
I can't believe the autosuggestions were working, but I couldn't see them because of the color :joy:

**Comment by clauBv23** [comment]
> ### ⚠️ Be sure iTerm's "Background" and "ANSI Normal Black" are set to two _distinctly_ different colors!
> > iTerm > Preferences > Profiles > Colors > ANSI Colors > Bright > Black
> > iTerm > Preferences > Profiles > Colors > Basic Colors > Background
> 
> @yuungH4x0r I had the same problem. Turns out I had the autosuggestion color (ANSI Bright Black) set exactly the same as my iTerm background so they blended together perfectly and I just couldn't see it 😅

Oh, damn! 😮‍💨

**Comment by DebOM** [comment]
add this to you ~/.zshrc. It started to work for me once added, even though I had the plugin set correctly
`source $ZSH/oh-my-zsh.sh`

**Comment by dominikabieder** [comment]
I'm getting 'zsh-autosuggestions' not found and 'zsh-syntax-highlighting' not found even though they are working.

I can only download the zip, I put it in .zsh folder, then added the plugins and at the end `source $ZSH/oh-my-zsh.sh` - without it it wouldn't show the branch name.

What can I improve? I can't git clone, the antigen also didn't work despite installing it with brew.

```
plugins=(
  git 
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source ~/.zsh/zsh-autosuggestions-master/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting-master/zsh-syntax-highlighting.zsh

source $ZSH/oh-my-zsh.sh
```

**Comment by gnsalok** [comment]
### Please validate  below points to fix `zsh-autosuggestions`

1. Make sure you do not define `plugins=()` twice in `~/.zshrc` file. Sometimes while installing `Oh My Zsh` and  `Powerlevel10k`, `plugins=(git)` automatically gets added, and you end up getting added it twice.
2. In `~/.zshrc` file, `plugins=(git)` line should come before `source $ZSH/oh-my-zsh.sh`. 

If you mess up with step 2, you will end up debugging for hours.

**Comment by manjushsh** [comment]
> for me the problem was simply wrong order of commands in .zshrc
> 
> this line: `plugins=(git z colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)`
> 
> was AFTER this line: `source $ZSH/oh-my-zsh.sh`
> 
> I just swapped them and after that all plugins were loaded correctly. (no need for manual sourcing of plugins)

Thank you. It worked!

**Comment by DavydovDenys** [comment]
All you need is to have **only one line** `plugins=(git zsh-autosuggestions zsh-syntax-highlighting)`
In my case, I had 2 lines
`plugins=(git zsh-autosuggestions zsh-syntax-highlighting)`
`plugins=(git ssh)`
I just added `git ssh` to `plugins=(git ssh zsh-autosuggestions zsh-syntax-highlighting)` and remove the last line 
`plugins=(git ssh)` and this worked for me.

**Comment by hoangneeee** [comment]
> for me the problem was simply wrong order of commands in .zshrc
> 
> this line: `plugins=(git z colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)`
> 
> was AFTER this line: `source $ZSH/oh-my-zsh.sh`
> 
> I just swapped them and after that all plugins were loaded correctly. (no need for manual sourcing of plugins)

thank you, it helps me

**Comment by nhlong108** [comment]
> ource .oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

You are my hero!!

**Comment by sunwhw** [comment]
1. vim ~/.zshrc
2. only add "source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions", no "plugins"! 
3. source ~.zshrc
it works for me!

**Comment by FahimFBA** [comment]
I followed the issue on macOS Sonoma like below:

1. Ran this: `git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions` to clone and save them in the zsh's plugin's directory.
2. Opened the config using `open ~/.zshrc`
3. Changed `plugins=(git)` to `plugins=(git zsh-autosuggestions)`
4. Reloaded the config using `source ~/.zshrc`

It worked flawlessly!

**Comment by FaizanNoor** [comment]
```
cdc $HOME

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

source ~/.zshrc
```

**Comment by FaizanNoor** [comment]
```
cd $HOME

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

source ~/.zshrc
```
