### ISSUE TITLE
`gem push TAB` raises error

### ISSUE THREAD

**Issue by mehdisadeghi** [zsh-users/zsh-autosuggestions#423]
I get the following error when typing `gem push` with a tab following:

```
_arguments:comparguments:325: doubled rest argument definition: *:gem:_files -g "*.gem(-.)"
```

`gem + TAB` works fine. I'm not sure whether this is a bug, filing anyway since this may be someone else's problem too.

**Comment by z0rc** [comment]
This issue isn't related to zsh-autosuggestions. Probably it's issue with oh-my-zsh or other zsh configuration framework you're using.

**Comment by mehdisadeghi** [comment]
@z0rc yes, I'm using oh-my-zsh. Feel free to close if this is irrelevant for this project.
