### ISSUE TITLE
only add command if it was successful

### ISSUE THREAD

**Issue by theonlygusti** [zsh-users/zsh-autosuggestions#424]
don't add commands from the history that didn't complete successfully

**Comment by ericfreese** [comment]
This is actually pretty tricky and not often what you really want. Furthermore, this plugin doesn’t currently have any opinions about what is stored in your history and I don’t think that should change. I’d prefer that anyone who wants this behavior implements it in their own local config.

FWIW I think zsh-histdb does store exit code so you could likely implement a custom suggestion strategy to filter only those entries that succeeded when they were run.

For more info see:

- https://unix.stackexchange.com/questions/41739/keep-only-successful-commands-in-bash-history
- https://superuser.com/questions/902241/how-to-make-zsh-not-store-failed-command
- https://github.com/larkery/zsh-histdb

**Comment by Haikyy** [comment]
Yes, you're right, it's better to not spread more the behaviour, I didn't think about changing this config from somewhere else out of this plugin.
