### ISSUE TITLE
turn off for some commands

### ISSUE THREAD

**Issue by theonlygusti** [zsh-users/zsh-autosuggestions#425]
I don't want zsh autosuggestions for commands like `youtube-dl` (I don't want it to suggest me a url that already downloaded).

I find the auto-filling of a url distracting and unclean.

**Comment by ericfreese** [comment]
Hi, can you please add some more context to this bug report or feature request? It’s hard for me to understand from an incomplete sentence alone.

**Comment by theonlygusti** [comment]
@ericfreese yes you're right, sorry about that. I edited the first post.

**Comment by ericfreese** [comment]
Do you want to keep these long commands in your history? If the command is not in history, it won't be suggested by this plugin.

You can use `HISTORY_IGNORE` param or fiddle with the `zshaddhistory` hook to control what is saved to history. See this thread on the mailing list: http://www.zsh.org/mla/users/2015/msg00147.html

You might also be interested in [`histignorespace` option](https://unix.stackexchange.com/a/48306/156673) that allows you to prefix a command with a space to omit it from history.  And here's some more info including removing existing history entries: https://stackoverflow.com/a/13661794/154703

**Comment by JonnyHaystack** [comment]
Hm, that certainly helps, but it's hard to cover every case of long commands that I might write

**Comment by ericfreese** [comment]
@theonlygusti Please try `features/history-ignore` branch (PR #456). I have yet to write tests, but I think it will work for your use case.

Say that you don't want suggestions for `youtube-dl` or e.g. `curl`:

```sh
ZSH_AUTOSUGGEST_HISTORY_IGNORE="(youtube-dl *|curl *)"
```

**Comment by ericfreese** [comment]
Merged to `develop`. Will go out with the next release.
