### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by cup** [zsh-users/zsh-autosuggestions#427]
Manjaro uses this repo out of the box. I would like to totally disable it.

For a permanent basis I believe I can simply remove the appropriate line from
`~/.zshrc`.

However can it be disabled for just the current session?

**Comment by ericfreese** [comment]
Yes, check out the `autosuggest-disable` widget.

https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#key-bindings

**Comment by cup** [comment]
@ericfreese thanks for fast response

However do i really need to create a keybinding just for this purpose? I would prefer simply a shell command similar to

~~~
$ disable bad thing
bad thing disabled!
~~~

**Comment by ericfreese** [comment]
You can call the function directly with `_zsh_autosuggest_disable`. It’s a “private” function (prefixed with underscore) so it’s always possible it may change without warning but probably won’t realistically.
