### ISSUE TITLE
Feature Request: max length of suggestions to show

### ISSUE THREAD

**Issue by JonnyHaystack** [zsh-users/zsh-autosuggestions#429]
It would be nice to have an option called e.g. `ZSH_AUTOSUGGEST_SUGGESTION_MAX_SIZE` or similar which limits the length of suggestions that can be shown.

I've had to `mv` some files with long path names and now every time I type mv I get a massive suggestion spanning more than the width of my 1080p monitor which I don't really want.

If we could limit the length of suggestions shown as well as being able to limit the buffer size for which to show suggestions that would be very helpful.

**Comment by ericfreese** [comment]
You may be interested in omitting those long `mv` commands from history. If you do, they won't be suggested by this plugin. Take a look at my comment here: https://github.com/zsh-users/zsh-autosuggestions/issues/425#issuecomment-492933081

**Comment by her** [comment]
Sorry am confused here, isn't this what you're looking for @JonnyHaystack 

https://github.com/zsh-users/zsh-autosuggestions#disabling-suggestion-for-large-buffers

<img width="905" alt="Screen Shot 2019-06-07 at 6 26 06 PM" src="https://user-images.githubusercontent.com/10278096/59140444-2bff8380-8952-11e9-97bb-4cf16b10ab05.png">

**Comment by JonnyHaystack** [comment]
@her I believe that is based on the length of the text currently on the command line, not the length of the history items

**Comment by JonnyHaystack** [comment]
Oh also I think I meant to post [this comment](https://github.com/zsh-users/zsh-autosuggestions/issues/425#issuecomment-495358045) on this issue instead

**Comment by her** [comment]
@JonnyHaystack that makes sense. Maybe the change is pretty straightforward, @ericfreese any suggestions on where to poke around in the code first? Perhaps a spec that tests around this type of functionality to maybe get started? 

I know I'm personally worried about performance edge cases where a long line of text grinds things to a halt, but I've not experienced it yet. I can sometimes end up with fantastically long `$ curl <foo>` commands in my history and I love having them there :)

**Comment by ericfreese** [comment]
> any suggestions on where to poke around in the code first? Perhaps a spec that tests around this type of functionality to maybe get started?

Sure, a spec sounds like a good place to start. I'd put it under https://github.com/zsh-users/zsh-autosuggestions/tree/master/spec/options/

A brute force way to implement would be to make the change in [`src/fetch.zsh`](https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/fetch.zsh#L20). Something along the lines of:

```sh
[[ $#suggestion > $ZSH_AUTOSUGGEST_MAX_SUGGESTION_LENGTH ]] && unset $suggestion
```

Though that wouldn't be smart enough to give you the most recent command you ran that is under the length limit (if the last command you ran was too long, it would give you no suggestion at all). For that you'd need to get into modifying each suggestion strategy, which will get complicated, especially for completion strategy, which is pretty hard coded to only return the first completion result.

**Comment by ericfreese** [comment]
@JonnyHaystack @her Please try `features/history-ignore` branch (PR #456). I have yet to write tests, but I think it will work for your use case.

Say that you don't want suggestions for anything 50 chars or over:

```sh
ZSH_AUTOSUGGEST_HISTORY_IGNORE="?(#c50,)"
```

See docs for `cN,M` globbing flag: http://zsh.sourceforge.net/Doc/Release/Expansion.html#Globbing-Flags

**Comment by JonnyHaystack** [comment]
Awesome, I'll give it a try later, thanks!

**Comment by ericfreese** [comment]
Merged to `develop`. Will go out with the next release.

**Comment by JonnyHaystack** [comment]
Seems to work perfectly, thank you! :smiley:
