### ISSUE TITLE
Highlight not applied when zle-line-init modifies BUFFER

### ISSUE THREAD

**Issue by romkatv** [zsh-users/zsh-autosuggestions#431]
Short version. zsh-syntax-highlighting wraps `zle-line-init` but zsh-autosuggestions doesn't. Thus, if `zle-line-init` modifies `BUFFER`, zsh-autosuggestions won't apply its highlighting to `POSTDISPLAY`, which will make it appear as if `POSTDISPLAY` was a part of `BUFFER`.

Why am I modifying `BUFFER` in `zle-line-init`? I'm using something like https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dirhistory but my version doesn't clear `BUFFER` when I'm changing directories. Here's a simplified example that allows me to execute `cd ..` when pressing `Ctrl-U` without clearing `BUFFER`.

```zsh
function cd-up() {
  cd ..
  saved_buffer=$BUFFER
  saved_cursor=$CURSOR
  BUFFER=
  zle accept-line
}

function restore-buffer() {
  BUFFER=$saved_buffer
  CURSOR=$saved_cursor
  saved_buffer=
  saved_cursor=1
}

zle -N cd-up
zle -N restore-buffer

autoload -Uz add-zle-hook-widget
add-zle-hook-widget line-init restore-buffer

bindkey "^U" cd-up
```

Note that zsh-autosuggestions wraps `cd-up` widget and adds highlighting after it modifies `BUFFER` but unfortunately this is not enough. The wrapper code for `zle-line-init` in zsh-syntax-highlighting runs afterwards and resets the highlighting.

Wrapping `zle-line-init` in zsh-autosuggestions fixes this issue but unfortunately there is no option to do it. Currently I'm using this hack:

```zsh
functions[orig_zsh_autosuggest_bind_widgets]=$functions[_zsh_autosuggest_bind_widgets]
function _zsh_autosuggest_bind_widgets() {
  orig_zsh_autosuggest_bind_widgets
  _zsh_autosuggest_bind_widget zle-line-init modify
}
```

You can see how it looks without and with the hack in https://asciinema.org/a/iU6zszJucHfbqVyr6sNSMuSDT?t=21. This records the following:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  cd
  apt update && apt install -y zsh git
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
  git clone https://github.com/zsh-users/zsh-autosuggestions.git
  echo >~/.zshrc "
    function cd-up() {
      cd ..
      saved_buffer=\$BUFFER
      saved_cursor=\$CURSOR
      BUFFER=
      zle accept-line
    }

    function restore-buffer() {
      BUFFER=\$saved_buffer
      CURSOR=\$saved_cursor
      saved_buffer=
      saved_cursor=1
    }

    zle -N cd-up
    zle -N restore-buffer
    
    autoload -Uz add-zle-hook-widget
    add-zle-hook-widget line-init restore-buffer

    bindkey \"^U\" cd-up

    source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
    source ~/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
    
    PROMPT=\"%/%# \"
    print -s echo hello world
    cd ~/zsh-syntax-highlighting/highlighters/root"
  exec zsh'
```

Then type `echo hello` and press `Ctrl-U` a few times. Observe that `hello` and `world` have identical highlighting. Press `Enter` and observe that only `hello` is printed.

Then add the hack:

```zsh
echo >>~/.zshrc '
  functions[orig_zsh_autosuggest_bind_widgets]=$functions[_zsh_autosuggest_bind_widgets]
  function _zsh_autosuggest_bind_widgets() {
    orig_zsh_autosuggest_bind_widgets
    _zsh_autosuggest_bind_widget zle-line-init modify
  }'
exec zsh
```

Once again type `echo hello` and press `Ctrl-U` a few times. Observe that `world` is greyed out as it should be.

So, could you add an option to wrap `zle-line-init`? Or maybe there is another way to achieve what I need?

**Comment by ericfreese** [comment]
Thank you for providing so many details :smile:

It looks like `zle reset-prompt` may work for you. See this implementation of `cd-up`: https://stackoverflow.com/a/10257511/154703

It worked for me running the following

```
% zsh -f
%% PROMPT="%d > "
%% cd-up() { cd ..; zle reset-prompt }
%% zle -N cd-up
%% bindkey ^U cd-up
%% source zsh-autosuggestions.zsh
```


Though I think we can probably remove ignoring behavior of zle-line-* anyway. Looks like it was originally added because I was doing [some deprecation warnings on zle-line-init](https://github.com/zsh-users/zsh-autosuggestions/commit/9788c2ee49737e3ca413416f74687b8624eddd61) and all that deprecation stuff has since been removed.

**Comment by romkatv** [comment]
> It looks like zle reset-prompt may work for you.

It'll work only for static prompts. That is, when the value of `PROMPT` doesn't change. Most ZSH themes, including [the one I'm using](https://github.com/romkatv/dotfiles-public/blob/master/.purepower), hook `precmd` and/or `preexec` and modify `PROMPT` or variables referenced by it in there. Here's a simple example:

```zsh
function set-prompt() { PROMPT=${(%):-%/%# } }
setopt noprompt{bang,percent,subst} prompt{cr,sp}
autoload -Uz add-zsh-hook
add-zsh-hook precmd set-prompt
```

(It's the same prompt as above but generated dynamically on every command.)

`zle reset-prompt` isn't enough to update such prompt after a directory change. To render a correct prompt in the new directory requires triggering all hooks that the theme relies on. The most portable way to do that is via `zle accept-line`.

> I think we can probably remove ignoring behavior of zle-line-*

That would be great!

**Comment by ericfreese** [comment]
Ok @romkatv I've pushed up `features/wrap-zle-line-init` branch. Please check it out and let me know what you think.

https://github.com/zsh-users/zsh-autosuggestions/pull/432

**Comment by ericfreese** [comment]
Merged to develop.

To enable wrapping of `zle-line-init`, remove `zle-\*` from `ZSH_AUTOSUGGEST_IGNORE_WIDGETS` and add `zle-\^line-init` (requires `extendedglob` option to be set).

```sh
ZSH_AUTOSUGGEST_IGNORE_WIDGETS=(${(@)ZSH_AUTOSUGGEST_IGNORE_WIDGETS:#zle-\*} zle-\^line-init)
```
