### ISSUE TITLE
Flawed TERM messes up this plugin

### ISSUE THREAD

**Issue by NightMachinary** [zsh-users/zsh-autosuggestions#435]
I suggest emitting some warning so that the user understands what is wrong. (To reproduce, just set TERM to some nonsense.)

**Comment by ericfreese** [comment]
Hi, I'm not immediately able to reproduce this using the following:

```
% zsh -df
ericfreese% export TERM=aldfasdflj
zsh: can't find terminal definition for aldfasdflj
ericfreese% source path/to/zsh-autosuggestions.zsh
```

Please give some more info:

- Can you reproduce with `zsh -df` and sourcing the plugin manually (see steps above)?
- What version of zsh are you using?
- What operating system?
- What terminal emulator?

**Comment by NightMachinary** [comment]
I reproduced this on another VPS by the following steps:
1. zsh -df
2. set TERM
3. Source the plugin
4. Type some echos
5. Repeat the steps above.

The nested zsh -df shows the messed up behavior, though it is less annoying
with the default prompt.

zsh 5.5.1 (though the zsh on the other VPS was the latest installed by
Homebrew on that same day, 5.7 I think?)

Ubuntu 18

Emulator: Blink (iOS)

**Comment by ericfreese** [comment]
Ok, I've reproduced this.

Is there some way that this could be broken for someone without them intentionally setting TERM to nonsense?

**Comment by NightMachinary** [comment]
Well, yes, otherwise you wouldn’t be seeing this report.
Sometimes the host TERM is not defined in the sshed system.

**Comment by z0rc** [comment]
Honestly I would call this an issue outside of zsh-asug scope. Garbage in $TERM will break more than zsh-asug. Also all default ssh configurations pass $TERM to remote hosts, otherwise remote shell session won't be able to properly communicate colors or anything more complex terminal wise. So I assume you deliberately changed $TERM on your local host or your ssh configuration and have to be ready to deal with consequences.

**Comment by NightMachinary** [comment]
I’m just saying emitting a warning that TERM is set incorrectly will help
people.  It’s probably just 3 lines of code?

**Comment by z0rc** [comment]
Again, I don't think that TERM validation should be a z-asug scope.

Also validation of $TERM won't be nearly close as 3 lines of code. First we have to check that $TERM definition actually available on disk under known paths, second actually verify that $TERM definition is actually usable, probably via infocmp. Also context should be somehow taken in account, for example tmux is running, what should be considered a valid/invalid $TERM: xterm, xterm-256color, screen etc?

Honestly this should be a part of your dotfiles, if you really need it. But given amount of effort required to validate $TERM, it's just simpler to fix in place once you notice issues.

**Comment by NightMachinary** [comment]
You’re right then. Feel free to close the issue.
