### ISSUE TITLE
how to bind ALT/ENTER/TAB to shortcut key?

### ISSUE THREAD

**Issue by magicsunny** [zsh-users/zsh-autosuggestions#436]
how to bind ALT/ENTER/TAB to shortcut key?
I know ^ is represented for CTRL

**Comment by ericfreese** [comment]
In zsh type `bindkey ‘` then press ctrl+v and the keystroke you want to bind. Then close the quote and add the widget you want to bind to `’ some-widget`

**Comment by magicsunny** [comment]
Thanks!

Eric Freese <notifications@github.com> 于2019年6月13日周四 下午2:29写道：
