### ISSUE TITLE
Breaks copy-earlier-word

### ISSUE THREAD

**Issue by henrebotha** [zsh-users/zsh-autosuggestions#437]
# Steps taken

1. Add to `~/.zshrc`: ```autoload -Uz copy-earlier-word; zle -N copy-earlier-word; bindkey '^N' copy-earlier-word```.
2. Source `~/.zshrc`.
3. Type `foo bar baz ` (note the trailing space).
4. Press <kbd>^</kbd><kbd>N</kbd> multiple times.

# Observed result

The words produced are `baz`, `baz`, `bar` in that order, repeating with further keypresses.

# Expected result

The words produced are `baz`, `bar`, `foo`, and an empty string, in that order, with no repetitions upon further keypresses.

# Environment

I have observed this in Zsh 5.5.1 and 5.7.1, both using Tmux and not using Tmux, under xfce4-terminal 0.8.7.4 on Xubuntu 18.10. I have observed this with zsh-autosuggestions at `70f36c0` and `733abd4`.

I have tried multiple versions of Zsh config (e.g. with and without vi-style bindings), and observed the error in all of them.

**Comment by ericfreese** [comment]
Fixed on develop, see #439
