### ISSUE TITLE
Feature Request: use clipboard for suggestions in certain cases

### ISSUE THREAD

**Issue by Kraymer** [zsh-users/zsh-autosuggestions#455]
I have frequent cases in my workflow where I never use current suggestions : when I want to revert/cherry-pick a commit I usually put the commit hash in my clipboard first then `git revert` ... it would make sense to suggest here the hash which is in my clipboard.

Feel free to close the issue if it is outside of the scope of the plugin (as _"It suggests commands based on history and completions."_)

**Comment by ericfreese** [comment]
I think the tricky part here would be determining when to offer the clipboard selection. For example, if you type just `git `, you wouldn't want it to suggest `git 146020d` (or whatever you had in your clipboard). Do you have some thoughts on how that would work?

**Comment by Kraymer** [comment]
Sure, I can give a try.

The plugin would have to _learn_ user habits, by storing in an internal database what strings are usually followed by clipboard content.

Naive implementation in pseudo code : 

~~~
CLIPBOARD_BIN='xsel'
CLIPBOARD_CONTENT=`xsel -ob`

on_command_entered(last_command):
    if len(CLIPBOARD_CONTENT) > MIN_LENGTH:
        if regex('\b' $CLIPBOARD_CONTENT '\b') in last_command:
            prefix, clipboard, _ = last_command.split_at($CLIPBOARD_CONTENT)

            # Keep a track if clipboard was used for that command on disk : in sqlite or something  
            sqlite.write(command, 'use_clipboard', +1)
        else:
            sqlite.write(command, 'no_use_clipboard', 1)
    else:
        sqlite.write(command, 'no_use_clipboard', 1)


on_command_completion(prompt):
    if sqlite.get_ratio(command, 'use_clipboard') > .75:
        completion = $CLIPBOARD_CONTENT
~~~

**Comment by ericfreese** [comment]
Thanks @Kraymer, this looks like it would be a pretty significant effort! I think a good first step would be for you (or someone else interested in having this feature) to create a custom suggestion strategy in your own local environment. Then we can see how it might look generalized for all users and try to fit it in here.

The custom suggestion strategy API is pretty simple. You just define a shell function with a special name and then refer to it in `ZSH_AUTOSUGGEST_STRATEGY`. The shell function will receive the current buffer as `$1` and should set the global param `suggestion` to the suggestion that it wants to make. The suggestion needs to begin with the buffer contents `$1` or it will not be shown.

For example, this defines a strategy `always-add-foo` that, regardless of buffer contents, suggests that you add " foo" to the end.

```sh
_zsh_autosuggest_strategy_always-add-foo() {
	typeset -g suggestion="$1 foo"
}
```

... and in your .zshrc:

```sh
ZSH_AUTOSUGGEST_STRATEGY=(always-add-foo)
```

See the [built-in strategies](https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/strategies/) for more inspiration. `zsh-histdb` also has some sample suggestion strategies here: https://github.com/larkery/zsh-histdb#integration-with-zsh-autosuggestions

**Comment by Kraymer** [comment]
Thanks @ericfreese for such a comprehensive reply, I felt obliged to try on my environment : 

~~~
_zsh_autosuggest_strategy_always-add-foo() {
    if [[ $1 == "git cherry-pick"* || \
        $1 == "git revert"* || \
        $1 == "git blame"* ]]; then    
        local CLIPBOARD_CONTENT=`xsel --clipboard --output`
        # If we have a SHA1 commit hash in clipboard then suggest it
        if [ ${#CLIPBOARD_CONTENT} -ge 6 ] && [ $CLIPBOARD_CONTENT =~ ^[0-9a-f]{5,40}$ ]]; then
 	        typeset -g suggestion="$1 $CLIPBOARD_CONTENT"
    fi
}
~~~

Sadly `xsel` crashes when called from this autosuggest hook :  

~~~
$ git blamexsel: fstat error on stdin: Bad file descriptor
$
$ # but xsel works correctly when called in the terminal :  
$  xsel --clipboard --output
foobar%
~~~

I googled for the problem, some pages led to zsh plugin `history-substring-search` as a possible culprit, so I disabled all my plugins but `zsh-autosuggestions`, to no avail.

I have no idea how to advance on that implementation so I leave it there, hoping someone can fix it !

**Comment by NightMachinary** [comment]
@Kraymer Try https://copyq.readthedocs.io instead of xsel, it might work.
You can use these functions to copy and paste:
```
        copyq copy -- "sth"

        copyq clipboard
```

**Comment by Billy-** [comment]
>I think the tricky part here would be determining when to offer the clipboard selection

Why not always? 😁 

The user can order which suggestion strategy gets called first, right? So this one would usually go last, and just offer up whatever is in your clipboard as a last resort 😄
