### ISSUE TITLE
Everytime I create a new terminal, I have to source ~/.zshrc to let the autosuggestion to come into the effect

### ISSUE THREAD

**Issue by PianoSea** [zsh-users/zsh-autosuggestions#460]
### Describe the bug
I have put the following code into my ~/.zshrc. 
```
source /usr/local/share/antigen/antigen.zsh
antigen bundle zsh-users/zsh-autosuggestions

```

### To Reproduce
Steps to reproduce the behavior:SG
Every time I press the COMMAND + T to new a terminal , I have to run the source ~/.zshrc, 

```sh
% zsh -df
% source path/to/zsh-autosuggestions.zsh
% ... # what do you do to reproduce?
```

### Desktop
 - OS + distribution: 
 - Zsh version: 
 - Plugin version:

**Comment by ericfreese** [comment]
This feels like it may be an issue with either antigen or the way you have antigen set up. Have you tried other methods of installing the plugin?

https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md

**Comment by recursiveElk** [comment]
I get this when installing with oh-my-zsh

**Comment by ericfreese** [comment]
@recursiveElk maybe this could be helpful? https://stackoverflow.com/questions/50689939/why-do-i-need-to-source-zshrc-for-every-new-shell-in-iterm2

**Comment by recursiveElk** [comment]
@ericfreese Thanks for this, newbie mistake!

**Comment by PianoSea** [comment]
Hi guys, Thanks all for your help.  Instead of using the antigen package management tool , I changed my strategy to another way showing in the official website with the configuration as follows: 
```
plugins=(
git
docker
zsh-syntax-highlighting
zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh
```

----------------
and I git clone it from the command line on the official website:

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions



Thank you again for your favors.
