### ISSUE TITLE
Every time a new window or tab column is opened,plugin's function falis

### ISSUE THREAD

**Issue by lovelyJason** [zsh-users/zsh-autosuggestions#464]
Hello,I found a problem.When I open a new window or a new tab column,my zsh has not suggestions on shell.Unless I executed an order: source ~/.zshrc

Why?How can I resolve this problem.I can't find the answer from google and baidu
![Snipaste_2019-08-01_15-55-00](https://user-images.githubusercontent.com/50656459/62275871-6f1f3400-b475-11e9-843e-f52aa044e720.png)
![Snipaste_2019-08-01_15-55-51](https://user-images.githubusercontent.com/50656459/62275882-734b5180-b475-11e9-93c9-a8f57bd6c37d.png)

**Comment by katernet** [comment]
Same for me. Basically suggestions don't show on the first prompt when first launching the shell or a new tab/window.

An easier way to get it working is to simply hit enter. Suggestions will work for me on the second prompt.

Latest zsh-autosuggestions, macOS, iTerm and my config is in my [dotfiles](https://github.com/katernet/dotfiles) repo.

**Comment by ericfreese** [comment]
@lovelyJason this might be helpful for you: https://github.com/zsh-users/zsh-autosuggestions/issues/460#issuecomment-511499844
