### ISSUE TITLE
Cannot change highlight color

### ISSUE THREAD

**Issue by wsw70** [zsh-users/zsh-autosuggestions#466]
### Describe the bug

Cannot change highlight color

### To Reproduce

- set `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` in `~/.zshrc`

```
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=gray"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#DCDCDC"
```
(two mutually exclusive examples - only one of them is used at one time)

- open new terminal
- the autosuggestion is the same color as the already-typed characters

### Expected behavior

Suggested characters hould be gray (in the examples above)

### Screenshots

Example of a `ls` to show that colors are rendered

![image](https://user-images.githubusercontent.com/1345886/62551466-5a271400-b86c-11e9-8e44-792086e3a32e.png)

Example of suggestion 

![image](https://user-images.githubusercontent.com/1345886/62551538-79be3c80-b86c-11e9-8834-fa9d017d173e.png)

### Desktop
 - Server: Ubuntu 18.04 LTS
 - Termianl to connect to the server: Mobaxterm on Windows 10
 - Zsh version: 5.4.2
 - Plugin version: 43f3bc4010b2c697d2252fdd8b36a577ea125881 (Jul 15, 2019) - the most current as of the date of this report.

### Additional context

The suggestion works correctly, the problem is just with the color.

**Comment by ericfreese** [comment]
Hi, I wonder if your terminal doesn’t support more than 8 colors. Try setting the highlight style variable to a number less than 8.

**Comment by wsw70** [comment]
@ericfreese thank you for the suggestion. My terminal is advertised as `xterm-256colors` but apparently this is false advertising :)

I changed `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` to `fg=2` and an ugly greenish color is used for the suggestions. This means your plugin works and my terminal does not.

Sorry for the noise, I will investigate that side (and thank you for the plugin: I switched today from `fish` to `zsh` and what you wrote was what i was mostly missing from `fish`)

**Comment by wsw70** [comment]
@ericfreese as a side note, it looks like http://www.ericfreese.com/ does not work

**Comment by ericfreese** [comment]
Glad I could help :) yes maybe someday I’ll get around to getting that back up

**Comment by LeonardAB** [comment]
@wsw70 yes it is advertised as `xterm-256colors` but to use it you have to change your session setting
![image](https://user-images.githubusercontent.com/14308605/105496489-e0eddc00-5d00-11eb-9724-ccbd1cba3cf8.png)
