### ISSUE TITLE
"completion" strategy: don't try to load new suggestions if prefix failed

### ISSUE THREAD

**Issue by Hi-Angel** [zsh-users/zsh-autosuggestions#467]
### Describe the bug

The strategy, basically, uses same candidates as tab-completion would. But it's clear
that tab-completion for some commands may take long time to complete. For this reason
it makes sense to check whether currently typed prefix failed to return any
candidates, and if it did, do not try to repeat the query for candidates if user
continues typing.

### Steps To Reproduce

1. Enter any git repository, for example:
    ```
    git clone https://github.com/zsh-users/zsh-autosuggestions && cd zsh-autosuggestions
    ```
2. Execute `ZSH_AUTOSUGGEST_STRATEGY=(completion)` to enable the strategy
2. Try to type `git checkout foobarbuzz`

### Expected behavior

There's only once the time lag, the moment when git failed to fetch `foo` as a completion

### Actual behavior

Lags are happening all the time as you type `foobarbuzz`, because for every letter `zsh-autosuggestions` tries to fetch candidates.

### Desktop
 - OS + distribution: Arch Linux 2019.08.01
 - Zsh version: 5.7.1
 - Plugin version: commit 43f3bc4

### Additional context

NB: for writing steps-to-reproduce I didn't use the suggested way with `zsh -df`
because this way autosuggestion doesn't work at all, as in, I set
`ZSH_AUTOSUGGEST_STRATEGY=(history completion)`, but there's no completion as I type.

**Comment by Hi-Angel** [comment]
I also wonder if it makes sense to go even further, and cache the whole list of candidates for the currently typed prefix, so you do not query anymore as user types?

**Comment by Hi-Angel** [comment]
And either way, the cache should only be valid until a whitespace character.

**Comment by ericfreese** [comment]
Thanks for the detailed report. Have you tried using async mode(check readme for details)? I’m thinking it’s about time to enable it by default. There still can be some value in this caching to avoid using too many resources but async may help you in the meantime.

**Comment by Hi-Angel** [comment]
> Thanks for the detailed report. Have you tried using async mode(check readme for details)? I’m thinking it’s about time to enable it by default. There still can be some value in this caching to avoid using too many resources but async may help you in the meantime.

Oh, this is amazing, thank you! I'll definitely gonna use it.

**Comment by Hi-Angel** [comment]
@ericfreese have it been implemented?
