### ISSUE TITLE
Doesn't suggest history from other sessions

### ISSUE THREAD

**Issue by NightMachinary** [zsh-users/zsh-autosuggestions#468]
If I open two terminals, and type `echo 986` into the first, this line will not be suggested to me in the second terminal. I am using the history options that make history shareable between sessions, as can be confirmed from the fact that when I use my fzf history completer, this line is present in the second session:
![image](https://user-images.githubusercontent.com/36224762/63454397-ff8eda00-c45f-11e9-9e1c-6e8f0c9030d3.png)

**Comment by ericfreese** [comment]
Have you seen #371? Did any of the possible workarounds there help?

**Comment by NightMachinary** [comment]
@ericfreese It’s indeed the same issue, thanks. I’m closing this.
