### ISSUE TITLE
Autocompletes only one charachter in St

### ISSUE THREAD

**Issue by waltsims** [zsh-users/zsh-autosuggestions#469]
### Describe the bug
ZSH only autocompletes one character when used with st terminal emulator.

### To Reproduce
In St terminal emulator with the default config from regolith-linux, the autocomplete only works for the character under the cursor. With the gnome-terminal on the same machine the plugin works.

### Expected behavior
I expect the behaviour between st and gnome-terminal to be the same.

### Screenshots
![Screenshot from 2019-08-28 10-03-46](https://user-images.githubusercontent.com/8669206/63837180-4490a000-c97b-11e9-9257-86ccfc0a5fd7.png)

### Desktop
 - VERSION="19.04 (Disco Dingo)" Regolith-Linux-Desktop
 - zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
 - commit 43f3bc4010b2c697d2252fdd8b36a577ea125881

**Comment by waltsims** [comment]
seems to be related to https://github.com/regolith-linux/regolith-st/issues/1

**Comment by waltsims** [comment]
moved to https://github.com/regolith-linux/regolith-st/issues/5

**Comment by waltsims** [comment]
Still looking for help on this front. Will re-open here.

**Comment by z0rc** [comment]
#288, #272, #262.

**Comment by waltsims** [comment]
> #288, #272, #262.

#262 helped. Thank you.
