### ISSUE TITLE
oh-my-zsh plugin

### ISSUE THREAD

**Issue by SimenB** [zsh-users/zsh-autosuggestions#47]
Hey!

I was wondering if it was possible to add this to the oh-my-zsh plugins?

I know absolutely nothing about how zsh works, but if someone can point me in the right direction, I'm sure I could throw together a PR for oh-my-zsh if you don't mind.

Can history-substring-search be used as inspiration?
https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/history-substring-search

**Comment by dd1994** [comment]
+1 for this

**Comment by faceleg** [comment]
This is possible.

The plugin itself has issues however, which should be fixed before we take steps that would cause further users to be bitten by the current brokenness.

**Comment by Treri** [comment]
I wrote a simple wrap for zsh-autosuggestion, and just put few lines in plugin.

[zsh-autosuggestion-conf](https://github.com/Treri/zsh-autosuggestions-conf/blob/master/zsh-autosuggestions-conf.plugin.zsh)

Now zsh-autosuggestion.plugin.zsh is just a link to autosuggestion.zsh.

Can me make zsh-autosuggestion.plugin.zsh a real file, and add below lines or something like in it?

```sh

source ./zsh-autosuggestions.plugins.zsh

# if you use zsh-autosuggestions plugin, don't delete below lines
# don't highlight word after cursor
export AUTOSUGGESTION_HIGHLIGHT_CURSOR=0
# complete entire suggestion with right arrow
export AUTOSUGGESTION_ACCEPT_RIGHT_ARROW=1
# Enable autosuggestions automatically.
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init
```

**Comment by tik9** [comment]
@faceleg can you explain more about the issues? I use it in Ubuntu 16/10 and have no problems. So why not integrate it with OMZ as plugin ??

**Comment by ericfreese** [comment]
@tik9 that comment was made a long time ago and the issues have since been fixed. I'd be happy if someone wanted to add this to oh-my-zsh but I likely won't be the one to do it since I don't use OMZ.

Probably the right place for this discussion though is over on their repo.

**Comment by tik9** [comment]
Thanks Eric, how can I move the issue over to omz? If I can't do that, I will write to their feature request issues.

**Comment by ericfreese** [comment]
I don't know if there's a way to move github issues from one repo to another. I'd probably just make a new issue over there and link back to here.

**Comment by ericfreese** [comment]
Gonna go ahead and close this. If people have interest in this being in OMZ, please open a ticket/PR on their repo.
