### ISSUE TITLE
bindkey for autosuggest-accept doesn't work in tmux

### ISSUE THREAD

**Issue by sebw** [zsh-users/zsh-autosuggestions#471]
Hi,

I have Ctrl-Space as bindkey for `autosuggest-accept`.

If I start tmux, Ctrl-Space stops working.

If I `source ~/.zshrc`, then the shortcut works.

I'm looking for a way to get the shortcut to work inside a tmux session without manual commands.

Anyone here using both autosuggestions and tmux?

Thanks

**Comment by ericfreese** [comment]
Hi, does it work if you bind ctrl-space to a different widget?

`bindkey '^@' self-insert`

Then press ctrl-space. Does it insert `^@` into the buffer?

**Comment by sebw** [comment]
Apologies, I missed the notification for the answer.

I'm getting the same result with the above bindkey.

`^@` is inserted, then I start tmux and it's no longer working, until I reload zsh config.

**Comment by ericfreese** [comment]
Ok thanks for following up. It sounds like this is just an issue with tmux and doesn’t have much to do with this plugin. I would try googling something like “tmux ctrl space” for further help.

**Comment by simonschmoll** [comment]
I have the same problem and it does not matter what keybindings I assign to `autosuggest-accept`.
Currently, I source the zsh config every time I start a new tmux session. However, I think this not really a good workaround as it slows down startup time.

**Comment by samm81** [comment]
I've figured this out. The problem for me was that I was putting my `bindkey '^\' autosuggest-excute` statement right after `plugins+=(zsh-autosuggestions)` (to keep everything together), which is before the `source $ZSH/oh-my-zsh.sh` line. It seems that `source`ing `oh-my-zsh.sh` somehow overwrites all previous `bindkey` statements (though I still don't know why re-`source`ing temporarily fixes the problem). The solution is to move your `bindkey` statement below the `source $ZSH/oh-my-zsh.sh` line.

**Comment by sebw** [comment]
Thank you so much @samm81, this was indeed the solution!

**Comment by dj1020** [comment]
> I've figured this out. The problem for me was that I was putting my `bindkey '^\' autosuggest-excute` statement right after `plugins+=(zsh-autosuggestions)` (to keep everything together), which is before the `source $ZSH/oh-my-zsh.sh` line. It seems that `source`ing `oh-my-zsh.sh` somehow overwrites all previous `bindkey` statements (though I still don't know why re-`source`ing temporarily fixes the problem). The solution is to move your `bindkey` statement below the `source $ZSH/oh-my-zsh.sh` line.

Thank you!!!

**Comment by schmoelder** [comment]
I know this is kind of an old issue but I'm experiencing the same problem. 

I have the following below the `source $ZSH/oh-my-zsh.sh` section and it does not work. Only when I `source ~/.zshrc` directly.

```
bindkey '^ ' autosuggest-accept
bindkey '^L' forward-word
bindkey '^H' backward-word
```

Any ideas why this could be?

**Comment by NathanielRN** [comment]
> The solution is to move your bindkey statement below the source $ZSH/oh-my-zsh.sh line.

@samm81 thank you!

@ericfreese may I send a PR to add this warning underneath https://github.com/zsh-users/zsh-autosuggestions/blob/85919cd1ffa7d2d5412f6d3fe437ebdbeeec4fc5/README.md?plain=1#L118-L120?
