### ISSUE TITLE
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS ignored in vi-mode

### ISSUE THREAD

**Issue by wallace11** [zsh-users/zsh-autosuggestions#472]
When using vi-mode, no matter what widget is in `ZSH_AUTOSUGGEST_ACCEPT_WIDGETS`, it won't work.

For example:
```sh
$ echo $ZSH_AUTOSUGGEST_ACCEPT_WIDGETS
end-of-line vi-end-of-line vi-add-eol up-line-or-history
$ bindkey | grep end-of-line          
"^E" end-of-line
```

Hitting `Ctrl-e` in insert mode when a suggestion appears won't do anything.

**Comment by ericfreese** [comment]
Hi, when I enable vi-mode I don't see `^E` bound to `end-of-line`.

```sh
% zsh -df
% bindkey -v
% bindkey ^E
"^E" self-insert
```

Can you start from `zsh -df` (to run without sourcing any configs like `~/.zshrc`) and post the exact commands you run to reproduce this issue?

**Comment by wallace11** [comment]
Okay, so I was literally sitting on it for 1 hour trying to reproduce the issue and find a pattern.
Apparently I had an error in my `zshrc`, however I can reproduce it using `up-line-or-history` with the following steps:

```sh
$ zsh -df

$ source zsh-autosuggestions.zsh
$ bindkey -v  # It appears as though it's not really necessary
$ ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(up-line-or-history)
$ bindkey | grep up-line
"^[OA" up-line-or-history
"^[[A" up-line-or-history

# Hitting "^[[A" (Arrow up) won't work

$ bindkey -M viins '^E' up-line-or-history
# Won't work either

$ ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(end-of-line)
$ bindkey -M viins '^E' end-of-line
# Ironically, this works
```

BTW, `^E` in my example above was a custom binding I set in order to demonstrate the problem (which doesn't really matter right now anyway...).

**Comment by ericfreese** [comment]
> ```
> # Hitting "^[[A" (Arrow up) won't work
> ```

I wouldn't necessarily expect that running a widget that totally blows away the buffer contents (like `up-line-or-history` does) would actually be overridden to accept the suggestion. Is this an actual problem for your use case? Maybe we need to add some documentation around which widgets this would work for and which it wouldn't.

> ```
> $ bindkey -M viins '^E' end-of-line
> # Ironically, this works
> ```

Does this mean that your original problem ("Hitting `Ctrl-e` in insert mode when a suggestion appears won't do anything.") is solved?

**Comment by wallace11** [comment]
Alright, I understand your reasoning.
It may be a good idea to just add a word about it in the docs since it was confusing (at least for me).
