### ISSUE TITLE
realloc(): invalid next size

### ISSUE THREAD

**Issue by FeruzOripov** [zsh-users/zsh-autosuggestions#475]
### Describe the bug

When I run `git checkout` and press tab, I am getting error `realloc(): invalid next size` and exits terminal.
### To Reproduce

```sh
% zsh -df
% source path/to/zsh-autosuggestions.zsh
% ... # what do you do to reproduce?
```

### Expected behavior

It should list files when `git checkout` + tab is run
### Desktop
 - OS + distribution: Ubuntu 18.04
 - Zsh version: 5.4.2
 - Plugin version:

**Comment by ericfreese** [comment]
Hi, this doesn’t sound like it’s actually an issue with this plugin, but rather with tab completion.

I don’t know how to solve your problem but I would start by running `zsh -df` and trying to reproduce in that environment. If you can’t reproduce there, it means something in your startup files (.zshrc) is causing the issue. Sequentially comment out sections of your zshrc and retry until you narrow down what exactly is causing it.

**Comment by jonrosner** [comment]
Hi,

I have the exact same issue when running `git checkout` and then hitting tab. I can fix it by commenting out zsh-autosuggestions in my .zshrc
