### ISSUE TITLE
Suggest on empty line

### ISSUE THREAD

**Issue by everdrone** [zsh-users/zsh-autosuggestions#477]
### Is your feature request related to a problem? Please describe.

Autosuggest won't trigger when pressing TAB on a new terminal line

### Describe the solution you'd like

Fish provides suggestions for commands on a new line instead of inserting a `\t` character

Is there an option to enable this?

**Comment by ericfreese** [comment]
It sounds like you’re confusing this plugin with the tab-completion behavior that zsh natively provides.

Have a look at this link for some more info on your particular question: https://unix.stackexchange.com/questions/14230/zsh-tab-completion-on-empty-line/32426
