### ISSUE TITLE
zsh-history-substring-search filtering with an arbitrary token

### ISSUE THREAD

**Issue by yafesdev** [zsh-users/zsh-autosuggestions#479]
I found my self using the `UP` button a lot recently as my current history get's longer and longer. I wished there would be a way of filtering suggestions by typing a word. 

Examples: 

```
python /testfiles/main.py
python /testfiles/write.py
python /testfiles/gui.py
python /testfiles/read.py
```
so the suggestion starts with `read.py` and I need to press the `UP` button 3 times until I get to `main.py`

Basically what I would like to have is to filter my suggestions with token like `main.py`

I'm not to versed in zsh, maybe that function is implemented already, but reading the main page I wasn't able to figure it out.

**Comment by ericfreese** [comment]
Hi @yafesdev, it sounds like you’re looking for the `history-incremental-search-backward` widget. You may also like https://github.com/zsh-users/zsh-history-substring-search.

**Comment by yafesdev** [comment]
@ericfreese Thanks, that was exactly what I was looking for!
