### ISSUE TITLE
Autoseggest for docker image or container id is so slow

### ISSUE THREAD

**Issue by DeepDarkOdyssey** [zsh-users/zsh-autosuggestions#485]
After setting `ZSH_AUTOSUGGEST_STRATEGY=(history completion)`, zsh can actually suggest the existing container id when I typing `docker container rm ...`. But it's so slow, takes a couple of secondes for the terminal to response after I trying to type another character. Is that nomal or something wrong with my zsh setting?
![image](https://user-images.githubusercontent.com/37280638/70597009-301e9d80-1c22-11ea-96ab-3c833f57a9b2.png)

**Comment by ericfreese** [comment]
Try enabling asynchronous mode: https://github.com/zsh-users/zsh-autosuggestions#enable-asynchronous-mode

**Comment by DeepDarkOdyssey** [comment]
Thanks @ericfreese , it works like a charm!
