### ISSUE TITLE
Autosuggest still completes on right arrow after incompatible paste

### ISSUE THREAD

**Issue by janosh** [zsh-users/zsh-autosuggestions#489]
### Describe the bug
Autosuggest doesn't update after paste.

### To Reproduce
**Example**: If I start typing `brew install` it suggests completing to `brew install black`. If I then paste `flake8` and press the right arrow key, it still completes to `brew install flake8black`.

This does not occur if I comment out the line

```sh
source $ZSH/oh-my-zsh.sh
```

in my `.zshrc`.

### Expected behavior
Nothing happening on right arrow after paste if the completion shown prior to pasting does not include the pasted text.

### Desktop
 - OS + distribution: macOS 10.15.2
 - Zsh version: 5.7.1
 - Plugin version: 0.6.3

**Comment by ericfreese** [comment]
This looks like a duplicate of #351.

**Comment by janosh** [comment]
You're right! Somehow I missed that issue. Adding

```sh
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(bracketed-paste)
```

to my `.zshrc` solved the issue. Just out of curiosity, [is this still low priority](https://github.com/zsh-users/zsh-autosuggestions/issues/351#issuecomment-483373656)?
