### ISSUE TITLE
New version release possible? (with history ignoring option etc)

### ISSUE THREAD

**Issue by aldanor** [zsh-users/zsh-autosuggestions#493]
Hi and apologies for the noise. I was wondering if it was possible to have a release anytime soon, so that downstream frameworks like prezto could be updated to a most recent tag?

On a related note, one of the most useful features that has been added recently is `ZSH_AUTOSUGGEST_HISTORY_IGNORE` which only exists in develop branch but not master. Would it be possible to sync that as well? (or are there any concerns preventing that?)

Thanks in advance!

**Comment by ericfreese** [comment]
Thanks for bringing this up. I will get a release together in the next few days 👍

**Comment by ericfreese** [comment]
Ok just released `v0.6.4`
