### ISSUE TITLE
Prohibitively slow after typing "."

### ISSUE THREAD

**Issue by mnpenner** [zsh-users/zsh-autosuggestions#499]
### Describe the bug
When I try to type something like `. ./.env` my terminal becomes practically unresponsive. Everything else is reasonably fast. Here's video proof: https://mpen.xyz/share/2020/01/2020-01-20_14-06-06.mp4

### To Reproduce
I tried w/ 

```
 % zsh -df
MARK-DESKTOP% source ~/.zplug/repos/zsh-users/zsh-autosuggestions
```

But I don't get suggestions at all if I load the plugin this way so I dunno. It's fast when I comment out this plugin from my `~/.zshrc` and then slow when I enable it.

### Expected behavior
Faaaaaaaaaaaaast

### Screenshots
Video in description.

### Desktop
 - OS + distribution: Ubuntu 18.04.2 LTS under WSL
 - Zsh version: 5.4.2
 - Plugin version: Dunno. How do I get this? Installed w/ `zplugin light zsh-users/zsh-autosuggestions`

### Additional context

Nada.

**Edit:** Just found the `ZSH_AUTOSUGGEST_USE_ASYNC=1` option. That makes it a bajillion times faster. Coolbeans!

Also, thanks for making this plugin. It's great!

**Comment by ericfreese** [comment]
I wonder if you’re also using the `completion` strategy without async mode? If so, see #497 #485 #498

**Comment by ericfreese** [comment]
Oh haha sorry I just saw your edit right after submitting that :) Going to go ahead and close this with the hopes that #498 will solve it for others coming across the problem.
