### ISSUE TITLE
More documentation for glob patterns

### ISSUE THREAD

**Issue by klieret** [zsh-users/zsh-autosuggestions#503]
Could we either have a link to a documentation of the patterns for ``ZSH_AUTOSUGGEST_COMPLETION_IGNORE`` and ``ZSH_AUTOSUGGEST_HISTORY_IGNORE`` or collect some more examples? For example, I would like to know where the ``?(#c50,)`` syntax comes from.

I'm in particular interested in examples of
* How to specify several optional patterns
* How to match strings with less than x characters

**Comment by ericfreese** [comment]
Sure. The globbing documentation is here: http://zsh.sourceforge.net/Doc/Release/Expansion.html#Glob-Operators

The `?(#c50,)` example can be broken down like this:
- `?`: any character
- `(#c50,)`: instance of `cN,M` globbing flag with minimum 50 and no maximum

Combining multiple patterns can be done with the `x|y` and `x~y` operators.

Matching a string with less than x characters I think can be done with the `cN,M` leaving N unset and setting M. Something like `?(#c,20)` to match strings 20 or less chars long.

**Comment by klieret** [comment]
Thanks a lot for following up on this so quickly!
