### ISSUE TITLE
Tab-completion is not working

### ISSUE THREAD

**Issue by Rizhiy** [zsh-users/zsh-autosuggestions#508]
### Describe the bug

I installed the plugin, the suggestions work, but when I hit tab it just uses built-in autocomplete.

### To Reproduce

1. Install plugin using antigen

```sh
% zsh -df
% source path/to/zsh-autosuggestions.zsh
% source p
Press tab
```

### Expected behavior
The line completes to suggested path, e.g. `source path/to/zsh-autosuggestions.zsh`

### Screenshots
https://vimeo.com/user108587111/review/391246534/c7afdbbaa6

### Desktop
 - OS + distribution: Ubuntu 18.04.3 LTS
 - Zsh version: 5.4.2
 - Plugin version: 0.6.4

**Comment by ericfreese** [comment]
Hey @Rizhiy.

The desired behavior you're describing where the suggestion is accepted by pressing tab is not enabled by default. You can accept the suggestion by pressing the right arrow or triggering the `end-of-line` widget (ctrl + e in emacs mode). That's described on the ["Usage" section of the readme](https://github.com/zsh-users/zsh-autosuggestions#usage). The benefit of this arrangement is that you can continue to use the normal tab completion separately from the autosuggestion functionality.

I think you can enable the behavior you're describing by binding tab to the `autosuggest-accept` widget. Add the following to your zshrc (after sourcing the plugin):

```zsh
bindkey '^I' autosuggest-accept
```

That's described in the ["Key Bindings" section of the readme](https://github.com/zsh-users/zsh-autosuggestions#key-bindings).

**Comment by Rizhiy** [comment]
Thanks, I mistook right arrow for tab in README
