### ISSUE TITLE
Install problem I met

### ISSUE THREAD

**Issue by seineo** [zsh-users/zsh-autosuggestions#510]
```
OS: Ubuntu 18.04
Terminal: zsh 
```
I've tried to install it in this way:
```shell
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
plugins=(zsh-autosuggestions)
```
But it failed. No error, just not work.
I searched a lot and tried a lot, but all failed.
I don't know why, it seems like all people succeeded except me...
Is there anyone can help me out?
Needless to say, thanks for your kind help.

**Comment by lyaici** [comment]
Hi, I had the same issue, try to check if the problem is not the color of your terminal background (or font color) :wink:

**Comment by seineo** [comment]
I haven't seen your reply until now, sorry.
And, I changed my terminal background colour just now, and it succeed! 
Thank you very, very, very much! I was going to give up back then.
