### ISSUE TITLE
Unexpected suggestion completion after pasting

### ISSUE THREAD

**Issue by emilklindt** [zsh-users/zsh-autosuggestions#511]
### Describe the bug
When pasting a path or other text, the suggestion is not updated in the background. That means, that after pasting a text and pressing the right arrow to go to the end of inserted text, the previous suggestion is inserted. An example of this is shown in the screencast below.

### To Reproduce

 - Type until a suggestion is shown.
 - Paste a path or similar from clipboard.
 - Press right key to go to end of inserted selection.
 - See that the suggestion previous to pasting text is inserted.

### Expected behavior
The suggestion should be updated after insertion, or not responding to right arrow presses when text is selection if possible. 

### Screenshots
[![asciicast](https://asciinema.org/a/303476.svg)](https://asciinema.org/a/303476)

### Desktop
 - OS + distribution: macOS Catalina (10.15.3)
 - Zsh version: 5.7.1
 - Plugin version: 0.6.4

**Comment by emilklindt** [comment]
This is a minimal example of a `.zshrc` config to reproduce:

```shell
export ZSH="/Users/emilklindt/.oh-my-zsh"
plugins=(zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
```

**Comment by emilklindt** [comment]
This issue can be resolved by disabling highlight on paste in `.zshrc`:

```shell
zle_bracketed_paste=()
```

As mentioned in [in this issue](https://github.com/ohmyzsh/ohmyzsh/issues/5459). Since this seems to be more related to the ohmyzsh setting of highlighting pasted text, this issue may be closed.

**Comment by IngoMeyer441** [comment]
`zle_bracketed_paste=()` does not only disable the highlighting but also disables bracketed paste mode at all. Bracketed paste is quite convenient for multi line strings since newlines are not interpreted as enter key. Is there another way of solving this issue?

**Comment by AntonUspehov** [comment]
@emilklindt 
I have the same issue as @IngoMeyer441

Is there another workaround for this?

**Comment by jrmyfranck** [comment]
I'm trying to find another workaround, but I'm stuck.

I created a configuration file to override [Oh My Zsh's internals](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-internals) at `~/.oh-my-zsh/custom/my_patches.zsh`

Inside, I customised the behaviour for the autosuggestion, based on the configuration instructions from the README: 

```
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
    forward-word
)
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(
    forward-char
)
```

I'm trying to find the [zle widget](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Zle-Widgets) that corresponds to pasting, to include it in a `ZSH_AUTOSUGGEST_CLEAR_WIDGETS=()` block, which would (based on my understanding?) achieve the desired behaviour.


Any idea?

**Comment by andyacer** [comment]
Hi @jrmyfranck, thanks so much for sharing this.  I've iterated on your solution, it seems to be working great so far.  I tried using just your last line in my .zshrc file.  I put it after my omz plugins and sourcing oh-my-zsh, as shown below.  

```zsh
plugins=( zsh-autosuggestions )

source $ZSH/oh-my-zsh.sh

ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(bracketed-paste)
```

For those who aren't concerned with pasting URLs, this might be the solution we're after here.  Just one line to disable auto suggestions after a pasting something, while still using being able to use bracketed paste.

**Comment by IngoMeyer441** [comment]
@jrmyfranck and @andyacer: Thanks for sharing your solutions. @andyacer's simplified solution also works great for me, even with `url-quote-magic`. I am a bit confused why the custom `pasteinit` and `pastefinish` hooks are needed at all. :thinking:

**Comment by jrmyfranck** [comment]
@IngoMeyer441 they probably aren’t needed. 

I’m not super familiar with zsh, so I grabbed the script from the page I linked to, but my understanding of it is quite limited. 

Since it seemed to be working, I did not bother to modify it, but @andyacer’s approach is probably superior.
