### ISSUE TITLE
Change colour iterm2, oh my zsh

### ISSUE THREAD

**Issue by Fealo** [zsh-users/zsh-autosuggestions#514]
Hello
I'm trying to change the colour of the suggestion. So far it's of the colour of the regular text.
I tried adding a "ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=250" command to .zshrc which didn't do anything. I also added a ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="xx" with a bright colour to a .zsh file in the ~/.oh-my-zsh/custom path. That colour now lights shows up when the autosuggestion first appears, then the text is plain white again. Something seems to overwrite the setting. I couldnt find anything on iTerm to change it.
Any ideas? 

ZSH 5.7.1.,
OhMyZSH
OS X 15.3.1
iTerm2

Best 
Felix

**Comment by Fealo** [comment]
Sorry, trying to delete the "bug" label but cant seem to do that.

**Comment by Fealo** [comment]
Also, I've identified the source: it was zsh-syntax-highlight. I ahvent gotten it to work together yet but it works fine without it.

**Comment by jhonmike** [comment]
Hello @Fealo, I had the same problem as you and with your tip I changed the loading order between the two plugins, first I loaded the `zsh-syntax-highlight` and then the `zsh-autosuggestions` and the colors started working again!! thanks!!
