### ISSUE TITLE
ZSH_AUTOSUGGEST_STRATEGY=completion doesn't work

### ISSUE THREAD

**Issue by pirj** [zsh-users/zsh-autosuggestions#515]
### Describe the bug

Setting suggestion strategy to `completion` or `(completion)` doesn't show tab completions as suggestions.

### To Reproduce

![image](https://user-images.githubusercontent.com/6916/75815792-131ee400-5da5-11ea-8e6d-bd397c77fd7b.png)

### Expected behavior

Auto-suggestion is shown with data coming from tab-completion.

### Desktop
 - OS + distribution: macOS 10.14.6
 - Zsh version: 5.8
 - Plugin version: v0.6.4 (ae315de)

### Additional context

Didn't use `(completion)` previously, just the default `(history)`, and history works perfectly fine.

**Comment by ericfreese** [comment]
As of right now, you need to run `compinit` for the completion suggestions to work:

```sh
autoload compinit && compinit
```

I'll look into making the strategy work without it- I think it should be possible.

**Comment by pirj** [comment]
Worked flawlessly. Thanks a lot for the hint!
Do you want me to send a pull request to explicitly mention this gotcha in the documentation?

**Comment by mvcouwen** [comment]
> As of right now, you need to run `compinit` for the completion suggestions to work:
> 
> ```shell
> autoload compinit && compinit
> ```
> 
> I'll look into making the strategy work without it- I think it should be possible.

Came here for this! Thanks!
However, if this is necessary for completion to work, would it be an idea to add it to the README?

**Comment by jake-is-a-legend** [comment]
add this to the readme

**Comment by chrisgrieser** [comment]
I also came here for this. After an hour of going through the issues. Please add to the readme, that you need `autoload compinit && compinit`! 🙏

**Comment by cycloss** [comment]
Bump for this needs to be in the readme

**Comment by stefan-schweiger** [comment]
Still does not work for me with `autoload compinit && compinit`. Where should this be put in `.zshrc`?

**Comment by Kaanta7** [comment]
came here for this exact issue, THANK YOU !

**Comment by kfernandez31** [comment]
> Still does not work for me with `autoload compinit && compinit`. Where should this be put in `.zshrc`?

+1, the error is `ZSH_AUTOSUGGEST_STRATEGY: inconsistent type for assignment`
