### ISSUE TITLE
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE changes after source

### ISSUE THREAD

**Issue by OmisNomis** [zsh-users/zsh-autosuggestions#516]
### Describe the bug

The highlight style seems to change after sourcing `.zshrc`. If I create a new terminal window, the color style is as expected:

![image](https://user-images.githubusercontent.com/14848394/75981653-d8b86280-5edc-11ea-9cce-2d18952cb315.png)

But if I source my `.zshrc` file, it goes to a bold white highlight style which is not what I want (the below screenshot is at the same point as the one above, as is auto-completing the file path).

![image](https://user-images.githubusercontent.com/14848394/75981696-f1287d00-5edc-11ea-9175-953270888ebd.png)

echoing out the variable gives the expected result

```
$ echo $ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE
fg=8
```

### To Reproduce

See above

### Expected behavior

Highlight style does not change on source

### Desktop
 - OS + distribution: OSX
 - Zsh version: 5.7.1
 - Plugin version: 

```
$ cat ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/VERSION
v0.6.4
```

### Additional context
.zshrc file below:

```
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(colored-man-pages dotenv history-substring-search osx z zsh-autosuggestions zsh-syntax-highlighting)

ZSH_DOTENV_FILE=local.env
ZSH_DOTENV_PROMPT=false

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

DISABLE_MAGIC_FUNCTIONS=true

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zstyle ':urlglobber' url-other-schema

# rbenv
eval "$(rbenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

**Comment by ericfreese** [comment]
I don’t know what exactly is going on here but it’s generally not a good idea to source your .zshrc additional times. If you’ve made changes to the file, try `exec zsh` instead.

**Comment by ericfreese** [comment]
You may also want to try removing (or commenting out) portions of your .zshrc to determine exactly which plugins/lines are necessary to reproduce the problem.

**Comment by OmisNomis** [comment]
Thanks for the quick response. 

It turns out the `zsh-syntax-highlighting` plugin is conflicting somehow. I commented it out and everything worked as expected. 

`exec zsh`, instead of sourcing `.zshrc` also works so I'll use that :)

Shall I close this?
