### ISSUE TITLE
History synchronization between multiple terminals

### ISSUE THREAD

**Issue by mintelm** [zsh-users/zsh-autosuggestions#519]
### Describe the bug
When sharing the history file between multiple Terminal sessions, zsh-autosuggestions doesn't refresh the history if Terminal1 types: `vim test`, Terminal2 doesn't suggest `vim test`. But if I type `history` in Terminal2 the autosuggestion works correct afterwards.

### To Reproduce
Start 2 Terminals: Terminal1 and Terminal2. Write a command in Terminal1 e.g. `vim test`.
Type `vi` in Terminal2. Terminal2 won't suggest `vim test`. If I run `history` in Terminal2 the autosuggestion works fine.

### Expected behavior
I would expect Terminal2 to autosuggest `vim test` without writing `history`.

### Desktop
 - OS + distribution: Arch Linux 5.5.11
 - Zsh version: 5.8
 - Plugin version: 0.6.4-1

### Additional context
My zshrc options for history:
```
HISTFILE=~/.cache/zsh_history
HISTSIZE=50000
SAVEHIST=10000
setopt appendhistory
setopt extendedhistory
setopt sharehistory
setopt incappendhistory
```

**Comment by mindyourlifeguide** [comment]
@mintelm, sharing a history file works after a session reload
