### ISSUE TITLE
Suggestions not cleared after enter

### ISSUE THREAD

**Issue by mindyourlifeguide** [zsh-users/zsh-autosuggestions#525]
### Describe the bug
Suggestions not cleared after enter

### Expected behavior
Clearing autosuggestions after enter

### Screenshots

![Peek 2020-04-18 12-08](https://user-images.githubusercontent.com/35348648/79633417-14964700-816e-11ea-8e53-eb3c32735b4a.gif)

### Desktop
![image](https://user-images.githubusercontent.com/35348648/79633442-4dceb700-816e-11ea-8488-72f1c112c615.png)
 - OS: Arch Linux 2020.04.18
 - Zsh version: 5.8
 - Plugin version: latest 

### Additional context
These options do not help solve this problem.
`ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(expand-or-complete bracketed-paste accept-line push-line-or-edit)`

**Comment by aschleifer** [comment]
I also have the same problem which kept me from really using this addon. otherwise I love it.

A bit more background:
- I'm using archlinux on the hardened kernel (but also hat it on the normal kernel)
- I use antigen to handle zsh plugins

**Comment by gawa971** [comment]
I also have this issue. However I'm not sure it's a bug in zsh-autosuggestions.

I cannot reproduce this with zsh-autosuggestions installed alone, with zgen, over a fresh/vanilla zsh : 
```bash
gawa@localhost:~> git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
Cloning into '/home/gawa/.zgen'...
[...]
gawa@localhost:~> source "${HOME}/.zgen/zgen.zsh"
gawa@localhost:~> zgen load zsh-users/zsh-autosuggestions
Cloning into '/home/gawa/.zgen/zsh-users/zsh-autosuggestions-master'...
[...]
gawa@localhost:~> pwd
/home/gawa
gawa@localhost:~> cd /mnt
gawa@localhost:/mnt> #   ^-- it suggested "/mnt/storage" but the "/storage" dissapeard after pressing enter, as expected. No bug.
gawa@localhost:/mnt>
```

It looks like the bug is introduced by my prompt : 
```bash
gawa@localhost:/mnt> zgen load subnixr/minimal
Cloning into '/home/gawa/.zgen/subnixr/minimal-master'...
[...]
λ › cd /mnt                                                                                                                                  /mnt
λ › #   ^--- here I already was in /mnt, as shown in the right prompt. I only typed "/" and pressed enter. The suggestion didn't clear.                                                                                                    /
λ › pwd                                                                                                                                          /
/
λ ›  
```

The good news is that since subnixr/minimal is a minimal prompt, it'll be easier to debug.

**Comment by gawa971** [comment]
In my case it was a conflict with the prompt [subnixr/minimal](https://github.com/subnixr/minimal). The last thing it does is remapping the enter key with ```bindkey -M main  "^M" buffer-empty```

My workaround consists in overriding this in my .zshrc after loading the prompt, I want the return key to be mapped to the default "accept-line" :  ```bindkey -M main "^M" accept-line```

It does the trick. Alternatively, after identifying the zle widget called by the return key (^M), you could add it in the autosuggest option. In my case ```ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(buffer-empty)``` works. However I really didn't understand what is this buffer-empty widget, since it doesn't even seem to exists in zsh and my prompt really.

That said, I found another bug : pressing ctrl+c doesn"t clear the suggestion. I didn't find a workaround for that.

**Comment by aschleifer** [comment]
I found out that my conflict came from oh-my-zsh plugin magic-enter: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/magic-enter/magic-enter.plugin.zsh#L24

For now I have disabled magic-enter. Maybe I will remap it to a different key. not sure.

**Comment by metebyte** [comment]
> I found out that my conflict came from oh-my-zsh plugin magic-enter: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/magic-enter/magic-enter.plugin.zsh#L24
> 
> For now I have disabled magic-enter. Maybe I will remap it to a different key. not sure.

Really thanks for this. I couldn't find out it was the one conflicting.

**Comment by mindyourlifeguide** [comment]
> I found out that my conflict came from oh-my-zsh plugin magic-enter: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/magic-enter/magic-enter.plugin.zsh#L24
> 
> For now I have disabled magic-enter. Maybe I will remap it to a different key. not sure.

Thanks! It`s solved my problem.

**Comment by CharlesGueunet** [comment]
For those who want magic enter and autosuggestion, it worked for me using the implemention [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/magic-enter/magic-enter.plugin.zsh)

In my zshrc:
```
: ${MAGIC_ENTER_OTHER_COMMAND:="clear"}
magic-enter() {
  # Only run MAGIC_ENTER commands when in PS1 and command line is empty
  # http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#User_002dDefined-Widgets
  if [[ -n "$BUFFER" || "$CONTEXT" != start ]]; then
    return
  fi

  BUFFER="$MAGIC_ENTER_OTHER_COMMAND"
}

# Wrapper for the accept-line zle widget (run when pressing Enter)

# If the wrapper already exists don't redefine it
(( ! ${+functions[_magic-enter_accept-line]} )) || return 0

case "$widgets[accept-line]" in
  # Override the current accept-line widget, calling the old one
  user:*) zle -N _magic-enter_orig_accept-line "${widgets[accept-line]#user:}"
    function _magic-enter_accept-line() {
      magic-enter
      zle _magic-enter_orig_accept-line -- "$@"
    } ;;
  # If no user widget defined, call the original accept-line widget
  builtin) function _magic-enter_accept-line() {
      magic-enter
      zle .accept-line
    } ;;
esac

zle -N accept-line _magic-enter_accept-line
```

**Comment by AndrewBelt** [comment]
I have no idea what I'm doing, but I wrote this simple implementation of magic-enter that clear the screen on an empty buffer, and clears the suggestion on enter.
```zsh
magic-enter() {
	if [[ -z "$BUFFER" ]]; then
		zle clear-screen
	else
		# Call built-in accept-line
		zle .accept-line
	fi
}
zle -N accept-line magic-enter
```

**Comment by CharlesGueunet** [comment]
@AndrewBelt this seems to work pretty well ! thanks
