### ISSUE TITLE
Use <tab> to choose autosuggestion

### ISSUE THREAD

**Issue by himat** [zsh-users/zsh-autosuggestions#532]
### Is your feature request related to a problem? Please describe.

When I start typing a command, and zsh shows an autosuggestion, is it possible to choose the autosuggestion by pressing the `tab` key or some other key instead of the right arrow key?
Moving my hand all the way to the right arrow key is slow, so is everyone only using the right arrow key to choose the autosuggestion?

### Describe the solution you'd like

Pressing tab when an autosuggestion hint is shown should just choose the shown autosuggestion.

**Comment by svermeulen** [comment]
This is possible by adding this to your .zshrc:
```
bindkey '\t' end-of-line
```

**Comment by svermeulen** [comment]
I personally don't use it though, because sometimes the default tab behaviour is useful, like choosing directories

**Comment by himat** [comment]
Yeah that's true.
So does everyone just move their hand all the way to the right arrow key then? Does anyone have a better method instead of overriding the tab key?

**Comment by svermeulen** [comment]
Well if you don't want to use right arrow key then you can put any other key instead of tab in that code I pasted above.

Btw also, I realized that you can do this
```
export ZSH_AUTOSUGGEST_STRATEGY=(
    history
    completion
)
```
Which allows the preview to fallback on using tab completion when there is no matching history.  This is pretty nice when choosing directories.  Which makes those times when you really need tab a bit less common.

**Comment by ericfreese** [comment]
I mostly use ^E for end-of-line (in emacs mode)

**Comment by holdjohnh** [comment]
thx
> I mostly use ^E for end-of-line (in emacs mode)

**Comment by mindyourlifeguide** [comment]
I'm use
```
bindkey '^I'      autosuggest-accept
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(buffer-empty bracketed-paste accept-line push-line-or-edit)
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=true
```

tab - history completion
shift+tab - autosuggest completion

**Comment by himat** [comment]
@mindyourlifeguide did you write that incorrectly?
I tried using that, but it makes tab do autosuggest completion, and shift+tab do history completion backwards.

How would I invert the tab and shift+tab from those lines you pasted?

**Comment by himat** [comment]
Specifically, I tested that while using cd
`$ cd <completion shows a previous cd command>`
If I use tab, it accepts it.
But I usually press tab to see all the subdirs in this dir and cycle through them, so I don't want to lose that behavior.

**Comment by mindyourlifeguide** [comment]
> Specifically, I tested that while using cd
> `$ cd <completion shows a previous cd command>`
> If I use tab, it accepts it.
> But I usually press tab to see all the subdirs in this dir and cycle through them, so I don't want to lose that behavior.

I wrote the combinations that I use)
These are right for you:
```
bindkey '^ I'   complete-word       # tab          | complete
bindkey '^ [[Z' autosuggest-accept  # shift + tab  | autosuggest
```

**Comment by be-rock** [comment]
this seems to work as expected:

```
 bindkey '\t' autosuggest-accept
```

**Comment by monkpit** [comment]
@be-rock as mentioned elsewhere, this clobbers the default tab behavior (for example `ls ./<tab>` will not suggest directories)

**Comment by tsids** [comment]
For some reason, none of the commands in this thread
```
bindkey '\t' autosuggest-accept
bindkey '^I'   complete-word
bindkey '^[[Z' autosuggest-accept
```
were working for me, at all. As in nothing would happen and it would default to cycling through all the entries.

At the end, i just went with 
```
bindkey '\t\t' autosuggest-accept
```
This way, pressing tab twice quickly in succession autocompletes the suggestion, but if I press tab once and leave it, then I can cycle through all the possible suggestions.

**Comment by sweetyGremlin** [comment]
> I mostly use ^E for end-of-line (in emacs mode)

I love you man! Thanks

**Comment by joshuadunning** [comment]
I'm using $ as completion. Similar to VIM end of line. 

.zshrc
`bindkey '$' autosuggest-accept`

**Comment by tarunaksha** [comment]
> For some reason, none of the commands in this thread
> 
> ```
> bindkey '\t' autosuggest-accept
> bindkey '^I'   complete-word
> bindkey '^[[Z' autosuggest-accept
> ```
> 
> were working for me, at all. As in nothing would happen and it would default to cycling through all the entries.
> 
> At the end, i just went with
> 
> ```
> bindkey '\t\t' autosuggest-accept
> ```
> 
> This way, pressing tab twice quickly in succession autocompletes the suggestion, but if I press tab once and leave it, then I can cycle through all the possible suggestions.

thanks man...good suggestion. I am using the same

**Comment by zeroarst** [comment]
Hi is it possible to use `tab` for `autosuggest-accept`, and change `ctrl + space` for shell suggestion such as `ls` cycle through?

**Comment by anashakt** [comment]
> For some reason, none of the commands in this thread
> 
> ```
> bindkey '\t' autosuggest-accept
> bindkey '^I'   complete-word
> bindkey '^[[Z' autosuggest-accept
> ```
> 
> were working for me, at all. As in nothing would happen and it would default to cycling through all the entries.
> 
> At the end, i just went with
> 
> ```
> bindkey '\t\t' autosuggest-accept
> ```
> 
> This way, pressing tab twice quickly in succession autocompletes the suggestion, but if I press tab once and leave it, then I can cycle through all the possible suggestions.
I like this one the most

**Comment by jonwcode** [comment]
None of these are working for me. I just simply want to press tab twice to autosuggest accept.

**Comment by Ekanshh** [comment]
Works for me. Generated via chat-gpt 4o: 

```
# Bind Tab to accept the autosuggested word (from cursor to first space)
bindkey '^I' forward-word

# Bind Shift + Tab to accept the whole autosuggestion
bindkey '^[[Z' autosuggest-accept
```

**Comment by elgs** [comment]
Is there anyway to bind to the command key + some letter key on a Mac keyboard?

**Comment by kohrachel** [comment]
For anyone trying to set up a custom key binding (e.g. <kbd>Shift</kbd> + <kbd>Tab</kbd>) for autocomplete, here's some troubleshooting steps that helped me: 

1. If you're using `oh-my-zsh`, make sure your `bindkey` config comes AFTER sourcing omz in your `.zshrc` file, e.g.

   ```sh
   source $ZSH/oh-my-zsh.sh
   bindkey '^[[Z' end-of-line
   ```
   If you do not do this, omz will overwrite your keybinding (at least for `end-of-line`) and there will be no effect. 

2. To check if your key binding succeeded, you can do:

    ```zsh
    # checks SHIFT + TAB binding 
    bindkey | grep '\^\[\[Z' 

    # should see something like this if you successfully bound the key 
    "^[[Z" end-of-line

    # if you instead see something like this, something is overwriting your keybinding
    "^[[Z" reverse-menu-complete
    ```

    If you see something other than what you bound the key to (in my case it was `reverse-menu-complete`), try 1. Otherwise, you may have something else that is overwriting the keybinding. Try moving the bindkey nearer to the end of your `.zshrc`

3. If you want to know what a particular keybinding is called, you can run `cat` in your terminal and then press your desired keybinding, e.g.:

    ```zsh
    cat
    
    # press SHIFT + TAB, get:
    ^[[Z
    ```
    
    This will give you the key binding that you can use in the `bindkey` command in your `.zshrc` file. If you try a key combination and nothing appears, that key binding might not be available (e.g. <kbd>CTRL</kbd> + <kbd>Tab</kbd>)

    And then use <kbd>CTRL</kbd> + <kbd>C</kbd> to exit
