### ISSUE TITLE
Ability to navigate the history beyond just the first match

### ISSUE THREAD

**Issue by svermeulen** [zsh-users/zsh-autosuggestions#533]
### Is your feature request related to a problem? Please describe.
I often find myself in situations where the suggested match is incorrect, and I know that the second-best match is what I am looking for. 

### Describe the solution you'd like
It would be amazing if we could bind a key to apply an offset to the history selection, so we could go forwards/backwards from the current best match, instead of only being able to choose or not choose the best match

### Describe alternatives you've considered
None

**Comment by ericfreese** [comment]
Hi, this has actually come up a few times. See #192, #409, #387

**Comment by svermeulen** [comment]
Thanks, yeah those solutions work for me

**Comment by shqear93** [comment]
https://github.com/zsh-users/zsh-autosuggestions/issues/609#issuecomment-904204583
