### ISSUE TITLE
Cursor-up stopped working recently

### ISSUE THREAD

**Issue by peti** [zsh-users/zsh-autosuggestions#534]
For the longest time, the "cursor-up" key would cycle through possible completions while honoring the already accepted prefix, but this feature has suddenly disappeared on my system a few days ago and I have no idea why. 

For example, let's say my history contained the following commands:

    xrandr --output DisplayPort-0 --auto
    ls /foo/bar
    xrandr --output DisplayPort-0 --mode 1920x1080 

Now, if I type `xrandr`, then I'll get a suggestion for the third of those commands. At that point, I used to move the cursor a word forward -- to the end of `xrandr` -- and hit cursor-up to get the first `xrandr` command (the one with the `--auto` flag), but nowadays this doesn't work. Instead I'll get `ls /foo/bar`.  It seems like cursor-up is no longer bound to `zsh-autosuggestions`.

Does anyone know how to explain this phenomenon? And, more importantly, what should I do to get the old behavior back which was far nicer, IMHO?

**Comment by ericfreese** [comment]
Hi, I don’t think zsh-autosuggestions has ever implemented this behavior but maybe you were using `history-beginning-search-backward` and `-forward`?

**Comment by svermeulen** [comment]
TIL about `history-beginning-search-backward` and `history-beginning-search-forward` which seem quite useful.  Why is it that they are different from the suggestion that `zsh-autosuggestions` displays?  Going backwards then forwards does not reveal the same suggestion

**Comment by peti** [comment]
Okay, I managed to get the old behavior back by making the following change to my .zshrc:

~~~
-bindkey '\e[A' history-beginning-search-backward
-bindkey '\e[B' history-beginning-search-forward
+bindkey "\eOA" history-beginning-search-backward
+bindkey "\eOB" history-beginning-search-forward
~~~
 
For some reason, the old key spec for cursor-up and -down stopped working. I have no idea what caused this ... but I'm sure glad that now it's working again.
