### ISSUE TITLE
is it possible to change * color

### ISSUE THREAD

**Issue by tzutalin** [zsh-users/zsh-autosuggestions#535]
Hi,
I like zsh-autosuggestions which saves me tons of time on typing.

However, when I type "find *" whose * is in dark blue color. It is not clear on my iterm2 . It is possible to change the color for *?

**Comment by ericfreese** [comment]
This plugin does not do any coloring of text that you have already typed. It sounds like the * you’re referring to is not a suggestion but has already been typed? In that case I’m wondering if you’re using the zsh-syntax-highlighting plugin and that is what’s coloring it blue. I would check out the docs for that project and possibly ask on that GitHub repo instead.

**Comment by tzutalin** [comment]
Hi @ericfreese 
Thanks! I guess you are right.
I installed `zsh-syntax-highlighting` and `zsh-autosuggestions` at the same time. 

I guess it is caused by https://github.com/zsh-users/zsh-syntax-highlighting/blob/db6cac391bee957c20ff3175b2f03c4817253e60/tests/tap-colorizer.zsh#L45
I will close this issue. Thanks
