### ISSUE TITLE
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS not working for `forward-char`

### ISSUE THREAD

**Issue by marlonrichert** [zsh-users/zsh-autosuggestions#537]
### Describe the bug
I added `forward-char` to `ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS`, but when I press right arrow, it accepts the whole line, instead of just one character.

### To Reproduce
Given:
* <kbd>ctrl</kbd><kbd>V</kbd> + right arrow outputs `^[OC`.
* `bindkey '^[OC'` outputs `"^[OC" forward-char`.

When
1. I input the following in the shell:
```
$ zsh -df
% typeset -ga ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS
% ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(
  forward-char
  vi-forward-char
  forward-word
  emacs-forward-word
  vi-forward-word
  vi-forward-word-end
  vi-forward-blank-word
  vi-forward-blank-word-end
  vi-find-next-char
  vi-find-next-char-skip
)
% source path/to/zsh-autosuggestions.zsh
```
2. I type `s`.
    * I get `ource path/to/zsh-autosuggestions.zsh` as a suggestion.
3. I press right arrow to accept the first character of the suggestion.

Then
* The whole line gets accepted.

### Expected behavior
Only the first character of the suggestion (`o`) should get accepted.

### Desktop
 - OS + distribution:  macOS 10.15.4 (19E287)
 - Zsh version: 5.8
 - Plugin version: ae315ded4dba10685dbbafbfa2ff3c1aefeb490d

### Additional context
This used to work just fine.

**Comment by bayesrule** [comment]
Same issue, win10+wsl2+zsh

**Comment by Rayqan** [comment]
Also having the same problem on Arch/zsh 5.8

**Comment by marlonrichert** [comment]
Appears to be working correctly now.
