### ISSUE TITLE
<tab> matching partial substrings

### ISSUE THREAD

**Issue by cameronbraid** [zsh-users/zsh-autosuggestions#539]
One feature I like from fish is tab completion like the following

current dir contains folders named :

something-infra1
foo-infra2
blah-infra3

in fish you can type 

`cd inf2<tab>` and it will complete with `foo-infra2`

**Comment by ericfreese** [comment]
Hi, this plugin doesn’t have anything to do with tab completion, but I think the behavior you want can be implemented in plain zsh. I’m not sure the exact details but found this on a quick google search: https://superuser.com/questions/415650/does-a-fuzzy-matching-mode-exist-for-the-zsh-shell

**Comment by cameronbraid** [comment]
Aah, ok thanks for the pointer.. The suggestion at that link seems to work well !

 .zshrc
```
# 0 -- vanilla completion (abc => abc)
# 1 -- smart case completion (abc => Abc)
# 2 -- word flex completion (abc => A-big-Car)
# 3 -- full flex completion (abc => ABraCadabra)
zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'
```
