### ISSUE TITLE
Suggest file names in the filesystem

### ISSUE THREAD

**Issue by iven** [zsh-users/zsh-autosuggestions#543]
Please support suggesting file names/paths in the filesystem, like fish shell does.

Say we have three files in current directory: **users.txt usage.txt readme.txt**

suggest as you type:
$ vim 
$ vim u(sers.txt)
$ vim usa(ge.txt)

or deeper path in the directory:
$ vim /path/to/your/fi(le.txt)

**Comment by ericfreese** [comment]
Have you tried the `completion` suggestion strategy? https://github.com/zsh-users/zsh-autosuggestions#suggestion-strategy

You also may want to use async mode with it since completion can take a little while https://github.com/zsh-users/zsh-autosuggestions#enable-asynchronous-mode

**Comment by iven** [comment]
Ah, maybe it's caused by wrong config, I'll try. Closing this for now, I'll reopen if it doesn't work. Thanks.
