### ISSUE TITLE
Vim mode issues with autosuggestions

### ISSUE THREAD

**Issue by gerazov** [zsh-users/zsh-autosuggestions#545]
Let me start off by saying that this is one of the features that have completely changed my experience of using the terminal kudos :+1: :clap: 

I've found that scrolling through the auto suggestions in vim mode doesn't work for me, both using `bindkey -v` and the `zsh-vim-mode` plug in. Originally I though it was because of the `zsh-vim-mode` (https://github.com/softmoth/zsh-vim-mode/issues/25) but the behaviour using `bindkey -v` gives the same behaviour. 

To reproduce just start typing a command in insert mode and then switch to vim mode and try scrolling for different autosuggestions and it simply scrolls from history ignoring the typed text. This also doesn't work when scrolling back with arrow keys in insert mode. 

![zsh_vim_backintime](https://user-images.githubusercontent.com/15214418/84243625-c44ebc00-ab02-11ea-9228-8a4afdda6d4d.gif)

Another problem is that going word by word in the suggestion can be done using `w` in normal mode (although it flashes some annoying output), but going back using `b` doesn't deselect them.
![zsh_vim_autocomplete](https://user-images.githubusercontent.com/15214418/84243426-776ae580-ab02-11ea-836a-ad0903047008.gif)

My plugin list reads:
```
plugins=(
  git
  extract
  colored-man-pages
  zsh-interactive-cd
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-vim-mode
  )
source $ZSH/oh-my-zsh.sh
```

 - OS + distribution: 5.4.44-1-MANJARO 20.0.3
 - Zsh version: 5.8
 - Plugin version: v0.4.3

**Comment by meav** [comment]
> To reproduce just start typing a command in insert mode and then switch to vim mode and try scrolling for different autosuggestions and it simply scrolls from history ignoring the typed text. This also doesn't work when scrolling back with arrow keys in insert mode.
> 
> ![zsh_vim_backintime](https://user-images.githubusercontent.com/15214418/84243625-c44ebc00-ab02-11ea-9228-8a4afdda6d4d.gif)
> 
I have a same this issue, I use plugin vi-mode of oh-my-zsh
[https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vi-mode](url)

**Comment by meav** [comment]
More info in my case: When in insert mode, up and down key search history with typed text; but in normal mode, up and down key work same as j and k key: search history without typed text.

**Comment by meav** [comment]
> To reproduce just start typing a command in insert mode and then switch to vim mode and try scrolling for different autosuggestions and it simply scrolls from history ignoring the typed text. This also doesn't work when scrolling back with arrow keys in insert mode.
> 
> ![zsh_vim_backintime](https://user-images.githubusercontent.com/15214418/84243625-c44ebc00-ab02-11ea-9228-8a4afdda6d4d.gif)
> 
This is not a bug, I solved this by add more key bindding in .zshrc:
```
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search
```

**Comment by gerazov** [comment]
This works - thanks! :+1:
