### ISSUE TITLE
"no such file or directory" on ubuntu 20.04 + oh-my-zsh

### ISSUE THREAD

**Issue by raulferras** [zsh-users/zsh-autosuggestions#557]
### Describe the bug
After installing zsh-autosuggestions on `oh-my-zsh`, after reloading zsh I always get:

```
/home/raul/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh:source:1: no such file or directory: /home/raul/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh^M
```

### To Reproduce
- Clone repo with: `git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions`
- Modify my `.zshrc` file and add the plugin: 
```
plugins=(git zsh-autosuggestions)
```
- Reload shell with `zsh` on the terminal.
- It outputs: 
```
/home/raul/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh:source:1: no such file or directory: /home/raul/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh^M
```

### Expected behavior
No error message should be displayed and plugin loaded.

### Desktop
 - OS + distribution: Ubuntu 20.04
 - Zsh version: 5.8
 - Plugin version: git commit: ae315de

**Comment by AntonTrapp** [comment]
Is it possible that you run your ubuntu with wsl on windows? ^M at the error is normally a "git config messed up" sign.

I had the same error and solved it by removing the plugin (in ~/.oh-my-zsh/custom/plugins/zsh-autosuggestion), changing the git CRLF handling:

```bash
git config --global core.autocrlf false
git config --global core.eol lf
```
and re-installing it. Maybe it's working for you too.

**Comment by johnsi15** [comment]
> Is it possible that you run your ubuntu with wsl on windows? ^M at the error is normally a "git config messed up" sign.
> 
> I had the same error and solved it by removing the plugin (in ~/.oh-my-zsh/custom/plugins/zsh-autosuggestion), changing the git CRLF handling:
> 
> ```shell
> git config --global core.autocrlf false
> git config --global core.eol lf
> ```
> 
> and re-installing it. Maybe it's working for you too.

This worked for me, 

I changed the config git and re-installing plugins.

Thanks.

**Comment by jmk2142** [comment]
Thanks @johnsi15 . This solution also worked for me with the autosuggestion and syntax highlighting plugins.

**Comment by varshneydevansh** [comment]
[https://github.com/ohmyzsh/ohmyzsh](https://github.com/ohmyzsh/ohmyzsh)

Manual Inspection

It's a good idea to inspect the install script from projects you don't yet know. You can do that by downloading the install script first, looking through it so everything looks normal, then running it:

wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
sh install.sh

If the above URL times out or otherwise fails, you may have to substitute the URL for https://install.ohmyz.sh to be able to get the script

**Comment by dev-danka** [comment]
> ```shell
> git config --global core.eol lf
> ```

This. rm -Rf your/dir/of/plugins/zsh-autosugg 
and git clone again
