### ISSUE TITLE
Is this zsh-autosuggestions plugin support detecting pwd folders?

### ISSUE THREAD

**Issue by StageGuard** [zsh-users/zsh-autosuggestions#561]
### Is this `zsh-autosuggestions` plugin support detecting pwd folders?

In fish, when I type first few characters of the folder name, fish shell will show the complete folder name.
But it seems that the plugin doesn't support this feature.

Shall I search for configurations or it actually doesn't support this feature?

### Screenshots

![This is fish shell](https://user-images.githubusercontent.com/45701251/91638977-e42cb680-ea45-11ea-8838-f0deef6b7888.png)
fish shell
![This is zsh with 
zsh-autosuggestions plugin](https://user-images.githubusercontent.com/45701251/91639006-07effc80-ea46-11ea-9a1b-bf9fc9bbe040.png)
zsh with  zsh-autosuggestions plugin

**Comment by ericfreese** [comment]
The default behavior is to only make suggestions based on your shell history, so with no config modifications you should get the suggestion you want after you’ve run it once.

You can also enable the `completion` suggestion strategy (see the readme) to get suggestions not based on history but based on tab completion.

Also somewhat related, there is an open ticket to make history suggestions (the default) behave more like Fish here: #426
