### ISSUE TITLE
Is there a way I can disable auto suggestions for specific categories

### ISSUE THREAD

**Issue by test-cmd-afk** [zsh-users/zsh-autosuggestions#566]
### Is your feature request related to a problem? Please describe.
It's annoying when I'm typing out my command and then it's constantly sending requests for the autosuggestions because it's really slow and makes it feel laggy. I don't want it to auto suggest those but I would still like to be able to search with tab. Same thing for when I'm scping and it tries to auto suggest directories.

### Describe the solution you'd like
A way to disable internet requests for auto suggestions 

### Describe alternatives you've considered
Disabling per command but this would suck more since I would have to manually add to the list every time I find a command that's affected by this

### Additional context
n/a

**Comment by ericfreese** [comment]
> It's annoying when I'm typing out my command and then it's constantly sending requests for the autosuggestions because it's really slow and makes it feel laggy

Have you tried the async mode? This will be enabled by default in the next version.

https://github.com/zsh-users/zsh-autosuggestions#enable-asynchronous-mode

> Disabling per command

You can try this for now if you haven't already.

https://github.com/zsh-users/zsh-autosuggestions#skipping-completion-suggestions-for-certain-cases

**Comment by test-cmd-afk** [comment]
Oh the async mode makes it a lot better. Thanks.
