### ISSUE TITLE
Missing character for long suggestions

### ISSUE THREAD

**Issue by AckslD** [zsh-users/zsh-autosuggestions#578]
### Describe the bug
When a autosuggestion is longer than the terminal width and the current text stop matching the long suggestion, one character is no longer displayed in the terminal. I think the easiest is to explain with the screencast below:

### To Reproduce

* Type a command longer than the terminal width.
* Type another command which first matches the long one and then doesn't.

### Expected behavior
No missing characters.

### Screenshots
![zsh_autosuggestions_issue](https://user-images.githubusercontent.com/23341710/102018545-2a482480-3d6e-11eb-9ab6-c4047e0ac250.gif)

Note, that the second command works, it's just that the " is not displayed when typing the command.

### Desktop
 - OS + distribution: EndeavourOS Linux x86_64, 5.9.13-arch1-1
 - Zsh version: zsh 5.8 (x86_64-pc-linux-gnu)
 - Plugin version: commit ae315ded4dba10685dbbafbfa2ff3c1aefeb490d

### Additional context
I'm using the following plugins.
```zsh
plugins=(
    git
    virtualenv
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-vim-mode
    timer
    tmux
    history-substring-search
    archlinux
)
```

**Comment by ericfreese** [comment]
Hi, I'm not able to reproduce this. I'm guessing that it has something to do with your prompt. Can you reproduce with a simpler prompt?

**Comment by AckslD** [comment]
Hi @ericfreese thanks for you suggestion. I will play around with some simpler prompts to see if I can find out what's going on.

**Comment by AckslD** [comment]
@ericfreese I think I narrowed it down to how I make the prompt different depending on whether the last command succeeded or not. I'm able to reproduce the issue with this minimal prompt:
```zsh
PROMPT='%{%(?.v.x)%}: '
```

Any idea if this is an issue with autosuggestions or with the way I'm doing it?

**Comment by ericfreese** [comment]
I'm not an expert on prompt expansion, but it looks like you might be using `%{...%}` incorrectly. 

http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Visual-effects

It says

> The string within the braces should not change the cursor position.

But your string within the braces does change the cursor position by outputting either `v` or `x`.

Can you remove the use of that construct and just do this?

```zsh
PROMPT='%(?.v.x)'
```

**Comment by AckslD** [comment]
Thanks a lot @ericfreese! This solved it for me :) I wasn't really sure what exactly `%{...%}` was doing since I just edited the existing muse theme. Anyway I replaced most of them with `%F..%f` around coloured parts and the issue is gone.
