### ISSUE TITLE
Failure to detect pasted content leads to wrongly continuing to suggest

### ISSUE THREAD

**Issue by PythonTryHard** [zsh-users/zsh-autosuggestions#583]
### Describe the bug
As an `oh-my-zsh` plugin, `zsh-autosuggestions` fails to detect if something has been pasted and will continue to suggest until such pasted content is modified (adding/removing a character)

### To Reproduce (with Screenshots)
Note: All screenshots are obtained with the minimal `.zshrc` attached below.

1. Write down any command that can lead to a suggestion.
![image](https://user-images.githubusercontent.com/31789326/106887764-34582500-6718-11eb-9cc1-559a730318f8.png)
2. Paste something in. The pasted content should be highlighted in white. Suggestion cannot be seen
![image](https://user-images.githubusercontent.com/31789326/106887838-50f45d00-6718-11eb-86ae-25840ba7a034.png)
3. Pressing <kbd>←</kbd> should de-highlight the pasted content and reveal the suggestion still being there (when it supposedly shouldn't be)
![image](https://user-images.githubusercontent.com/31789326/106889166-3ae79c00-671a-11eb-966a-a218c2560ba4.png)
Additionally, pressing <kbd>→</kbd> or <kbd>End</kbd> should de-highlight and adding the suggestion to the end of the pasted content.
![image](https://user-images.githubusercontent.com/31789326/106889319-6cf8fe00-671a-11eb-911c-8cd64cc25f5e.png)

### Expected behavior
After pressing <kbd>←</kbd>, there should be no suggestion, and pressing <kbd>→</kbd> or <kbd>End</kbd> should not result in the suggestion getting added to the end.

### Desktop
 - OS + distribution: KDE neon Testing Edition 5.21, and Ubuntu 20.10 (both are fully up-to-date as of writing this report)
 - Zsh version: `5.8`
 - Plugin version: `ae315ded4dba10685dbbafbfa2ff3c1aefeb490d`

#### Minimal `.zshrc` that can trigger this bug
Irreproducible locally with `zsh -df` followed by manual sourcing due to suggestion not appearing, however reproducible with the following minimal `.zshrc`
```sh
export ZSH="/home/f4ll3n53r4ph/.oh-my-zsh"
plugins=(zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
```

#### Terminal tested against
On KDE neon:
1. Konsole 20.12.2
2. `kitty` 0.19.3 (freshly out of the box)

On Ubuntu 20.10:
1. GNOME Terminal 3.38.0

**Comment by lihk11** [comment]
have the same problem
