### ISSUE TITLE
Include files as a suggestion to the command

### ISSUE THREAD

**Issue by manjunathb4461** [zsh-users/zsh-autosuggestions#584]
### Is your feature request related to a problem? Please describe.

In most of the cases the user would be traversing some files from directory, so what if that is also provided as a suggestion

### Describe the solution you'd like

suppose user types some command, then this plugin would complete it with first file/directory by order, by modified time or by alphabetical order as a suggestion
eg, whenever user types `cd /usr/local/` plugin completes it with `cd /usr/local/bin`

### Describe alternatives you've considered

currently users keep hitting tabs until what they want is suggested to them, that can be made easier using this plugin

### Additional context

This suggestion can be made only if current suggestion based on history returns none

**Comment by ericfreese** [comment]
Hi, have you tried using the [`completion` suggestion strategy](https://github.com/zsh-users/zsh-autosuggestions#suggestion-strategy)?

Side note: while using it, you will also probably also want to enable [asynchronous mode](https://github.com/zsh-users/zsh-autosuggestions#enable-asynchronous-mode) since generating completions can sometimes take a relatively long time.

**Comment by manjunathb4461** [comment]
thanks Eric

**Comment by NightMachinary** [comment]
[**@Eric Freese**](https://github.com/ericfreese) commented on [Feb 11, 2021, 8:15 PM GMT+3:30](https://github.com/zsh-users/zsh-autosuggestions/issues/584#issuecomment-777631713 "2021-02-11T16:45:13Z - Replied by Github Reply Comments"):
> Hi, have you tried using the [`completion` suggestion strategy](https://github.com/zsh-users/zsh-autosuggestions#suggestion-strategy)?
> 
> Side note: while using it, you will also probably also want to enable [asynchronous mode](https://github.com/zsh-users/zsh-autosuggestions#enable-asynchronous-mode) since generating completions can sometimes take a relatively long time.

Can we have this as another engine? completion does not return files in a lot of scenarios.

**Comment by ericfreese** [comment]
> Can we have this as another engine? completion does not return files in a lot of scenarios.

Yeah I wouldn't be opposed to this. Can you make another ticket for the feature request that explains these scenarios and why completion would not work in those cases?
