### ISSUE TITLE
The `completion` strategy prohibitively slow when fetching from network

### ISSUE THREAD

**Issue by mareq** [zsh-users/zsh-autosuggestions#597]
### Describe the bug
When [the `completion` strategy](https://github.com/zsh-users/zsh-autosuggestions/issues/111) needs to fetch information from network, the command prompt freezes.

### To Reproduce
Steps to reproduce the behavior: type any command that would attempt completion using some information from network, e.g.:
* `scp user@192.168.1.1:/home/`: it takes minutes to type the `/home/` part
* `git remote add upstream https://github.com/zsh-users/zsh-autosuggestions.git`: it takes minutes to type the `https://github.com/zsh-users/zsh-autosuggestions.git` part
* `pip install numpy`: it takes minutes to type `numpy` part
* etc. (the moment the plugin needs to fetch some completion information over network, it freezes the command prompt)

Note: `COMPLETION_WAITING_DOTS="true"` was set whole time; the dots are not displayed.

### Expected behavior
Ideally, fetch information from network asynchronously on background (is the `COMPLETION_WAITING_DOTS="true"` setting meant for this and this means that it does not work as it shoud?).

Additionally, provide setting to disable any network traffic originating from the plugin (this may be a useful feature on itself, regardless of this issue).

### Screenshots
N/A

### Desktop
- OS + distribution: Degian Bullseye
- Zsh version: zsh 5.8 (x86_64-debian-linux-gnu)
- Plugin version: v0.6.4 (ae315de)

### Additional context
N/A

**Comment by ericfreese** [comment]
Hi, please give the async mode a try

It will be enabled by default in the next release

https://github.com/zsh-users/zsh-autosuggestions#enable-asynchronous-mode

**Comment by mareq** [comment]
Yes, `ZSH_AUTOSUGGEST_USE_ASYNC="true"` in `.zshrc` pretty much fixes the problem. I did not know about that option, thank you!

Note: It still would be a nice feature to be able to suppress all network traffic, but that is separate thing and rated only as nice-to-have new feature -> Closing this ticket.
