### ISSUE TITLE
auto suggestions color not changing 

### ISSUE THREAD

**Issue by Tervicke** [zsh-users/zsh-autosuggestions#603]
### Describe the bug
i am on lubuntu 20.04 andi cant change the color of the auto suggestion its in default that is grey . i tried changing the color by following the steps on <a href=https://stackoverflow.com/questions/47310537/how-to-change-zsh-autosuggestions-color>here</a>
the autosuggestion is working but the colors are not being changed i tried restarting the terminal and also using different values 
i used this line <br>
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=014'

**Comment by TheBabu** [comment]
I can confirm this bug:

It seems to be an issue with zsh upgrading from 5.8 to 5.8.1

https://fossies.org/linux/zsh/README

It perhaps has to do something with:
>    36 PROMPT_SUBST expansion is no longer performed on arguments to prompt-
   37 expansion sequences such as %F.

**Comment by Alexey104** [comment]
The same problem for me after the latest zsh upgrade(5.8.1). Works fine after downgrading.

**Comment by Hackjaku** [comment]
Same problem here after upgrading to 5.8.1
The suggestions now are of the same color as the foreground text (and they change with different themes). After removing and reinstalling the plugin, the suggestions appear of the right color after I type the first character, but change back to fore text color after a second character is typed. Also, if I cancel a character (whichever one), the suggestion becomes correctly themed.

**Comment by AckslD** [comment]
Thanks @Alexey104, works for me :+1:

**Comment by Hackjaku** [comment]
I second this, thanks a lot!
