### ISSUE TITLE
Auto suggestion completion with ctrl + e doesn't work after adding bindkey - v to .zshrc file

### ISSUE THREAD

**Issue by Yalchin403** [zsh-users/zsh-autosuggestions#606]
### To Reproduce

```sh
% zsh -df
% source path/to/zsh-autosuggestions.zsh
% ... # what do you do to reproduce?
```

### Desktop
 - OS + distribution: 
 - Zsh version: 
 - Plugin version:

**Comment by ericfreese** [comment]
This is expected. Vi cmd mode (what `bindkey -v` enables) does not bind `^E` to `end-of-line` and `end-of-line` is what accepts the suggestion by default. You should be able to use `$` out of the box in vi mode to go to the end of the line (and accept the suggestion) but if you want to use `^E` in vi mode you'll need to bind it yourself. I think you can do this with `bindkey -a ^E end-of-line`
