### ISSUE TITLE
where is the history of auto-suggestions located? can i modify myself to make my own suggestions?

### ISSUE THREAD

**Issue by alexzanderr** [zsh-users/zsh-autosuggestions#616]
the title is pretty straight forward.
sorry if duplicate.
thanks in advance.

**Comment by ericfreese** [comment]
Yeah it uses the standard zsh history, so any modifications you make to your zsh history will be reflected in the suggestions made going forward. Run `echo $HISTFILE` to see where your zsh history is being stored.

**Comment by alexzanderr** [comment]
```shell
> echo $HISTFILE
/home/alexzander/.config/zsh/.zsh_history
```
yeah. i got it now. thanks

**Comment by alexzanderr** [comment]
its very nice it uses the standard `zsh history` file, instead of creating another one.
