### ISSUE TITLE
make it fuzzy

### ISSUE THREAD

**Issue by 257** [zsh-users/zsh-autosuggestions#62]
i don't know if it's possible right now but make all suggestions *inline* and make them fuzzy. much line fzf:
![](https://raw.github.com/junegunn/i/master/fzf.gif)

this should go nicely with @jirutka's autosuggest-execute-suggestion (https://github.com/tarruda/zsh-autosuggestions/pull/61)

**Comment by chenglou** [comment]
FWIW, [Auto-fu](https://github.com/hchbaw/auto-fu.zsh) does the inline part. Been a bit difficult to set up, but works.

**Comment by ericfreese** [comment]
The bit of code responsible for fetching a suggestion is [here](https://github.com/tarruda/zsh-autosuggestions/blob/master/src/suggestion.zsh).

You should be able to play around for now by overriding the `_zsh_autosuggest_suggestion` function somewhere in your `.zshrc` after sourcing the plugin.

**Comment by chenglou** [comment]
@ericfreese any plan to make them list the suggestions like an autocomplete menu?

**Comment by ericfreese** [comment]
Not planning to do that currently. I think the idea of this plugin is to match closely the behavior of the fish autosuggest feature, which, as far as I know, doesn't have this option.

Definitely open to new ideas though. This could be pretty cool.

**Comment by chenglou** [comment]
Totally understand. And it'd probably change the plugin too much.

But in case you're ever interested, that menu autocomplete changed my CLI productivity dramatically. It's literally the equivalent of having autocomplete vs not:

![asd](https://cloud.githubusercontent.com/assets/1909539/12878337/066a4788-cdf1-11e5-91b1-9f82fed1fe6d.gif)

**Comment by PythonNut** [comment]
Does anyone know what would be required to make this happen? In particular, since we can now fetch suggestions from completion, some of the work has already been done.

I'm currently using both `auto-fu` and `zsh-autosuggestions` and I'm pretty interested in dropping `auto-fu` if possible and would be willing to put in some effort to make it happen.

**Comment by ericfreese** [comment]
As I see it, there'd be two steps to this, the latter probably being the most complicated:

1) Write a suggestion strategy that returns fuzzy results or modify existing ones to support fuzzy searching.
2) Figure out how to render the fuzzily-found suggestions on the command line. For example, if I type `eo` and my suggestion strategy comes back with `echo foo` as a suggestion, how would that be shown to the user? It's easy if we show it on another line, but with this plugin the suggestions are shown inline, tacked on to the end of the buffer via `POSTDISPLAY`.

As a first step without even touching code, someone could write down a detailed proposal of the interactions and how we could render things. Could look at existing autocomplete implementations for inspiration.

**Comment by PythonNut** [comment]
@ericfreese My comment is more in reference to menu display as mentioned in #15, not the fuzzy matching specifically. Additionally, menu display as an alternative or complement to `POSTDISPLAY` would make future non-prefix matching work easier to display, which is how it relates to this issue.

**Comment by ericfreese** [comment]
I'm not sure I understand exactly what you're proposing. I'm not familiar with auto-fu. Can you write out in detail what exactly you're hoping to have implemented?

**Comment by 257** [comment]
not-so-detailed proposal i wrote years ago is here:
https://github.com/fish-shell/fish-shell/issues/1467

needs a bit of brush up indeed. i will revisit it my self.
