### ISSUE TITLE
Suggestion Is Not Italicized

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [zsh-users/zsh-autosuggestions#623]
Hello,

I am having an issue where this plugin is not italicizing the suggestion it provides. I have tried this on several terminals:

- st
- xfce4-terminal
- gnome-terminal
- konsole
- kitty

and all have this issue. The smallest configuration needed to reproduce this issue is as follows:
```
## Set active suggestion groups.
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)

## Highlight suggestions as light grey.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=242,italic"
```

**Comment by ericfreese** [comment]
Hi, I don't think that zsh supports `italic` highlighting. See the zsh documentation here (search for "The available types of highlighting are the following") to see what is supported: https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting

**Comment by FOSSilizedDaemon** [comment]
> Hi, I don't think that zsh supports `italic` highlighting. See the zsh documentation here (search for "The available types of highlighting are the following") to see what is supported: https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting

Ohh, that makes more sense. Thank you.
