### ISSUE TITLE
One word accept

### ISSUE THREAD

**Issue by rejexy** [zsh-users/zsh-autosuggestions#627]
### Is your feature request related to a problem? Please describe.

I may not have understood the configuration well enough, but it would be nice to be able to accept only one word from the suggested string.

**Comment by RyanGibb** [comment]
From the README:
> If you invoke the `forward-word` widget, it will partially accept the suggestion up to the point that the cursor moves to.

So if you have the binding set up Control-Right will do this.

Alternatively, with vi keybinds (`bindkey -v`), Esc-w-Enter or ESC-W+Enter, for a word or WORD respectively, will also work.

**Comment by NightMachinary** [comment]
@reinhrst Can we add a cycling mechanic like emacs `dabbrev-expand`? If the user invokes the one-word completor again, autosuggestions should erase the previous completion, and use the one from the next best candidate.

**Comment by reinhrst** [comment]
@NightMachinary not sure you tagged the right person here...

**Comment by ericfreese** [comment]
Closing since the original question was answered
