### ISSUE TITLE
How to bind `tab` / `ctrl + h` key to accept / clear the current suggestion without disappearing the default behavior

### ISSUE THREAD

**Issue by noraworld** [zsh-users/zsh-autosuggestions#633]
This is a help wanted, not a bug report or a feature request.

How can I bind keys as they meet the following requirements?

* If the auto-suggestion is available (when a part of command that I have not typed yet shows up with grey-colored), press the `tab` key to accept the current suggestion, otherwise the `tab` key behaves as default
* If the auto-suggestion is available (when a part of command that I have not typed yet shows up with grey-colored), press the `ctrl + h` to clear the current suggestion, otherwise the `ctrl + h` behaves as default (backward-delete-char; it deletes one character)

I have tried the following, but I realized the default behavior disappears.

```
bindkey '\t' autosuggest-accept
bindkey '^H' autosuggest-clear
```

I want to accept auto-suggestion / clear auto-suggestion by pressing `tab` key / `ctrl + h` key, but I don’t want to override the existing key bindings.

I have read [#532](https://github.com/zsh-users/zsh-autosuggestions/issues/532), but I could not resolve the problem.

Any suggestions would be greatly appreciated!

Thank you.

**Comment by ericfreese** [comment]
> If the auto-suggestion is available (when a part of command that I have not typed yet shows up with grey-colored), press the tab key to accept the current suggestion, otherwise the tab key behaves as default

I think you will need to define a custom widget for this. You can probably check if $POSTDISPLAY has non-zero length and if so run autosuggest-accept. Else call your completion widget that you currently have tab bound to. Then bind tab to that widget

> If the auto-suggestion is available (when a part of command that I have not typed yet shows up with grey-colored), press the ctrl + h to clear the current suggestion, otherwise the ctrl + h behaves as default (backward-delete-char; it deletes one character)

I would think you can tackle this a similar way. Make a custom widget that calls autosuggest-clear if the POSTDISPLAY is set. Otherwise calls backward-delete-char

**Comment by loodvn** [comment]
Thanks for the great plugin!
As a first time user, I also find tab (when suggestions are available) to be more natural than other keybindings (e.g. when I use VSCode/other IDEs I use tab to apply completion).

I understand there's the clash with zsh's tab behaviour (and the solution of keeping both is great) so just adding another vote towards adding this tab option.
