### ISSUE TITLE
Conflict with zsh-cmd-architect

### ISSUE THREAD

**Issue by Freed-Wu** [zsh-users/zsh-autosuggestions#641]
### Describe the bug

This plugin conflicts with zsh-cmd-architect. The related issue is <https://github.com/zdharma-continuum/zsh-cmd-architect/pull/1>

### To Reproduce
Steps to reproduce the behavior: (This script is smaller than the original script of issue)

```zsh
# $ uname -r
# 5.15.4-arch1-1
# $ has zsh
# ✓ zsh 5.8
# $ cat test.zsh
. ~/.zinit/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
. ~/.zinit/plugins/zui/zui.plugin.zsh
. ~/.zinit/plugins/zsh-cmd-architect/zsh-cmd-architect.plugin.zsh
# $ zsh -df
# $ . ./test.zsh
```

Press <kbd>Ctrl-T</kbd>, then press `q`

### Screenshots

![Screenshot from 2021-12-10 23-21-56](https://user-images.githubusercontent.com/32936898/145598177-61014535-9cce-4744-8270-f39d823851f7.png)

### Expected behavior

The cursor should occur after the prompt-string.

**Comment by ericfreese** [comment]
@Freed-Wu It looks like the linked PR will fix the problem from the zsh-cmd-architect side. Is there any change you'd like us to make on this side?

**Comment by Freed-Wu** [comment]
Thanks for your reply. Can I know why this bug happened? Is it a bug of zsh-autosuggestions, or a bug of zsh-cmd-architect?

**Comment by ericfreese** [comment]
My guess is it's on the zsh-cmd-architect side but I haven't looked into it. That will probably be pretty low priority for me
