### ISSUE TITLE
Up / Down Arrows to Cycle Historic Matches

### ISSUE THREAD

**Issue by nixpulvis-aetion** [zsh-users/zsh-autosuggestions#646]
Much like `fish` shell's implementation, I would like to be able to quickly cycle through my history by prefix using the <kbd>up</kbd> and <kbd>down</kbd> arrow keys. This feature is really nice especially because I'm starting to use other history tools like https://github.com/cantino/mcfly which also work with the arrow keys in this way.

It's a pretty intuitive feature, so I would probably consider this to be a good candidate for the default configuration, unless it conflicts with another popular key binding I'm unaware of.

**Comment by ericfreese** [comment]
Do `history-beginning-search-backward`/`history-beginning-search-forward` work for you?

See https://github.com/zsh-users/zsh-autosuggestions/issues/192

**Comment by nixpulvis-aetion** [comment]
@ericfreese perfect, thanks for pointing me in the right direction. I've added the following to me `~/.zshrc` and it's working as I desired now:

```zsh
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
```

How would you feel about adding this to the default configuration when you source `zsh-autosuggestions.zsh`?

**Comment by ericfreese** [comment]
> How would you feel about adding this to the default configuration when you source zsh-autosuggestions.zsh?

I'd like to keep it out of this plugin because not everyone likes to use those widgets. This plugin tries to just implement autosuggestions without having any broader opinions about how people should set up their config

**Comment by nixpulvis-aetion** [comment]
OK, fair enough.

Thanks again.

**Comment by ryancurrah** [comment]
Every time I set up a new laptop, I inevitably forget this setting, Google it, and end up right back at this issue. Feels like Groundhog Day!
