### ISSUE TITLE
Provide new completion suggestion after accepting previous completion suggestion.

### ISSUE THREAD

**Issue by hgaiser** [zsh-users/zsh-autosuggestions#648]
### Is your feature request related to a problem? Please describe.
I would like to receive new suggestions when accepting previous suggestions using the completion strategy. I'm using [fzf-suggestion](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh) in my zshrc file.

### Describe the solution you'd like
Accepting a suggestion should preferably trigger a new suggestion.

### Additional context
[Here](https://asciinema.org/a/ARyPH1gKrAU1TaD9mBYHwELi2) is a screencast of how `<Tab>` works, versus `<Right>`.

Note that the first `ls` command is accepted using `<Right>` and shows no new suggestion after accepting `foo`. The second `ls` is accepted using `<Tab>`, which does show a new (`bar`) suggestion after accepting the previous suggestion (`foo`).

This is reproducible like this:

```shell
% zsh -df
% mkdir -p foo/bar
% ZSH_AUTOSUGGEST_STRATEGY=completion
% autoload compinit && compinit
% source zsh-autosuggestions/zsh-autosuggestions.zsh
% source /usr/share/fzf/completion.zsh
% ls fo<<USE RIGHT ARROW KEY OR TAB>>
```

When not sourcing `fzf/completion.zsh` the effect of both `<Tab>` and `<Right>` are the same (it doesn't provide a new suggestion in either case).

**Comment by ericfreese** [comment]
I think the default behavior should continue to be the same because that is the way that it works in fish, which this plugin emulates.

But you can probably get something working in your own config by defining your own accept widget that does both an accept and then, if the accept changed the buffer, a fetch. I don't have time right now to write something up but something along these lines can hopefully get you started:

```
% function my-zsh-autosuggest-accept() { zle autosuggest-accept; zle autosuggest-fetch }
% zle -N my-zsh-autosuggest-accept
% bindkey '^[[C' my-zsh-autosuggest-accept
```

**Comment by hgaiser** [comment]
Yep fair enough! Thank you for the suggestion, I will go that route :). 👍
