### ISSUE TITLE
Broken after update. Arch.

### ISSUE THREAD

**Issue by gprime31** [zsh-users/zsh-autosuggestions#659]
![2022-02-14_06-45](https://user-images.githubusercontent.com/44535257/153858576-924cfc41-3f56-49c8-9d42-bdd5f6bc5ba1.png)

**Comment by ericfreese** [comment]
Hi, can you please give some more information?

**Comment by gprime31** [comment]
I typed cd    (cd space) and hit tab and that's what happens.

**Comment by ericfreese** [comment]
OK thanks. I think this is not related to this plug in and you're talking about regular zsh completion functionality. Is there something specific that makes you think that there is a problem with this plug in?

**Comment by gprime31** [comment]
reinstalled zsh and plugin, seems good now.
Thanks.
