### ISSUE TITLE
context-based auto-suggestions

### ISSUE THREAD

**Issue by atsepkov** [zsh-users/zsh-autosuggestions#66]
For commands like `cd`, `vim`, etc. the suggestion based on history alone is not always applicable/relevant in a given context (for example, if I just `cd`ed to a given directory, the latest `cd` in my history is no longer useful, relative `cd` commands are also not relevant if the path is not visible from the current directory). It may be nice to perform a check if this command is relevant based on $PWD, or allow users a way to define their own filters for relevant commands. I understand that this will not be possible for exotic commands and user scripts, but doesn't seem like it would be hard to do for common system tools (zsh already does this for its tab completion). Allowing the users to easily setup their own macros for this, on the other hand, could allow them to create more relevant filters for their own use cases (like ssh tab completion based on /etc/hosts).

**Comment by mkwmms** [comment]
👍

**Comment by stjohnjohnson** [comment]
:+1: :sheep:

**Comment by ericfreese** [comment]
The bit of code responsible for fetching a suggestion is [here](https://github.com/tarruda/zsh-autosuggestions/blob/master/src/suggestion.zsh).

You should be able to play around for now by overriding the `_zsh_autosuggest_suggestion` function somewhere in your `.zshrc` after sourcing the plugin.

**Comment by douglasjunior** [comment]
Sorry for revive this issue, but I am also looking for something similar to what we have in fish, I would like the history to be suggested by directory.

For example, I always run a complex `rm ...` command in a particular directory, but when I go back to that directory ZSH suggests the 'rm ...' that I ran most recently anywhere, not looking at that directory first.

I would like the suggestions to be something like:

1. history: based on the current directory
1. history: global
1. completion

It's possible?

**Comment by ericfreese** [comment]
@douglasjunior this might help https://github.com/ericfreese/zsh-prioritize-cwd-history

**Comment by douglasjunior** [comment]
@ericfreese yes it will help me a lot, thanks!

But this plugin works only by pressing the UP arrow, not with autosuggestions, right?

**Comment by ericfreese** [comment]
It should work with autosuggestions too so that commands from the current dir are suggested first
