### ISSUE TITLE
Invalid colors for suggestions after upgrading zsh

### ISSUE THREAD

**Issue by yaa110** [zsh-users/zsh-autosuggestions#662]
### Describe the bug
suggested words are displayed as the main text color after uprading zsh to `zsh 5.8.1 (x86_64-pc-linux-gnu)`.

### Expected behavior

![before](https://user-images.githubusercontent.com/3187511/153975325-4aae1405-ad71-43b7-896c-ca51599d2fe0.png)

Afetr upgrade:

![after](https://user-images.githubusercontent.com/3187511/153975342-e9ba651d-a3e5-403a-9eaf-a5540f8c5a77.png)

### To Reproduce
Upgrade zsh to `(x86_64-pc-linux-gnu)` on arch linux.

### Desktop
 - OS + distribution: Arch Linux (Linux username 5.16.9-arch1-1 SMP PREEMPT Fri, 11 Feb 2022 22:42:06 +0000 x86_64 GNU/Linux)
 - Zsh version: 5.8.1
 - Plugin version: a411ef3e0992d4839f0732ebeb9823024afaaaa8

**Comment by char1iechen** [comment]
Encountered the same issue here.

**Comment by Alexey104** [comment]
The same. Works fine after downgrading zsh to 5.8.

**Comment by shaeinst** [comment]
can confirm

**Comment by KarboniteKream** [comment]
If you use this plugin with `zsh-syntax-highlighting`, the issue is on their side: https://github.com/zsh-users/zsh-syntax-highlighting/issues/857

**Comment by Alexey104** [comment]
> If you use this plugin with `zsh-syntax-highlighting`...

Thank you, updating `zsh-syntax-highlight` plugin fixed the problem.

**Comment by HuangfuStar** [comment]
so am i
