### ISSUE TITLE
bad file descriptor error

### ISSUE THREAD

**Issue by flaviusbuffon** [zsh-users/zsh-autosuggestions#669]
### Describe the bug
Often notice me with this output:
```
_histdb_query_batch:7: 23: bad file descriptor
```
### Screenshots

![image](https://user-images.githubusercontent.com/44057232/157870374-0787395c-db98-47a4-9bb7-c7aa72c1859c.png)

### Desktop
 - OS + distribution: Arch Linux 
 - Zsh version: 5.8.1
 - Plugin version: newest

**Comment by ericfreese** [comment]
This looks like it might be related to [zsh-histdb](https://github.com/larkery/zsh-histdb) Have you tried posting on that projects issue tracker?

**Comment by flaviusbuffon** [comment]
Sorry for my fault. If u can, please delete this issue. I will post this issue on zsh-hisdb project.
