### ISSUE TITLE
Issue with tab completion

### ISSUE THREAD

**Issue by MZauchner** [zsh-users/zsh-autosuggestions#683]
### Describe the bug
When triggering autocompletion with tab, the input text does not get cleared and also cannot be deleted. Hard to explain, but here is a screenshot attached. The text typed before triggering tab completion was "spec". When cycling through suggestions with tab, the text "spec" remains at the beginning followed by the suggestion. "spec" in this case cannot be deleted with backspace and only disappears when the terminal window is resized. The only other plugin I am using is the syntax highlighting plugin. 
Any idea what could cause this?
![report](https://user-images.githubusercontent.com/20087213/162897188-69580547-2c3a-4624-98f8-55848af9580b.png)

This seems to be an interaction with the agnoster theme. Has anyone found a solution for this?

**Comment by Devarth123** [comment]
bro this is not a zsh-autosuggestions bug,
even after removing the plugin it still exists

**Comment by Devarth123** [comment]
this bug can be fixed my putting this in your  ~/.zshrc

"export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8"






original post -https://github.com/ohmyzsh/ohmyzsh/issues/1905

**Comment by Contentsearch** [comment]
> this bug can be fixed my putting this in your ~/.zshrc
> 
> "export LC_ALL=en_US.UTF-8 
      export LANG=en_US.UTF-8"
> 
> original post -[ohmyzsh/ohmyzsh#1905](https://github.com/ohmyzsh/ohmyzsh/issues/1905)

same issue on windows11, 
but it doesn't  work .
I've tried other languages as well, but it doesn't work.
 and my `.zshrc` config flow:
```bash

export ZSH="$HOME/.oh-my-zsh"  
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

ZSH_THEME="robbyrussell"
 plugins=(git  
          zsh-syntax-highlighting
zsh-autosuggestions
	 )

source $zsh/oh-my-zsh.sh
```

how do i do that ... 
When I type some characters and then use Tab after the line jumps and can't be deleted
<img width="925" alt="image" src="https://github.com/zsh-users/zsh-autosuggestions/assets/51782090/47394ac6-0548-4689-8e78-1f0a3e0b0bbb">
