### ISSUE TITLE
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE doesn't work typing forward, but works when I hit backspace

### ISSUE THREAD

**Issue by dillonhmayhew** [zsh-users/zsh-autosuggestions#684]
### Describe the bug
The ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE is set to the default fg=8. When I start typing, the text appears just as plain white terminal text. But if I hit backspace, the fg=8 is satisfied.

### Screenshots
Typing forward:
![image](https://user-images.githubusercontent.com/58822522/164256880-f8a415f2-ece6-4048-aa49-bbae6f2f9c51.png)
Hitting backspace:
![image](https://user-images.githubusercontent.com/58822522/164257161-45c9d3c1-3e6b-45d5-9fa6-45acd90760db.png)

### Desktop
 - OS + distribution: Debian GNU/Linux bookworm/sid 11-updates (Debian Testing)
 - Zsh version: zsh 5.8.1 (x86_64-debian-linux-gnu)
 - Plugin version: v0.7.0

### Additional context
I also have this identical setup on Ubuntu 20.04.4 LTS and Raspbian 10, except the ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE is respected at all times.

**Comment by D3PSI** [comment]
same issue here, except in my setup the backspace part does not work either

**Comment by jerzywilczek** [comment]
@dillonhmayhew 
I had the same problem and removing the ```zsh-syntax-highlighting``` plugin and downloading a newer version of it solved it completely.

**Comment by dillonhmayhew** [comment]
> 

Thank you @jerzywilczek 

Solution for those who use oh-my-zsh:
`rm -rf ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting`

`git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting`

Link to oh-my-zsh install for this plugin:
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md

This fixes the issue.

**Comment by D3PSI** [comment]
Thank you @jerzywilczek , this really does fix the issue it seems. Thanks @dillonhmayhew  for providing the omz-script.

**Comment by diminutivesloop** [comment]
So I didn't have zsh-syntax-highlighting installed at all and I still had this issue. I ended up installing it since why not, but ideally this bug should be fixed for the default install as well, right?
