### ISSUE TITLE
vi-mode will select auto-suggestion

### ISSUE THREAD

**Issue by vmizener** [zsh-users/zsh-autosuggestions#689]
### Describe the bug
When in vi-mode, the auto-suggestion text is selectable.

### To Reproduce

```sh
% zsh -df
% source zsh-autosuggestions.zsh
```
Then typing `s<ESC>A<Return>` will rerun the source command.

### Expected behavior
Typing `s<ESC>A<Return>` should run "s".

### Desktop
 - OS + distribution: Ubuntu 20.04.4 LTS
 - Zsh version: zsh 5.8.1
 - Plugin version: a411ef3e0992d4839f0732ebeb9823024afaaaa8

**Comment by ericfreese** [comment]
`A` is bound to `vi-add-eol` in the default `vicmd` keybinding (vi mode). By default this plugin binds that widget to accept the suggestion if the cursor is at the end of the buffer, which it is in your example.

If you don't want that behavior, you can remove `vi-add-eol` from the list of widgets that accept suggestions by running something like this:

```
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(${ZSH_AUTOSUGGEST_ACCEPT_WIDGETS:#vi-add-eol})
```
