### ISSUE TITLE
conflict with shell native autocompletion

### ISSUE THREAD

**Issue by pedrocosta012** [zsh-users/zsh-autosuggestions#693]
When pressing the "tab" key (to complete the name of the repository where I want to navigate), if there is more than one repository with the same typed initials, the typed snippet is repeated at the beginning of the line (it is not possible to delete it using backspace ).
This is a purely visual error, but it is quite annoying.

Typing:
![Captura de tela de 2022-06-22 12-18-46](https://user-images.githubusercontent.com/48810920/175068061-807fb424-93af-4de2-9d2e-a5514c082a91.png)

And pressing "tab", this happens:
![Captura de tela de 2022-06-22 12-17-49](https://user-images.githubusercontent.com/48810920/175068431-465f3226-9c3a-4be5-a2b6-6b2693096214.png)

And as much as I insist this part of the code is not deleted:
![Captura de tela de 2022-06-22 12-17-25](https://user-images.githubusercontent.com/48810920/175069424-3ded4e4d-4521-4822-8697-690afca99cb3.png)

But new commands typed still work!

**Comment by tors** [comment]
i have the same issue!

**Comment by renaldofreire** [comment]
Same here.

**Comment by zxzxm** [comment]
same issue!

**Comment by Devarth123** [comment]
guys please have some time to search for  your issue in the issue tab before opening a new issue 

check this thread https://github.com/zsh-users/zsh-autosuggestions/issues/683

**Comment by pedrocosta012** [comment]
Thanks guy, this solution actually works!
I even looked for it but couldn't find it.

**Comment by prosk-sudo** [comment]
This solution does not work for me, any other suggestions? :(
