### ISSUE TITLE
How should I change my autosuggestions config?

### ISSUE THREAD

**Issue by bluebambu** [zsh-users/zsh-autosuggestions#695]
Hi, I install zsh-autosuggestions with `manual` installation method. I'm trying to change the config to change the suggesting strategy. How exactly should I change it?  do I need to do things like this? 

```
# Strategies to use to fetch a suggestion
# Will try each strategy in order until a suggestion is returned
(( ! ${+ZSH_AUTOSUGGEST_STRATEGY} )) && {
	typeset -ga ZSH_AUTOSUGGEST_STRATEGY
	ZSH_AUTOSUGGEST_STRATEGY=(history)
}
ZSH_AUTOSUGGEST_STRATEGY=(completion)  <<<----
```

I  tried and it seems not working... 

And I also wonder, after I modify the `config.zsh` file, how do I make it active?  `source xxx/zsh-autosuggestions.zsh` seems not working for me.  

thanks.

**Comment by ic-768** [comment]
If you have a `.zshrc` file you can do all your configuration there ( no need to mess with `config.zsh` )

E.g.


```
ZSH_AUTOSUGGEST_STRATEGY=(completion)
source xxx/zsh-autosuggestions.zsh
```

and it should work
