### ISSUE TITLE
zsh autosuggest completion not working.

### ISSUE THREAD

**Issue by drjkpalli** [zsh-users/zsh-autosuggestions#699]
**ZSH_AUTOSUGGEST_STRATEGY=(history completion)**

Hi, the completion strategy is not working for me on Mac OS Monterey. 
I am using oh my zsh

History suggestion works great but completion strategy doesn't work at all.
Documentation says   zpty   module is required. 
Internet says it comes pre-installed with the latest versions of zsh.
is there a way to install it if it doesn't come pre-installed ?

**Comment by codeagencybe** [comment]
I also can't get autosuggestion working on my Mac M1 with Monterey. 
Oh my zsh is working fine, powerlevel10k theme is working fine but nothing from zsh plugins wants to work. 

I already tried uninstalling everything and re-install, same problem. 
Is there a known problem maybe on MacOS M1 SoC or Monterey?

**Comment by Ice1187** [comment]
I also can't get completion strategy to work on my Macbook M2 with Monterey.

**Comment by kumarsaroj18** [comment]
Yes, I was also facing issue with my newly purchased Mac M1 with Monterey OS.
The problem got installed by removing plugins=(git zsh-autosuggesions) section and manually adding entry as the bottom-most line.
[checkout here](https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#manual-git-clone)
Don't forget to thumbs-up, if it solves your problem

**Comment by codeagencybe** [comment]
I got it solved by completely deleting .ohmyzsh folder and re-run the installation. 
I think the problem is that latest M1 MacOS by default ships zsh as shell but something not fully compatible with all plugins. 
Deleting everything and manually installing it with Homebrew did seem to fix the problem.

**Comment by BigBoulard** [comment]
Hi guys,

Same problem here but using `homebrew` on MacOS Monterey (12.6.1) on zsh (and `starship` prompt). Just ran the brew script but I can't find any info about any additional configuration if needed.

**Comment by davisssamuel** [comment]
Same issue here. Installed using `brew` on Intel Core i5 running macOS Monterey 12.6.3. `history` works fine, but `completion` does not work at all.

**Comment by Marcos-A** [comment]
I'm experiencing the same problem as @davisssamuel. Installed by cloning the repository on Intel Core i7, running macOS Ventura 13.2.1 on zhs with starship prompt.

**Comment by Marcos-A** [comment]
I'm experiencing the same problem as @davisssamuel. Installed by cloning the repository on Intel Core i7, running macOS Ventura 13.2.1 on zhs with Starship prompt. I'm not using Oh My Zsh.

**Comment by Marcos-A** [comment]
I'm experiencing the same problem as @davisssamuel. Installed by cloning the repository on Intel Core i7, running macOS Ventura 13.2.1 on zhs with Starship prompt. I don't have Oh My Zsh installed.

**Comment by emko** [comment]
same i am on Fedora,  history works but completion does not

**Comment by Yarden-zamir** [comment]
Same here, m1 mac

**Comment by WIIASD** [comment]
Same issue here on Amazon Linux 2

**Comment by gnsalok** [comment]
### Please validate  below points to fix `zsh-autosuggestions`

1. Make sure you do not define `plugins=()` twice in `~/.zshrc` file. Sometimes while installing `Oh My Zsh` and  `Powerlevel10k`, `plugins=(git)` automatically gets added, and you end up getting added it twice.
2. In `~/.zshrc` file, `plugins=(git)` line should come before `source $ZSH/oh-my-zsh.sh`. 

If you mess up with step 2, you will end up debugging for hours.

**Comment by FahimFBA** [comment]
I followed the issue on macOS Sonoma like below:

1. Ran this: `git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions` to clone and save them in the zsh's plugin's directory.
2. Opened the config using `open ~/.zshrc`
3. Changed `plugins=(git)` to `plugins=(git zsh-autosuggestions)`
4. Reloaded the config using `source ~/.zshrc`

It worked flawlessly!

**Comment by mayank-allen** [comment]
@FahimFBA can we connect, I am doing the same thing but not working for me :(

**Comment by FahimFBA** [comment]
> 4\. source ~/.zshrc

Sure! Give me an email.

**Comment by mayank-allen** [comment]
@FahimFBA mayank7577@gmail.com, can we connect on gmeet ? please join this-
To join the video meeting, click this link: https://meet.google.com/axd-fjys-gbg
Otherwise, to join by phone, dial +1 786-802-2337 and enter this PIN: 646 034 494#
To view more phone numbers, click this link: https://tel.meet/axd-fjys-gbg?hs=5

**Comment by FahimFBA** [comment]
> @FahimFBA Hey it was working, the issue was because of my theme I was not able to see suggestions

That's great to hear!

**Comment by sainttttt** [comment]
Having the same problem on macOS ventura. tried installing through brew and direct git clone. Neither works. Any ideas on how to fix?

**Comment by sebasjimenez10** [comment]
I was running into this same issue and was able to get it working by completely restarting iTerm... not even using the `source` command was working, hope this helps 🙂

**Comment by lucasmaffazioli** [comment]
For me it was this random line

# bindkey              '^I' menu-select
# bindkey "$terminfo[kcbt]" menu-select


Always go back to basics:
>> Remove everything from your config except for zsh-autocomplete. Does the problem still reproduce? If the problem disappears, enable other parts of your config one by one until you identify the culprit.

**Comment by XmoDVO** [comment]
To anyone who might using ubuntu, it might be the terminal color issue. I solved my problem by setting Palatte Color.
