### ISSUE TITLE
Accept line with enter/return?

### ISSUE THREAD

**Issue by donaldpipowitch** [zsh-users/zsh-autosuggestions#7]
Hi tarruda,

thanks for your plugin. I'm quite new to zsh and maybe I did something wrong, but I expected to accept a suggested line via enter/return. Instead the suggestion was removed and I accepted everything before the suggestion. I commented out two lines (https://github.com/tarruda/zsh-autosuggestions/blob/master/autosuggestions.zsh#L36, https://github.com/tarruda/zsh-autosuggestions/blob/master/autosuggestions.zsh#L147) to get my desired effect. Can I get the same effect somehow without modifying the source?

**Comment by politicus** [comment]
Hi @tarruda

New to zsh/fish, I found your plugin very interesting and tried to make it work. Before installing it, I expected to only have to write a few letters, hit enter to have the suggested words accepted.

At first, I followed the readme file and added "bindkey '^ ' autosuggest-accept" to my zshrc file. 

I found the solution (write a few words, hit ctrl+space, then enter) not as efficient as efficient as it could be (i.e. write a few letters, hit enter, have the suggested words accepted).  

Then, I tried to remap the widget "autosuggest-accept". I couldn't find any answer as I do not want to use the ctrl key and know nothing about the "symbols" (hex code ?) used to represent the keys. 

After a few unsuccessful remapping trials, I then, tried to follow your answer to @donaldpipowitch  and tried to use "autosuggest-accept-suggested-small-word". I got the error: "No such widget 
 autosuggest-accept-suggested-small-word". I saw that the widget does exist but the function don't [here](https://github.com/zsh-users/zsh-autosuggestions/issues/48).

This leads me to  two questions :

How can I "remap autosuggest-accept" to "cmd+u" or "alt+x"? Or any other keys combination as long I do not have to use the ctrl key.

How can I make the widget "autosuggest-accept-suggested-small-word work"?

Thank you.

zsh 5.4.2
Mac OS X 10.12.6
