### ISSUE TITLE
Highlight style has disappeared and I can't get it back!

### ISSUE THREAD

**Issue by sammy88888888** [zsh-users/zsh-autosuggestions#704]
### Describe the bug

Recently my zsh-autosuggestions suggestion colour has changed to be the same colour as the text I've written and I can't get it back, see the screen shot below.

I've tried updating my `.zshrc` as suggested in the docs just to see if anything changes, but it seems to have no effect:

```sh
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ff00ff,bg=cyan,bold,underline"
```

### Expected behaviour
To retain the original suggestion highlight colour.

### Screenshots
<img width="201" alt="Screenshot 2022-09-06 at 10 20 56" src="https://user-images.githubusercontent.com/10332775/188598340-a413d0f5-5353-401b-be99-6fd536eb74de.png">

### Desktop
 - OS + distribution: Mac M2 OSMonterey v.12.5.1 
 - Zsh version: 5.8.1
 - Plugin version: v0.6.4

**Comment by srntqn** [comment]
@sammy88888888  Hi! 

I had the same problem as you, fixed it using this instruction:

https://github.com/zsh-users/zsh-autosuggestions/issues/684#issuecomment-1110988619

**Comment by sammy88888888** [comment]
Amazing, should have spotted that. Thanks, that solved the problem!

**Comment by Soooda** [comment]
In addition to this weird behavior, I also found running `omz reload` will temporarily enable `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` to take effect (until you close the current terminal session) while simply running `source ~/.zshrc` does not. 

Nonetheless, #684 is the solution for me, should have figured that the outdated version was causing the matter. I am just surprised as I thought `omz update` would do all the version updating stuff for me.

**Comment by Jasmeet107** [comment]
this is still happening to me, even after #684 :( any other ideas?
