### ISSUE TITLE
prefix matching not working on  Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1063-aws x86_64)

### ISSUE THREAD

**Issue by xianggao001** [zsh-users/zsh-autosuggestions#714]
### Describe the bug
OS:   Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1063-aws x86_64)
zsh version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

I installed zsh-autosuggestions w/ manual installation method. it can autosuggest things when I type, but if I press UP and DOWN to scroll history, it only show plain history but not prefix history.  Is there a config to force the prefix match? 

my .zshrc 
```
autoload colors && colors

##### enable auto-suggestion & syntax-highlight
 source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
 source /home/xianggao/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

```

I checked using `zsh -df` and in it, the history prefix match can work normally.  But as you can see I don't have too many things in my zshrc.   Not sure where the issue is...

thank you!

**Comment by ericfreese** [comment]
>  if I press UP and DOWN to scroll history, it only show plain history but not prefix history

This plugin doesn't have any control over this behavior. I think you may be looking for this? https://unix.stackexchange.com/a/97844
