### ISSUE TITLE
[question] Can any repo to be created like sphinx-contrib/github-administration

### ISSUE THREAD

**Issue by Freed-Wu** [zsh-users/zsh-autosuggestions#720]
Hey, I notice

> If you are interested in hosting a project here, ping one of the organization owners on IRC (libera.chat / #zsh-users), Matrix or Gitter.

Can we have a repo like [sphinx-contrib/github-administration](https://github.com/sphinx-contrib/github-administration/) to do this work? It should be more convenient than IRC weechat/irris/...

TIA!

**Comment by ericfreese** [comment]
This isn't really the right place for this question. It would be more likely to be addressed if you went through one of those mentioned methods of communication https://github.com/zsh-users

I'm not in a position to make a change like this since I'm only responsible for this repo.
