### ISSUE TITLE
How can I autocomplete one part of autosuggested path at a time? ("forward dir/")

### ISSUE THREAD

**Issue by Andrew15-5** [zsh-users/zsh-autosuggestions#722]
I know that I can use `forward-char` with `ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS` to be able to autocomplete one character at a time. Also, I know that `forward-word` can be used to autocomplete one word (anything without spaces) at a time.

I need to autocomplete one directory at a time (`forward-dir`), that is, until and including next `/` in "word" in autosuggestion:

```sh
*I typed 4 chars and autosuggestion shows up*
vi dir1/dir2/dir3/file
   ^

*hitting forward-word*
vi dir1/dir2/dir3/file
                      ^

*hitting forward-char (partial)*
vi dir1/dir2/dir3/file
    ^

*what I need*
vi dir1/dir2/dir3/file
       ^

*after that I can do something like this (with ZSH_AUTOSUGGEST_STRATEGY=(history completion) set)*
vi dir1/otherdir/file
        ^

vi dir1/otherdir/file
                ^

vi dir1/otherdir/a.txt
                 ^

vi dir1/otherdir/a.txt
                      ^
```

![vi d](https://user-images.githubusercontent.com/37143421/217805150-5a6ab3d7-cdc5-48ce-842c-a58fa4ff7b14.png) (init)

![forward-word](https://user-images.githubusercontent.com/37143421/217805231-6832a283-9a0a-471a-a936-cb115d57f89d.png) (forward-word)

![forward-char](https://user-images.githubusercontent.com/37143421/217805363-83963625-6856-4fa2-af2c-70fac9ce3da3.png) (forward-char)

![what I need](https://user-images.githubusercontent.com/37143421/217805479-17badd0a-95ed-452f-b4fc-e455a6f358d7.png) ("forward dir/")

![image](https://user-images.githubusercontent.com/37143421/217805793-6c04f5bd-d44d-41e5-a7ac-03c08e0b216a.png) (start typing different dir)

![image](https://user-images.githubusercontent.com/37143421/217805869-05aae36d-f603-4601-a142-cbd7f219e452.png) ("forward dir/")

![image](https://user-images.githubusercontent.com/37143421/217805989-9e5618e2-bda0-4148-9cee-7773a36f8fd9.png)
![image](https://user-images.githubusercontent.com/37143421/217806063-10ec1b07-a2e9-4f05-9e24-49870a8bf83b.png)

I noticed that the desirable behavior is shown by hitting Tab key, but only for the first directory in autosuggestion: if I keep on pressing Tab, it will just start changing autocompleted directory (and show the list of all dirs) in next level and not appending directories from the first autosuggestion. Or I can type 1st char of dir of each level and then press Tab — then it will be like I want but with extra keystrokes. (I don't want to type 1st char of **each** dir in autosuggested path, only the very 1st char to show the autosuggested path).

**Comment by ericfreese** [comment]
Does this help? https://unix.stackexchange.com/a/48589

**Comment by Andrew15-5** [comment]
Yes, it does! Thank you.
