### ISSUE TITLE
add option to not include suggestions for commands that previously terminated with non-zero exit code

### ISSUE THREAD

**Issue by Eboubaker** [zsh-users/zsh-autosuggestions#729]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when this plugin suggests from a previously terminated command with non-zero exit code (when you do typing error, syntax error, forgot sudo, etc..)

### Describe the solution you'd like
add option to not include suggestions for commands that previously terminated with non-zero exit code.

**Comment by ericfreese** [comment]
See #424
