### ISSUE TITLE
Remove 1 suggestion

### ISSUE THREAD

**Issue by lacherogwu** [zsh-users/zsh-autosuggestions#734]
Hey, by mistake I typed some command, how do I remove it from history?

**Comment by merziy** [comment]
This is a question for shells, and not this plugin. Your shell history is saved into a file, so if you are using a zsh shell, type this into your terminal.
`vim ~/.zsh_history`
Then, find and delete the command from the shell history, which will cause this plugin to 'forget' it.

**Comment by lacherogwu** [comment]
Great thanks for your answer!
