### ISSUE TITLE
Suggestions are not being cleared after not accepting

### ISSUE THREAD

**Issue by Allaman** [zsh-users/zsh-autosuggestions#746]
### Describe the bug

The auto-suggested text is not distinguishable if not being accepted.
For instance, in the following screenshot, I entered `cd temp<CR>` and afterward `cd<CR>`. Before hitting CR in the last command, I could see "temp" in a dark gray color. As I didn't accept the suggestion, my expectation would be that the suggestion stays displayed in the same dark gray color on my terminal, which I am quite sure was the case some time ago.
<img width="136" alt="image" src="https://github.com/zsh-users/zsh-autosuggestions/assets/12184268/0e4a4923-8582-4777-aae1-b0dc25be4c35">

Unfortunately, I had a hard time creating a reproducible minimal demo. What I recognized is, that the behavior is correct when I remove either of these lines from my config:

* `source $HOME/.shell/fast-syntax-Highlighting/fast-syntax-highlighting.plugin.zsh`
* `ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-beginning-search-backward-end history-beginning-search-forward-end)`

I am also aware of [this issue](https://github.com/zsh-users/zsh-autosuggestions/issues/698) and [that issue](https://github.com/zsh-users/zsh-autosuggestions/issues/688). I played around with different style configurations and installed zsh 5.9 as well. No success.

The issue also occurs on kitty and alacritty and on my NixOS box. This drives me nuts, and I have a very hard time to tackle this down. 

Any help or hint is much appreciated! 

For reference – my config:
* https://github.com/Allaman/dots/tree/main/dot_shell
* https://github.com/Allaman/dots/blob/main/dot_zshrc

### Desktop
 - OS + distribution: macOS 12.6 (Apple Silicone)
 - Zsh version: 5.8.1
 - Plugin version: a411ef3 (0.7.0

**Comment by jonaustin** [comment]
@Allaman also having this issue; were you able to fix without completely removing `fast-syntax-highlighting`?

**Comment by Allaman** [comment]
@jonaustin to be honest, I don't know my solution anymore. I see in my config that I use fast-syntax-highlighting and no issues. But I am also in the middle of some refactoring, so my repo is not up to date
