### ISSUE TITLE
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE

### ISSUE THREAD

**Issue by Aur0nd** [zsh-users/zsh-autosuggestions#752]
### Describe the bug
let's assume that we want to type ls -lha ~/Desktop
if I type the whole command then everything works as expected, but if I type "ls -lh" and then accept the suggestion, everything after "ls -lh" is going to have the suggestions color (Greyed out or whatever color I choose).

```sh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=4'
```

<img width="252" alt="Screenshot 2023-07-20 at 14 42 58" src="https://github.com/zsh-users/zsh-autosuggestions/assets/71910902/80b6604a-3b69-429a-88f8-cd4c88ca0de6">

### Desktop
 MacOS Sonoma

**Comment by Goncharo** [comment]
Yup same thing here, if anyone has a workaround that'd be great

<img width="376" alt="Screenshot 2023-07-22 at 10 00 41 AM" src="https://github.com/zsh-users/zsh-autosuggestions/assets/6843426/532ed321-3522-41cb-8d66-2a0b33d14922">

**Comment by hectorhuertas** [comment]
Also happens on Arch

**Comment by Hacksore** [comment]
I have this set:
```
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
```

This is what happens to me in neovim+tmux:
![image](https://github.com/zsh-users/zsh-autosuggestions/assets/996134/8ef9b607-082f-413a-ba61-84745ab70b4d)


This is what happens when using only tmux
![image](https://github.com/zsh-users/zsh-autosuggestions/assets/996134/7b5d5170-c595-47f7-98bc-82fb3a383ee8)

I'm not sure if this issue is related but it's really hard to use the plugin 😢.

**Comment by alifhughes** [comment]
setting `export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#f1d687"` in my `~/.zshrc` worked for me, it is a similar colour to the default.

**Comment by ivanjermakov** [comment]
I had the same problem with
```
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#aaa"
```
![image](https://github.com/zsh-users/zsh-autosuggestions/assets/26609879/81ea5c03-4d2c-43f6-9be3-58b6e385c0a3)
It works with full color hex
```
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#aaaaaa"
```
![image](https://github.com/zsh-users/zsh-autosuggestions/assets/26609879/7fece3c1-8275-43a3-b7bc-e63977d25e0c)

**Comment by patrick96** [comment]
Problem seems to be that when `fg=7` (or anything below 8, at least in my terminal) is added to [`region_highlight`](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Zle-Widgets) (which is doing the highlighting), it is implicitly replaced by the color name. When undoing the highlighting, this plugin searches for `fg=7` exactly to replace it, which then fails.

It's likely more robust to use the `memo` property for this
