### ISSUE TITLE
Escaping symbol added after every word to a Folder name

### ISSUE THREAD

**Issue by iaroslavnikitin** [zsh-users/zsh-autosuggestions#774]
### Describe the bug
Escaping symbol added after every word to a Folder name, e.g. when typing a command `cd untitled folder` it suggests and writes – `cd untitled\ folder`

### To Reproduce
installed simply zsh-autosuggestions and zsh-syntax-highlighting, started to use it and the issue appears right away

### Expected behavior
when typing a command `cd untitled folder` it suggests and displays `cd untitled folder`

### Screenshots
<img width="324" alt="Screenshot 2023-12-28 at 10 58 29 PM" src="https://github.com/zsh-users/zsh-autosuggestions/assets/42630604/93575161-7c29-4919-bc38-a2511c750a4a">

### Desktop
 - OS + distribution: macOS Sonoma 14.1.2 (23B92)
 - Zsh version: 5.9
 - Plugin version: v0.7.0

**Comment by Saecki** [comment]
I'm not a maintainer, but this is definitely intended. You can try out what happens if you don't add the backslash and run the `cd` command.

**Comment by iaroslavnikitin** [comment]
@Saecki, i do not add the backslash, it's added automatically by autosuggestion / autocompletion to every single folder that has more than 1 word in a title and a space between those words:

<img width="315" alt="Screenshot 2024-01-08 at 7 20 23 PM" src="https://github.com/zsh-users/zsh-autosuggestions/assets/42630604/2c7279cd-ebb9-4dea-995e-013576a5f311">

**Comment by Saecki** [comment]
Yes, but the `\` is necessary for your shell to understand that the two words are in fact one directory. If you would run `cd untitled folder` instead of `cd untitled\ folder`, you would get the following error:
```
❯ cd untitled folder
cd: string not in pwd: untitled
```

**Comment by iaroslavnikitin** [comment]
ah, got it, thank you, sorry for my noob's request here, closing the ticket then
